### ISSUE TITLE
Phased restart fails when ruby version changes and is specified in Gemfile

### ISSUE THREAD

**Issue by bf4** [puma/puma#1016]
Reproduce in any Puma app with:

a file `.ruby-version`

```ruby
2.2.4
```

a `Gemfile` that specifies the Ruby version by reading in the above file

```ruby
source 'https://rubygems.org'
ruby File.read(File.expand_path("../.ruby-version", __FILE__)).strip
```

a `config/puma.rb`

```ruby
require 'dotenv'

WORKERS = ENV['WORKERS'] || 3
THREAD_POOL = ENV['THREAD_POOL'] || 16
ENVIRONMENT = ENV['RACK_ENV'] || 'development'
PORT = ENV['PORT'] || 3000

prune_bundler
environment ENVIRONMENT
workers WORKERS
threads THREAD_POOL, THREAD_POOL
port PORT

if ['production', 'staging'].include?(ENVIRONMENT)
  pidfile '/var/run/puma.pid'
else
  quiet
end
```

with Puma running

```ruby
bundle exec puma -C config/puma.rb
```

and we install the latest ruby ppa, version `2.2.5` and deploy code which changes `.ruby-version`

```diff
-2.2.4
+2.2.5
```

and we sending `SIGUSR2` for a phased restart:

Then:

Then the worker continuously fails to boot logging (partial output)

```
[13790] + Gemfile in context: /srv/web/Gemfile
[31mYour Ruby version is 2.2.4, but your Gemfile specified 2.2.5[0m
```

It seems we can't do a phased restart when upgrading Ruby version, need to restart the server, but we're wondering if we're doing anything wrong or if there's a programmatic way to handle a Ruby upgrade.

larger output snippet, reproduced on my dev machine

```
15:25:31 web.1    | started with pid 1552
15:25:32 web.1    | * Pruning Bundler environment
15:25:32 web.1    | [1552] Puma starting in cluster mode...
15:25:32 web.1    | [1552] * Version 3.4.0 (ruby 2.2.5-p319), codename: Owl Bowl Brawl
15:25:32 web.1    | [1552] * Min threads: 16, max threads: 16
15:25:32 web.1    | [1552] * Environment: development
15:25:32 web.1    | [1552] * Process workers: 3
15:25:32 web.1    | [1552] * Phased restart available
15:25:32 web.1    | [1552] * Listening on tcp://0.0.0.0:5000
15:25:32 web.1    | [1552] Use Ctrl-C to stop
15:25:32 web.1    | [1553] + Gemfile in context: $HOME/projects/rails_server/Gemfile
15:25:32 web.1    | [1554] + Gemfile in context: $HOME/projects/rails_server/Gemfile
15:25:32 web.1    | [1555] + Gemfile in context: $HOME/projects/rails_server/Gemfile
15:25:38 web.1    | [1552] - Worker 2 (pid: 1555) booted, phase: 0
15:25:38 web.1    | [1552] - Worker 0 (pid: 1553) booted, phase: 0
15:25:38 web.1    | [1552] - Worker 1 (pid: 1554) booted, phase: 0
15:25:48 web.1    | [1552] - Gracefully shutting down workers...
15:25:49 web.1    | [1552] * Restarting...
15:25:49 web.1    | [1552] Puma starting in cluster mode...
15:25:49 web.1    | [1552] * Version 3.4.0 (ruby 2.2.5-p319), codename: Owl Bowl Brawl
15:25:49 web.1    | [1552] * Min threads: 16, max threads: 16
15:25:49 web.1    | [1552] * Environment: development
15:25:49 web.1    | [1552] * Process workers: 3
15:25:49 web.1    | [1552] * Phased restart available
15:25:49 web.1    | [1552] * Inherited tcp://0.0.0.0:5000
15:25:49 web.1    | [1552] Use Ctrl-C to stop
15:25:49 web.1    | [1676] + Gemfile in context: $HOME/projects/rails_server/Gemfile
15:25:49 web.1    | [1677] + Gemfile in context: $HOME/projects/rails_server/Gemfile
15:25:49 web.1    | [1678] + Gemfile in context: $HOME/projects/rails_server/Gemfile



15:25:49 web.1    | $HOME/.rvm/gems/ruby-2.2.5/gems/bundler-1.12.5/lib/bundler/definition.rb:417:in `validate_ruby!': Your Ruby version is 2.2.5, but your Gemfile specified 2.2.4 (Bundler::RubyVersionMismatch)
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/bundler-1.12.5/lib/bundler.rb:91:in `setup'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (required)>'
15:25:49 web.1    | 	from $HOME/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
15:25:49 web.1    | 	from $HOME/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
15:25:49 web.1    | 	from $HOME/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/configuration.rb:292:in `rack_builder'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/configuration.rb:313:in `load_rackup'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/configuration.rb:242:in `app'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/runner.rb:133:in `app'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/runner.rb:140:in `start_server'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:239:in `worker'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `fork'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `times'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `spawn_workers'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:424:in `run'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/launcher.rb:172:in `run'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cli.rb:74:in `run'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/bin/puma-wild:31:in `<main>'
15:25:49 web.1    | $HOME/.rvm/gems/ruby-2.2.5/gems/bundler-1.12.5/lib/bundler/definition.rb:417:in `validate_ruby!': Your Ruby version is 2.2.5, but your Gemfile specified 2.2.4 (Bundler::RubyVersionMismatch)
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/bundler-1.12.5/lib/bundler.rb:91:in `setup'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (required)>'
15:25:49 web.1    | 	from $HOME/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
15:25:49 web.1    | 	from $HOME/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
15:25:49 web.1    | 	from $HOME/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/configuration.rb:292:in `rack_builder'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/configuration.rb:313:in `load_rackup'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/configuration.rb:242:in `app'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/runner.rb:133:in `app'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/runner.rb:140:in `start_server'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:239:in `worker'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `fork'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `times'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `spawn_workers'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:424:in `run'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/launcher.rb:172:in `run'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cli.rb:74:in `run'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/bin/puma-wild:31:in `<main>'

15:25:49 web.1    | $HOME/.rvm/gems/ruby-2.2.5/gems/bundler-1.12.5/lib/bundler/definition.rb:417:in `validate_ruby!': Your Ruby version is 2.2.5, but your Gemfile specified 2.2.4 (Bundler::RubyVersionMismatch)
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/bundler-1.12.5/lib/bundler.rb:91:in `setup'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (required)>'
15:25:49 web.1    | 	from $HOME/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
15:25:49 web.1    | 	from $HOME/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
15:25:49 web.1    | 	from $HOME/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/configuration.rb:292:in `rack_builder'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/configuration.rb:313:in `load_rackup'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/configuration.rb:242:in `app'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/runner.rb:133:in `app'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/runner.rb:140:in `start_server'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:239:in `worker'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `fork'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `times'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `spawn_workers'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cluster.rb:424:in `run'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/launcher.rb:172:in `run'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/lib/puma/cli.rb:74:in `run'
15:25:49 web.1    | 	from $HOME/.rvm/gems/ruby-2.2.5/gems/puma-3.4.0/bin/puma-wild:31:in `<main>'
15:25:49 web.1    | [1679] + Gemfile in context: $HOME/projects/rails_server/Gemfile
15:25:49 web.1    | [1680] + Gemfile in context: $HOME/projects/rails_server/Gemfile
15:25:49 web.1    | [1681] + Gemfile in context: $HOME/projects/rails_server/Gemfile
```

**Comment by evanphx** [comment]
Yeah, I'm not sure how/if I should fix this one. Puma uses fork to launch the workers so there is really no way to pickup a new version of ruby. If you upgrade ruby, you need to do a full restart.
