### ISSUE TITLE
"missing_extensions?" error when using 'kill -USR1'

### ISSUE THREAD

**Issue by paz-choe** [puma/puma#1034]
Hi~

puma 3.4.0, ruby 2.3.1p112 , rails 5.0.0

due to deploy, 'releases/57' directory was deleted. and using 'kill -USR1' for phased restart.

```
/home/pi/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/stub_specification.rb:148:in `missing_extensions?': undefined method `missing_extensions?' for nil:NilClass (NoMethodError)
        from /home/pi/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/basic_specification.rb:71:in `contains_requirable_file?'
        from /home/pi/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1037:in `block in find_by_path'
        from /home/pi/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1036:in `each'
        from /home/pi/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1036:in `find'
        from /home/pi/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1036:in `find_by_path'
        from /home/pi/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems.rb:189:in `try_activate'
        from /home/pi/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
        from /home/pi/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:292:in `rack_builder'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:313:in `load_rackup'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:242:in `app'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/runner.rb:133:in `app'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/runner.rb:140:in `start_server'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cluster.rb:239:in `worker'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `fork'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `times'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `spawn_workers'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cluster.rb:178:in `check_workers'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cluster.rb:442:in `run'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/launcher.rb:172:in `run'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cli.rb:74:in `run'
        from /home/pi/app/five/releases/57/vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/bin/puma-wild:31:in `<main>'
```

My puma config looks like this:

```
#!/usr/bin/env puma
app_dir = '/home/pi/app/five'

directory "#{app_dir}/current"

environment 'production'
daemonize true
pidfile "#{app_dir}/shared/pids/puma.pid"
state_path "#{app_dir}/shared/pids/puma.state"

stdout_redirect "#{app_dir}/shared/log/puma.stdout.log", "#{app_dir}/shared/log/puma.stderr.log", true

bind 'unix:///tmp/puma.sock'
workers 2
prune_bundler

tag 'rails_five'
worker_timeout 30
```
#776 is similar issue. Please, help me.. OTL

**Comment by evanphx** [comment]
The other issue is most likely somehow 2 rubygems are getting loaded into the process. Does this happen everytime for you or was it just this once?

**Comment by donce** [comment]
Hey @evanphx, @JeongHan-Choi.

I am having the same issue - `ruby 2.3.1`, `puma 3.6.0`, `rails 5.0.0`.

It happens each time old directory gets deleted.

I've checked `$LOAD_PATH` - there aren't any duplicated paths.

**Comment by JeongHan-Choi** [comment]
@donce 
if you use 'bundle exec' command, do not run puma on bundle context.
bundle context is not available when old-directory is deleted.

1. gem install puma
2. pumactl -P puma.pid -F puma_production.rb phased-restart (don't use bundle exec)

I hope everything works out well.

**Comment by donce** [comment]
@JeongHan-Choi Thanks for help.

For `phased-restart`, I am using `kill -USR1` without `bundle exec`.
For starting puma, I am using `bundle exec puma ...` - otherwise, it doesn't load gems. Do you mean I should start `puma` without `bundle exec`? How does it load gems then?

**Comment by u007** [comment]
same issue here, ruby 2.3.1 puma 3.6.0, rails 5.0.0

**Comment by u007** [comment]
i realize its attempting to start another:
puma 3.6.0 (tcp://127.0.0.1:3000,...)
it does not seems to use existing pid , and it happen 50% of the time

**Comment by JeongHan-Choi** [comment]
@donce 

Yes, You should start puma without bundle exec.
to load gems, using ['prune_bundler'](http://www.rubydoc.info/github/puma/puma/Puma%2FConfiguration%2FDSL%3Aprune_bundler) in puma's configuration.

**Comment by u007** [comment]
@paz-choe does it mean that the old directory (original) started on gets deleted from capistrano, it will starts to fail? oh damn..
anyone know  work around?

**Comment by kainosnoema** [comment]
This just started happening to us as we're testing upgrading to Ruby 2.3.1. No other configuration or version changes. Haven't had a chance to dig into workarounds yet—any tips on what's worked?

**Comment by hovancik** [comment]
Same issue here.  I use SIGUSR1 as well. Error happens on every 7th deploy. I keep 6 versions. 

```
/home/www/deploy/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/stub_specification.rb:148:in `missing_extensions?': undefined method `missing_extensions?' for nil:NilClass (NoMethodError)
```

`ruby 2.3.1`
`rails 5.0.4`
`puma 3.9.1`

puma.rb
```
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i
threads threads_count, threads_count

workers ENV.fetch("WEB_CONCURRENCY") { 2 }

environment ENV.fetch("RAILS_ENV") { "development" }

bind "unix://#{ENV.fetch('APP_DIR')}/shared/tmp/sockets/puma.sock"
pidfile "#{ENV.fetch('APP_DIR')}/shared/tmp/pids/puma.pid"
directory "#{ENV.fetch('APP_DIR')}/current"
activate_control_app "unix://#{ENV.fetch('APP_DIR')}/shared/tmp/sockets/pumactl.sock", { auth_token: 'sddsfsd' }

stdout_redirect "log/puma.stdout.log", "log/puma.stderr.log", true

prune_bundler true
```

**Comment by hovancik** [comment]
so I have tried different versions of ruby and version `2.4.1` seems to work fine.

**Comment by Frexuz** [comment]
2.4.1 seems to have fixed it for me as well.
