### ISSUE TITLE
Tests failing on FreeBSD (race condition)

### ISSUE THREAD

**Issue by jlduran** [puma/puma#1044]
I've been experiencing defunct processes (one per worker) with puma in cluster mode on FreeBSD (10 & 11), although the app seems to run fine. On Debian, the same app doesn't show any zombies.

```
[app@example.com ~]$ ps aux
USER   PID %CPU %MEM    VSZ    RSS TT  STAT STARTED    TIME COMMAND
app  14799  0.4  0.7  13904   3648  0  Ss   06:15   0:00.05 -bash (bash)
app  14798  0.2  1.4  60372   7036  -  S    06:15   0:00.02 sshd: app@pts/0 (sshd)
app  14498  0.0  3.2  84084  15536  -  S    04:51   0:02.46 ruby: puma 3.6.0 (unix:///usr/local/www/apps/test_app/
app  14499  0.0 27.9 323400 137192  -  I    04:51   0:30.44 ruby: puma: cluster worker 0: 14498 [test_app] (ruby)
app  14500  0.0 29.9 329952 146652  -  I    04:51   0:33.67 ruby: puma: cluster worker 1: 14498 [test_app] (ruby)
app  14502  0.0  0.0      0      0  -  Z    04:52   0:00.00 <defunct>
app  14504  0.0  0.0      0      0  -  Z    04:52   0:00.01 <defunct>
app  14831  0.0  0.5  21156   2612  0  R+   06:15   0:00.01 ps aux
```

I decided to run the test suite and found these two errors, I wonder if they are related:

```
===================================================================================================================
Failure:
  </\{ "workers": 2, "phase": 0, "booted_workers": 0, "old_workers": 0, "worker_status": \[\{ "pid": \d+, "index": 0, "phase": 0, "booted": false, "last_checkin": "[^"]+", "last_status": \{\} \},\{ "pid": \d+, "index": 1, "phase": 0, "booted": false, "last_checkin": "[^"]+", "last_status": \{\} \}\] \}/> expected to be =~
  <"{ \"workers\": 2, \"phase\": 0, \"booted_workers\": 1, \"old_workers\": 0, \"worker_status\": [{ \"pid\": 20707, \"index\": 0, \"phase\": 0, \"booted\": false, \"last_checkin\": \"2016-08-08T10:56:15Z\", \"last_status\": {} },{ \"pid\": 20708, \"index\": 1, \"phase\": 0, \"booted\": true, \"last_checkin\": \"2016-08-08T10:56:15Z\", \"last_status\": {} }] }">.
test_control_clustered(TestCLI)
/home/vagrant/puma/test/test_cli.rb:91:in `test_control_clustered'
     88:     s << "GET /stats HTTP/1.0\r\n\r\n"
     89:     body = s.read
     90: 
  => 91:     assert_match(/\{ "workers": 2, "phase": 0, "booted_workers": 0, "old_workers": 0, "worker_status": \[\{ "pid": \d+, "index": 0, "phase": 0, "booted": false, "last_checkin": "[^"]+", "last_status": \{\} \},\{ "pid": \d+, "index": 1, "phase": 0, "booted": false, "last_checkin": "[^"]+", "last_status": \{\} \}\] \}/, body.split("\r\n").last)
     92: 
     93:     # wait until the first status ping has come through
     94:     sleep 6
===================================================================================================================
```

```
===================================================================================================================
Failure:
  </Worker \d \(pid: \d+\) booted, phase: 1/> expected to be =~
  <"[20706] Puma starting in cluster mode...\n[20706] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity\n[20706] * Min threads: 0, max threads: 16\n[20706] * Environment: production\n[20706] * Process workers: 2\n[20706] * Phased restart available\n[20706] * Listening on unix://test/test_server.sock\n[20706] Use Ctrl-C to stop\n[20706] * Starting control server on unix://test/test_control.sock\n[20706] - Worker 0 (pid: 20709) booted, phase: 0\n[20706] - Worker 1 (pid: 20710) booted, phase: 0\n[20706] - Starting phased worker restart, phase: 1\n[20706] + Changing to /home/vagrant/puma\n[20706] - Stopping 20709 for phased upgrade...\n[20706] - TERM sent to 20709...\n[20706] - KILL sent to 20709...\n[20706] - KILL sent to 20709...\n">.
test_phased_restart_via_pumactl(TestIntegration)
/home/vagrant/puma/test/test_integration.rb:158:in `test_phased_restart_via_pumactl'
     155:     @events.stdout.rewind
     156:     log = @events.stdout.readlines.join("")
     157:     assert_match(/TERM sent/, log)
  => 158:     assert_match(/Worker \d \(pid: \d+\) booted, phase: 1/, log)
     159: 
     160:     # Stop
     161:     ccli = Puma::ControlCLI.new %W!-S #{@state_path} stop!, sout
===================================================================================================================
```

Here is a sample `Vagrantfile` that replicates the failures.  I'm installing Ruby from `pkgng` for convenience, but the same issue is present with Ruby 2.3.1 compiled using `rbenv`/`ruby-build`:

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = 'freebsd/FreeBSD-11.0-BETA4'
  config.vm.hostname = 'freebsd'
  config.vm.base_mac = '589CFC000001' # FreeBSD Bug 201904
  config.vm.network 'private_network', ip: '192.168.50.4'
  config.vm.synced_folder '.', '/vagrant', type: 'nfs'
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
    vb.customize ['modifyvm', :id, '--nictype2', 'virtio']
  end

  config.ssh.shell = 'sh'

  config.vm.provision 'shell', inline: <<-ROOT
    # Install dependencies
    pkg upgrade -y
    pkg install -y bash git-lite ragel ruby rubygem-bundler

    # Bash configuration
    mount -t fdescfs fdesc /dev/fd
    echo 'fdesc   /dev/fd       fdesc   fs  rw  0   0' >> /etc/fstab

    # Prepare the vagrant user:
    # Change its default shell to Bash
    pw usermod vagrant -s /usr/local/bin/bash
  ROOT

  config.vm.provision 'shell', privileged: false, inline: <<-VAGRANT
    # Clone the puma repo
    git clone https://github.com/puma/puma.git

    # Run the tests
    cd puma
    bundle install
    bundle exec rake
  VAGRANT
end
```

**Comment by wwood** [comment]
Hi,

I'm not a maintainer but the first one was already reported as https://github.com/puma/puma/issues/995, and I can confirm the second one: we observed it during the Guix build.

**Comment by evanphx** [comment]
Yeah, I need to fix that test, it's racey.
