### ISSUE TITLE
puma overides Port option from rack handler with default value from puma.config

### ISSUE THREAD

**Issue by chulkilee** [puma/puma#1154]
### Steps to reproduce

```sh
rails new --api --skip-listen --skip-active-record --skip-action-mailer foo1
rails new --api --skip-listen --skip-active-record --skip-action-mailer foo2

# in foo1
bin/rails s -p 3000

# in foo2
bin/rails s -p 3001
```

### Expected behavior

- foo1 runs on 3000
- foo2 runs on 3001

### Actual behavior

- foo1 runs on 3000 (correct)
- foo2 tried to run on 3000, and failed

```
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3001
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.1 (ruby 2.3.2-p217), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Exiting
/myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/puma-3.6.1/lib/puma/binder.rb:266:in `initialize': Address already in use - bind(2) for "0.0.0.0" port 3000 (Errno::EADDRINUSE)
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/puma-3.6.1/lib/puma/binder.rb:266:in `new'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/puma-3.6.1/lib/puma/binder.rb:266:in `add_tcp_listener'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/puma-3.6.1/lib/puma/binder.rb:102:in `block in parse'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/puma-3.6.1/lib/puma/binder.rb:85:in `each'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/puma-3.6.1/lib/puma/binder.rb:85:in `parse'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/puma-3.6.1/lib/puma/runner.rb:133:in `load_and_bind'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/puma-3.6.1/lib/puma/single.rb:85:in `run'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/puma-3.6.1/lib/puma/launcher.rb:172:in `run'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/puma-3.6.1/lib/rack/handler/puma.rb:51:in `run'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:296:in `start'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:79:in `start'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /myhome/tmp/foo2/bin/rails:9:in `require'
	from /myhome/tmp/foo2/bin/rails:9:in `<top (required)>'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /myhome/.rbenv/versions/2.3.2/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /myhome/tmp/foo2/bin/spring:14:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

- When I change the default port option from `config/puma.rb`, then it tries to use the new value
- When I revert changes in #1118 it works well

### System configuration

**Ruby version**: 2.3.3
**Rails version**: 5.0.0.1

**Comment by chulkilee** [comment]
For the record: workaround is passing `PORT` variable to `bin/rails`, which is picked up by puma through `config/puma.rb`, not through rack handler.

**Comment by andrew** [comment]
This change just caught me out too, had `port ENV.fetch("PORT") { 3000 }` in `config/puma.rb` but using the following command in production:

    bundle exec puma -C config/puma.rb -p 5000

When I deployed the upgrade to 3.6.1 today, it switched ports from 5000 to 3000, I'd guess because the `-p` option is no longer as important as the value in `config/puma.rb` but that's definitely a breaking change.

![screen shot 2016-11-22 at 11 42 51 am](https://cloud.githubusercontent.com/assets/1060/20522721/b594c76a-b0a9-11e6-8587-31e6eb55da6c.png)

**Comment by nateberkopec** [comment]
> I'd guess because the -p option is no longer as important as the value in config/puma.rb but that's definitely a breaking change.

Yeah, that's definitely not great/intentional side effect of #1118.

**Comment by nateberkopec** [comment]
I think I'll just revert #1118 and we'll fix TTIN properly in a future release.

**Comment by andrew** [comment]
@nateberkopec sounds good 👍

**Comment by nateberkopec** [comment]
Fixed in 3.6.2 - thanks for your patience everyone! Just getting used to the codebase so I'm still learning "if you push this lever over here..."

**Comment by evanphx** [comment]
@nateberkopec That's my fault. We're missing tests in a bunch of places as you've seen 😄

**Comment by nateberkopec** [comment]
@evanphx meh no one's perfect, we've all certainly seen much worse!

**Comment by raldred** [comment]
@nateberkopec any possibility this has been regressed in 3.7.0?

**Comment by nateberkopec** [comment]
@raldred Probably, 3.8 + Rails 5.1 will fix this issue permanently.
