### ISSUE TITLE
3.6.2 causes `RuntimeError: can't modify frozen String`

### ISSUE THREAD

**Issue by BigGillyStyle** [puma/puma#1173]
### Steps to reproduce

1. Updated from Puma from 3.6.1 to 3.6.2
2. Started ActionCable server using Rails 5.0.0.1
  * Script to start is: `bundle exec puma -p 28080 [my_rails_root]/cable/config.ru`
  * config.ru is:

    ```
    require ::File.expand_path('../../config/environment',  __FILE__)
    Rails.application.eager_load!
    
    run ActionCable.server
    ```
3. Received error:

    ```
    RuntimeError: can't modify frozen String
      [my_rails_root]/vendor/bundle/gems/puma-3.6.2/lib/puma/launcher.rb:289:in `title'
      [my_rails_root]/vendor/bundle/gems/puma-3.6.2/lib/puma/launcher.rb:284:in `set_process_title'
      [my_rails_root]/vendor/bundle/gems/puma-3.6.2/lib/puma/launcher.rb:172:in `run'
      [my_rails_root]/vendor/bundle/gems/puma-3.6.2/lib/puma/cli.rb:75:in `run'
      [my_rails_root]/vendor/bundle/gems/puma-3.6.2/bin/puma:11:in `<top (required)>'
      [my_rails_root]/vendor/bundle/bin/puma:23:in `load'
      [my_rails_root]/vendor/bundle/bin/puma:23:in `<top (required)>'
    ```
4. Changed Gemfile back to Puma 3.6.1, ran `bundle update puma`, restarted server with no errors.

### System configuration

**Ruby version**:  2.3.1
**Rails version**:  5.0.0.1

**Comment by BigGillyStyle** [comment]
This is my first time posting an issue on an open source project, so let me know how I could be of more help.

**Comment by BigGillyStyle** [comment]
I apologize.  After several hours of debugging this on my Ubuntu 14.04 box, I discovered that there were running Puma processes while I updated the Puma gem.  Once I stopped all those processes, updated Puma to 3.6.2, and then re-started them...there were no problems.
