### ISSUE TITLE
Undefined method `bytesize'

### ISSUE THREAD

**Issue by dopykuh** [puma/puma#1208]
### Steps to reproduce
- Don't know. (Possibly when using grape error's?)

### Trace

```
DELETE /api/v1/ldap?ip=88.99.91.125 HTTP/1.1" 204 - 0.1886
Read error: #<NoMethodError: undefined method `bytesize' for #<Hash:0x000000025813d8>>
/var/lib/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:609:in `handle_request'
/var/lib/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:415:in `process_client'
/var/lib/gems/2.3.0/gems/puma-3.7.0/lib/puma/server.rb:275:in `block in run'
/var/lib/gems/2.3.0/gems/puma-3.7.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

### System configuration

**Ruby version**: 2.3.1p112
**Rack version**: 2.0.1
**Grape version**: 0.19.1

**Comment by dopykuh** [comment]
A downgrade to 3.6.0 has temporary resolved the issue.

**Comment by dopykuh** [comment]
Looks like an invalid response object, possibly a grape exception?

**Comment by dopykuh** [comment]
Its a grape bug!
