### ISSUE TITLE
Puma isn't running correct bundler env

### ISSUE THREAD

**Issue by johnny-1111one1** [puma/puma#1232]
### Description
We currently use god to monitor things like unicorn and resque. I wanted to use Puma for the phased restart, but as soon as I trying to monitor it with God, it ignores the bundler context. I feel like I must be missing something simple.

### Steps to reproduce
**config/puma/qa.rb:**
```
environment 'qa'
directory '/home/ubuntu/current'
pidfile '/home/ubuntu/pids/puma.pid'
bind 'tcp://0.0.0.0:8080'
workers 2
threads 1, 1
daemonize true
prune_bundler
stdout_redirect '/home/ubuntu/shared/log/puma.stdout.log', '/home/ubuntu/shared/log/puma.stderr.log'
```

Deploying with capistrano 3, no rvm/rbenv. After deploy callbacks to load the correct version of Gemfile. Unicorn and our Resque processes start and restart as expected.

Since I have **RAILS_ENV** defined as **qa**, I can ssh into the api box, cd to current, and run `bundle exec puma`, which starts up without issues. However, I want it to be monitored like everything else.

So I created a god file, **config/god/puma.god:**
```
rails_env = ENV['RACK_ENV'] = ENV['RAILS_ENV'] || 'production'
rails_root = ENV['RAILS_ROOT'] || '/home/ubuntu/current'
pidfile = '/home/ubuntu/pids/puma.pid'

God.watch do |w|
  w.dir = rails_root
  w.pid_file = pidfile
  w.name = 'puma'
  w.interval = 30.seconds
  w.env = {"RAILS_ENV"=>rails_env, "BUNDLE_GEMFILE"=>"#{rails_root}/Gemfile"}
  w.start = "bundle exec puma -C config/puma/#{rails_env}.rb"
  w.stop = "kill -TERM `cat #{pidfile}`"
  w.restart = "kill -TERM `cat #{pidfile}`"

  # restart if memory gets too high
  w.transition(:up, :restart) do |on|
    on.condition(:memory_usage) do |c|
      c.above = 1500.megabytes
      c.times = 2
    end
  end

  # determine the state on startup
  w.transition(:init, { true => :up, false => :start }) do |on|
    on.condition(:process_running) do |c|
      c.running = true
    end
  end

  # determine when process has finished starting
  w.transition([:start, :restart], :up) do |on|
    on.condition(:process_running) do |c|
      c.running = true
      c.interval = 5.seconds
    end

    # failsafe
    on.condition(:tries) do |c|
      c.times = 5
      c.transition = :start
      c.interval = 5.seconds
    end
  end

  # start if process is not running
  w.transition(:up, :start) do |on|
    on.condition(:process_running) do |c|
      c.running = false
    end
  end
end
```
However, when I ask god to monitor this process, Puma outputs the same error in a loop --
**stdout:**
```
...
[9141] + Gemfile in context: /home/ubuntu/releases/20170303031725/Gemfile
...
```

**stderr:**
```
...
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/releases/20170303031725/config/boot.rb:6:in `<top (required)>'
	from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/releases/20170303031725/config/application.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/releases/20170303031725/config/environment.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from config.ru:1:in `block in <main>'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/builder.rb:40:in `eval'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/builder.rb:40:in `parse_file'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/configuration.rb:323:in `load_rackup'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/configuration.rb:250:in `app'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/runner.rb:148:in `app'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/runner.rb:155:in `start_server'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/cluster.rb:261:in `worker'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/cluster.rb:126:in `block (2 levels) in spawn_workers'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/cluster.rb:126:in `fork'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/cluster.rb:126:in `block in spawn_workers'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/cluster.rb:122:in `times'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/cluster.rb:122:in `spawn_workers'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/cluster.rb:200:in `check_workers'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/cluster.rb:465:in `run'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/launcher.rb:171:in `run'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/lib/puma/cli.rb:77:in `run'
	from /home/ubuntu/shared/bundle/ruby/2.0.0/gems/puma-3.7.1/bin/puma-wild:31:in `<main>'
...
```

### Some things I've tried
I haven't played with the configuration file much. Since it seems to work in one context, I assume it has something to do with a number of issues I've seen logged around how it references or loads the Gemfile.

I have tried various w.start commands without success:
`cd #{rails_root} && bundle exec puma -C config/puma/qa.rb`
`bundle exec puma -C config/puma/qa.rb`
`puma -C config/puma/qa.rb`
`puma`
`bundle exec puma` (setting RACK_ENV picks up correct environment)

### Expected behavior

Running puma within the context of bundle exec to be consistent.

### Actual behavior

Something in this configuration is changing the context in which puma executes.

### System configuration

**Ruby version**: 2.0.0p353
**Rails version**: 3.2.22.3
**Puma version**: 3.7.1
**God version**: 0.13.7

**Comment by nateberkopec** [comment]
I don't think this is a Puma issue. You'll have better luck getting an answer on StackOverflow. 

I can reopen if you can provide a full repro app, otherwise we're just debugging someone else's app in the dark.
