### ISSUE TITLE
ConcurrentRuby TimerTask fails to fire when running in app under Puma

### ISSUE THREAD

**Issue by xrl** [puma/puma#1256]
### Steps to reproduce

Run my a copy of the issue from my minimal reproduction, a sinatra app that spawns a task at boot and prints status of task after each `curl`.

```
git clone https://github.com/tureus/puma-timer-test.git
cd puma-timer-test
bundle install
bundle exec ruby app.rb -s puma

# note there is a spawn task but not stdout
# in another console
curl http://localhost:4567/hello
# note the inspected output, iterations is 0, so the task is not firing
```

### Expected behavior

The timer task should be firing and spamming the stdout of the sinatra app.

The expected behavior can be seen when evaluating the `app.rb` without the puma wrapper:

```
LP-XLANGE-OSX:timer-test xlange$ bundle exec irb
irb(main):001:0> require_relative 'app'
=> true
irb(main):002:0> hello from #<Concurrent::TimerTask:0x007ff6d5273ca0>
hello from #<Concurrent::TimerTask:0x007ff6d5273ca0>
hello from #<Concurrent::TimerTask:0x007ff6d5273ca0>
hello from #<Concurrent::TimerTask:0x007ff6d5273ca0>
```

### Actual behavior

The timer task is not firing/printing and the `iterations` counter is not going up.

### System configuration

**Ruby version**: `ruby-2.3.1`
**Sinatra version**: `1.4.8`
**ConcurrentRuby version**: `1.0.5`

**Comment by xrl** [comment]
I'm adding my `TimerTask` code to a full-up rails app, running with a slightly different puma config:

```
LP-XLANGE-OSX:contractresearchmap-beta xlange$ kc logs contractresearchmap-2510290728-3rv49
[1] Puma starting in cluster mode...
[1] * Version 3.7.0 (ruby 2.3.1-p112), codename: Snowy Sagebrush
[1] * Min threads: 8, max threads: 32
[1] * Environment: development
[1] * Process workers: 3
[1] * Preloading application
spawning timertask
execution_interval: 1, timeout_interval: 10
[1] * Listening on tcp://0.0.0.0:3000
[1] ! WARNING: Detected 2 Thread(s) started in app boot:
[1] ! #<Thread:0x0055986e46d7f8@/usr/local/bundle/bundler/gems/semantic_logger-8446da586d18/lib/semantic_logger/processor.rb:7 sleep> - /usr/local/bundle/bundler/gems/semantic_logger-8446da586d18/lib/semantic_logger/processor.rb:139:in `pop'
[1] ! #<Thread:0x0055986bcceda0@/usr/local/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:317 sleep> - /usr/local/bundle/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:43:in `sleep'
```

Interesting that puma caught the error on that app.

**Comment by xrl** [comment]
Definitely a me problem! I wasn't respawning the work in the background threads. The semantic_logger project included info on how to reopen the logger and that got me unblocked. Also had to write a `config.ru` for the sinatra app so I could get this level of config.
