### ISSUE TITLE
Errno::EPIPE Broken pipe when using wss

### ISSUE THREAD

**Issue by Machiaweliczny** [puma/puma#1271]
### Steps to reproduce

Try to write big payload through WSS using ActionCable 5.0.0.1 and Puma 3.7.1

### Expected behavior

The error should be handled gracefully.

### Actual behavior

This error is omitted by Puma 3.7.1 and ActionCable 5.0.0.1 doesn't handle it properly as well.

### System configuration

**Ruby version**: 2.3.3
**Rails version**: 5.0.0.1

### Stacktrace

```
[
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.7.1/lib/puma/minissl.rb:65:in `write'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.7.1/lib/puma/minissl.rb:65:in `write'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/connection/stream.rb:30:in `write'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/connection/client_socket.rb:73:in `write'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:228:in `send_frame'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:191:in `frame'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:111:in `text'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/connection/client_socket.rb:83:in `transmit'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/connection/web_socket.rb:20:in `transmit'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/connection/base.rb:96:in `transmit'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/channel/base.rb:201:in `block in transmit'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/channel/base.rb:200:in `transmit'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/channel/streams.rb:165:in `block in stream_transmitter'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/server/worker.rb:58:in `block in invoke'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/server/worker.rb:39:in `block in work'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/server/worker/active_record_connection_management.rb:14:in `block in with_database_connections'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `tag'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/server/worker/active_record_connection_management.rb:14:in `with_database_connections'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/engine.rb:60:in `block (4 levels) in <class:Engine>'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:76:in `wrap'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/engine.rb:55:in `block (3 levels) in <class:Engine>'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_work_callbacks'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/server/worker.rb:38:in `work'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/server/worker.rb:56:in `invoke'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.1/lib/action_cable/server/worker.rb:51:in `block in async_invoke'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'",
  "~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'"
]
```

This is how ActionCable client handles it on frontend:
```
[ActionCable] Opening WebSocket, current state is null, subprotocols: actioncable-v1-json,actioncable-unsupported 1491926513682
action_cable.js:50 [ActionCable] ConnectionMonitor started. pollInterval = 3000 ms 1491926513694
action_cable.js:50 [ActionCable] WebSocket onopen event, using 'actioncable-v1-json' subprotocol 1491926514045
action_cable.js:50 [ActionCable] ConnectionMonitor recorded connect 1491926514480
action_cable.js:50 [ActionCable] WebSocket onclose event 1491926541823
action_cable.js:50 [ActionCable] ConnectionMonitor recorded disconnect 1491926541824
action_cable.js:50 [ActionCable] ConnectionMonitor detected stale connection. reconnectAttempts = 0, pollInterval = 3000 ms, time disconnected = 7.689 s, stale threshold = 6 s 1491926549513
action_cable.js:50 [ActionCable] ConnectionMonitor reopening 1491926549514
```

It's detecting disconnect and reconnects but I lost message I wanted to send.
I would love to know the reason why I'm getting this `Errno::EPIPE Broken pipe` in first place.

If this cannot be fixed then I think that this code https://github.com/rails/rails/blob/v5.0.0.1/actioncable/lib/action_cable/connection/client_socket.rb#L74 should rise error which is propagated back to my Sidekiq job which was streaming this message so it can be retransmitted after connection is back again.

-----

Not sure I should post it here or in Rails. I'm not sure what closes this connection exactly.

**Comment by nateberkopec** [comment]
Does anything in #1189 help you out? Also, try latest master.

**Comment by nateberkopec** [comment]
Please try with 3.9.1 and reopen if not fixed, thanks!

**Comment by tokhi** [comment]
I still have this problem with puma and resque, I tried `3.9.1`, 3.10.0` and also `3.11`
