### ISSUE TITLE
puma fails to install on CentOS 7

### ISSUE THREAD

**Issue by senorcinco** [puma/puma#1281]
### Steps to reproduce
```
# gem install puma -- --with-cppflags=-I/usr/include/openssl --with-ldflags=-L/usr/lib64
Building native extensions with: '--with-cppflags=-I/usr/include/openssl --with-ldflags=-L/usr/lib64'
This could take a while...
ERROR:  Error installing puma:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb --with-cppflags=-I/usr/include/openssl --with-ldflags=-L/usr/lib64
checking for BIO_read() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby
	--with-puma_http11-dir
	--without-puma_http11-dir
	--with-puma_http11-include
	--without-puma_http11-include=${puma_http11-dir}/include
	--with-puma_http11-lib
	--without-puma_http11-lib=${puma_http11-dir}/
	--with-openssl-dir
	--without-openssl-dir
	--with-openssl-include
	--without-openssl-include=${openssl-dir}/include
	--with-openssl-lib
	--without-openssl-lib=${openssl-dir}/
	--with-cryptolib
	--without-cryptolib
/usr/share/ruby/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/share/ruby/mkmf.rb:519:in `try_link0'
	from /usr/share/ruby/mkmf.rb:534:in `try_link'
	from /usr/share/ruby/mkmf.rb:714:in `try_func'
	from /usr/share/ruby/mkmf.rb:944:in `block in have_library'
	from /usr/share/ruby/mkmf.rb:889:in `block in checking_for'
	from /usr/share/ruby/mkmf.rb:340:in `block (2 levels) in postpone'
	from /usr/share/ruby/mkmf.rb:310:in `open'
	from /usr/share/ruby/mkmf.rb:340:in `block in postpone'
	from /usr/share/ruby/mkmf.rb:310:in `open'
	from /usr/share/ruby/mkmf.rb:336:in `postpone'
	from /usr/share/ruby/mkmf.rb:888:in `checking_for'
	from /usr/share/ruby/mkmf.rb:939:in `have_library'
	from extconf.rb:8:in `block in <main>'
	from extconf.rb:8:in `each'
	from extconf.rb:8:in `find'
	from extconf.rb:8:in `<main>'


Gem files will remain installed in /usr/local/share/gems/gems/puma-3.8.2 for inspection.
Results logged to /usr/local/share/gems/gems/puma-3.8.2/ext/puma_http11/gem_make.out
```

### Expected behavior

The puma gem is installed.

### Actual behavior

extconf.rb failed

### System configuration

```
# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core) 

# uname -a
Linux asaapdev99 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

# rpm -qa | grep openssl
openssl-devel-1.0.1e-60.el7_3.1.x86_64
openssl-1.0.1e-60.el7_3.1.x86_64
openssl-libs-1.0.1e-60.el7_3.1.x86_64

# rpm -qa | grep ruby
ruby-irb-2.0.0.648-29.el7.noarch
rubygem-bigdecimal-1.2.0-29.el7.x86_64
rubygem-io-console-0.4.2-29.el7.x86_64
rubygems-2.0.14.1-29.el7.noarch
ruby-devel-2.0.0.648-29.el7.x86_64
ruby-libs-2.0.0.648-29.el7.x86_64
rubygem-psych-2.0.0-29.el7.x86_64
rubygem-json-1.7.7-29.el7.x86_64
rubygem-rdoc-4.0.0-29.el7.noarch
ruby-2.0.0.648-29.el7.x86_64
```

**Comment by senorcinco** [comment]
I've also tried several iterations of:
```
--with-openssl-include=/usr/include/openssl
--with-openssl-lib=/usr/lib64
--without-cryptolib
```
They all result in the same basic error:
```
checking for BIO_read() in -lcrypto... *** extconf.rb failed ***
```

**Comment by nateberkopec** [comment]
Do you have `libssl-dev` installed?

**Comment by nateberkopec** [comment]
Pardon, I think on CentOS it's `openssl-devel`

**Comment by crigor** [comment]
I'm able to reproduce the issue ie "You have to install development tools first." on centos 7 (using docker image centos:7). I only installed ruby and ruby-devel at this point.

After installing a few more packages, I was able to install puma.

```
yum install make automake gcc gcc-c++ kernel-devel
```

This is roughly the equivalent of build-essential on Debian/Ubuntu. https://unix.stackexchange.com/questions/1338/what-is-the-fedora-equivalent-of-the-debian-build-essential-package

```
[root@1356186a625a /]# gem install puma
Building native extensions.  This could take a while...
Successfully installed puma-3.9.1
Parsing documentation for puma-3.9.1
Installing ri documentation for puma-3.9.1
1 gem installed
[root@1356186a625a /]# gem install puma -- --with-cppflags=-I/usr/include/openssl --with-ldflags=-L/usr/lib64
Building native extensions with: '--with-cppflags=-I/usr/include/openssl --with-ldflags=-L/usr/lib64'
This could take a while...
Successfully installed puma-3.9.1
Parsing documentation for puma-3.9.1
1 gem installed
```
