### ISSUE TITLE
Puma fails to boot: DH_set0_pqg: symbol not found

### ISSUE THREAD

**Issue by warmwaffles** [puma/puma#1301]
### Steps to reproduce

1) Clone https://github.com/simplecasual/ruby.fm

2) `docker-compose build`

3) `docker-compose up`

### Expected behavior

Rails server boots

### Actual behavior

```
web_1 | => Booting Puma
web_1 | => Rails 5.1.1 application starting in development on http://0.0.0.0:3000
web_1 | => Run `rails server -h` for more startup options
web_1 | Exiting
web_1 | /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require': Error relocating /usr/lib/ruby/gems/2.4.0/gems/puma-3.8.2/lib/puma/puma_http11.so: DH_set0_pqg: symbol not found - /usr/lib/ruby/gems/2.4.0/gems/puma-3.8.2/lib/puma/puma_http11.so (LoadError)
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/puma-3.8.2/lib/puma/server.rb:15:in `<top (required)>'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/puma-3.8.2/lib/puma/runner.rb:1:in `<top (required)>'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/puma-3.8.2/lib/puma/cluster.rb:1:in `<top (required)>'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/puma-3.8.2/lib/puma/launcher.rb:4:in `<top (required)>'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/puma-3.8.2/lib/rack/handler/puma.rb:14:in `config'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/puma-3.8.2/lib/rack/handler/puma.rb:56:in `run'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:297:in `start'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:44:in `start'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:131:in `block in perform'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `tap'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `perform'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
web_1 |   from /usr/lib/ruby/gems/2.4.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
web_1 |   from bin/rails:4:in `require'
web_1 |   from bin/rails:4:in `<main>'
```

Base docker image: https://github.com/simplecasual/ruby-docker/blob/master/Dockerfile
Application docker: https://github.com/simplecasual/ruby.fm/blob/master/Dockerfile

I can not use openssl packages because postgres 9.6 depends on libressl.

```
ERROR: unsatisfiable constraints:
  libressl-dev-2.5.4-r0:
    conflicts:
               openssl-dev-1.0.2k-r0[pc:libcrypto=2.5.4]
               openssl-dev-1.0.2k-r0[pc:libssl=2.5.4]
               openssl-dev-1.0.2k-r0[pc:openssl=2.5.4]
    satisfies: world[libressl-dev]
               postgresql-dev-9.6.2-r4[libressl-dev]
  openssl-dev-1.0.2k-r0:
    conflicts:
               libressl-dev-2.5.4-r0[pc:libcrypto=1.0.2k]
               libressl-dev-2.5.4-r0[pc:libssl=1.0.2k]
               libressl-dev-2.5.4-r0[pc:openssl=1.0.2k]
    satisfies: world[openssl-dev]
```

### System configuration

**Alpine Version**: apline:3.6
**Ruby version**: 2.4.1
**Rails version**: 5.1.1

**Comment by romdim** [comment]
I've solved it for now by requiring puma 3.6.2 as suggested here: https://github.com/reevoo/jenkins_statistics/commit/de1f9bbc86b46afb346e03358ad33b56119806ba
and while waiting for this: https://github.com/puma/puma/pull/1285 to be pushed

**Comment by warmwaffles** [comment]
That certainly fixed it @romdim. Downgraded for now.

**Comment by nateberkopec** [comment]
LibreSSL fix has been pushed 👍

**Comment by warmwaffles** [comment]
@nateberkopec which release was it fixed under? 3.9.0?

**Comment by nateberkopec** [comment]
Yup!

**Comment by warmwaffles** [comment]
Can confirm that it indeed works. Thanks guys!
