### ISSUE TITLE
Puma tries to start several times

### ISSUE THREAD

**Issue by Nikita2k** [puma/puma#1354]
### Steps to reproduce
I have 2 apps under
```
/home/deploy/apps/app1/current
/home/deploy/apps/app1/current
```

My **/etc/init/puma.conf**
```
description "Puma Background Worker"

stop on (stopping puma-manager or runlevel [06])

setuid deploy
setgid deploy

respawn
respawn limit 3 30

instance ${app}

script
env RACK_ENV="production"

exec /bin/bash <<'EOT'
  export HOME="$(eval echo ~$(id -un))"

  if [ -d "/usr/local/rbenv/bin" ]; then
    export PATH="/usr/local/rbenv/bin:/usr/local/rbenv/shims:$PATH"
  elif [ -d "$HOME/.rbenv/bin" ]; then
    export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
  elif [ -f  /etc/profile.d/rvm.sh ]; then
    source /etc/profile.d/rvm.sh
  elif [ -f /usr/local/rvm/scripts/rvm ]; then
    source /etc/profile.d/rvm.sh
  elif [ -f "$HOME/.rvm/scripts/rvm" ]; then
    source "$HOME/.rvm/scripts/rvm"
  elif [ -f /usr/local/share/chruby/chruby.sh ]; then
    source /usr/local/share/chruby/chruby.sh
    if [ -f /usr/local/share/chruby/auto.sh ]; then
      source /usr/local/share/chruby/auto.sh
    fi
  fi

  cd $app
  logger -t puma "Starting server: $app"

  echo "App path $app" 
  cd ..
  configPath="$PWD/shared/puma.rb"
  cd current
  exec bundle exec puma -C $configPath --daemon
EOT
end script
```

**/home/deploy/apps/app1/shared/puma.rb** (from Capistrano)
```
#!/usr/bin/env puma

directory '/home/deploy/apps/app1/current'
rackup "/home/deploy/apps/app1/current/config.ru"
environment 'production'

pidfile "/home/deploy/apps/app1/shared/tmp/pids/puma.pid"
state_path "/home/deploy/apps/app1/shared/tmp/pids/puma.state"
stdout_redirect '/home/deploy/apps/app1/current/log/puma.error.log', '/home/deploy/apps/app1/current/log/puma.access.log', true


threads 4,16

bind 'unix:///home/deploy/apps/app1/shared/tmp/sockets/app1-puma.sock'

workers 0

preload_app!

on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = "/home/deploy/apps/app1/current/Gemfile"
end


on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```

Doing server restart:
```
sudo shutdown -r now
```

### Expected behavior

Server reboots normally and puma starts both instances

### Actual behavior

Server reboots normally and puma starts both instances **with delay**

**/home/deploy/apps/app1/current/log/puma.access.log**
```
=== puma startup: 2017-06-29 18:23:08 +0000 ===
=== puma startup: 2017-06-29 18:23:11 +0000 ===
=== puma startup: 2017-06-29 18:23:16 +0000 ===
=== puma startup: 2017-06-29 18:23:23 +0000 ===
RuntimeError: There is already a server bound to: /home/deploy/apps/app1/shared/tmp/sockets/app1-puma.sock
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:362:in `add_unix_listener'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:141:in `block in parse'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:88:in `each'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:88:in `parse'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/runner.rb:144:in `load_and_bind'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/single.rb:87:in `run'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/bin/puma:23:in `load'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/bin/puma:23:in `<top (required)>'
RuntimeError: There is already a server bound to: /home/deploy/apps/app1/shared/tmp/sockets/app1-puma.sock
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:362:in `add_unix_listener'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:141:in `block in parse'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:88:in `each'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:88:in `parse'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/runner.rb:144:in `load_and_bind'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/single.rb:87:in `run'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/bin/puma:23:in `load'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/bin/puma:23:in `<top (required)>'
RuntimeError: There is already a server bound to: /home/deploy/apps/app1/shared/tmp/sockets/app1-puma.sock
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:362:in `add_unix_listener'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:141:in `block in parse'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:88:in `each'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/binder.rb:88:in `parse'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/runner.rb:144:in `load_and_bind'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/single.rb:87:in `run'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/bin/puma:23:in `load'
  /home/deploy/apps/app1/shared/bundle/ruby/2.3.0/bin/puma:23:in `<top (required)>'
```

**/home/deploy/apps/app1/current/log/puma.error.log**
```
=== puma startup: 2017-06-29 18:23:08 +0000 ===
=== puma startup: 2017-06-29 18:23:11 +0000 ===
=== puma startup: 2017-06-29 18:23:16 +0000 ===
=== puma startup: 2017-06-29 18:23:23 +0000 ===
* Listening on unix:///home/deploy/apps/app1/shared/tmp/sockets/app1-puma.sock
* Listening on unix:///home/deploy/apps/app1/shared/tmp/sockets/app1-puma.sock
bundler: failed to load command: puma (/home/deploy/apps/app1/shared/bundle/ruby/2.3.0/bin/puma)
* Listening on unix:///home/deploy/apps/app1/shared/tmp/sockets/app1-puma.sock
bundler: failed to load command: puma (/home/deploy/apps/app1/shared/bundle/ruby/2.3.0/bin/puma)
* Listening on unix:///home/deploy/apps/app1/shared/tmp/sockets/app1-puma.sock
bundler: failed to load command: puma (/home/deploy/apps/app1/shared/bundle/ruby/2.3.0/bin/puma)
```
### System configuration

Ubuntu 16.04
**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by stereobooster** [comment]
Not sure what you trying to achieve. You want to bind two puma servers to one socket in manner of [`unicorn :reuseport => true`](https://bogomips.org/unicorn/Unicorn/Configurator.html)?

**Comment by nateberkopec** [comment]
Yeah, the error message is pretty self explanatory. You're binding to the same socket 4 times. You can't do that.

**Comment by Nikita2k** [comment]
Thank you both for a quick answer. 

I'm trying to have two sockets and that is what I achieve with that config:
```
deploy    2370  0.0 23.1 771736 115672 ?       Sl   Jun29   0:11 puma 3.8.2 (unix:///home/deploy/apps/app1/shared/tmp/sockets/app1-puma.sock) [20170629172103]
deploy    2390  0.0 16.1 764560 80672 ?        Sl   Jun29   0:09 puma 3.7.1 (unix:///home/deploy/apps/app2/shared/tmp/sockets/app2-puma.sock) [20170629172111]
```

Just not sure why puma tries to start each instance 4 times =/

**Comment by stereobooster** [comment]
Well try puma standalone 

```
bundle exec puma -C $configPath --daemon
```

if it will run only once it means that the problem (most likely) is not in the puma, but in the shell script.
