### ISSUE TITLE
Issues getting puma to bind to unspecified ipv6 address through rackup

### ISSUE THREAD

**Issue by agargiulo** [puma/puma#1356]
### Steps to reproduce

1) write simple rack app in `config.ru`

``` ruby
# config.ru
run(proc { |_env| ['200', { 'Content-Type' => 'text/plain' }, ['A barebones rack app']] })
```

2) run `rackup -p 1234 -o ::`
```
Puma starting in single mode...
* Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller
* Min threads: 0, max threads: 16
* Environment: development
/opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): tcp://:::1234 (URI::InvalidURIError)
        from /opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
        from /opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
        from /opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/binder.rb:89:in `block in parse'
        from /opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/binder.rb:88:in `each'
        from /opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/binder.rb:88:in `parse'
        from /opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/runner.rb:144:in `load_and_bind'
        from /opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/single.rb:87:in `run'
        from /opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
        from /opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/rack/handler/puma.rb:69:in `run'
        from /opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:297:in `start'
        from /opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:148:in `start'
        from /opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/bin/rackup:4:in `<top (required)>'
        from /opt/rbenv/versions/2.4.1/bin/rackup:22:in `load'
        from /opt/rbenv/versions/2.4.1/bin/rackup:22:in `<main>'
```

3) I've tested the same thing but adding `-s thin` and it starts up just fine
```
[5:42:30] % rackup -p 1234 -o :: -s thin
Thin web server (v1.7.1 codename Muffin Mode)
Maximum connections set to 1024
Listening on :::1234, CTRL+C to stop
````

### Expected behavior

Expected puma to start up and be bound to `::` on port 1234

### Actual behavior

a error was raised about a bad URI

### System configuration

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
**Rails version**: N/A
**Rack version**: Rack 1.3 (Release: 2.0.3)

**Comment by agargiulo** [comment]
Same issue shows up in Ruby 2.3.4 p301

**Comment by nateberkopec** [comment]
Puma expects its binds to adhere to RFC 3986. According to that, you have to put ipv6 literals inside square brackets:

```
rackup -p 1234 -o [::]
```

**Comment by agargiulo** [comment]
Oh awesome, I thought I tried everything but I forgot `[::]` 
Thanks!

**Comment by schneems** [comment]
As a heads up: Puma only works with `[::]` while webrick only works with `::`

```
$ bundle exec rackup --host "[::]"
[2024-11-24 20:14:10] INFO  WEBrick 1.7.0
[2024-11-24 20:14:10] INFO  ruby 3.3.1 (2024-04-23) [arm64-darwin23]
bundler: failed to load command: rackup (/Users/rschneeman/.gem/ruby/3.3.1/bin/rackup)
/Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/3.3.0/socket.rb:231:in `getaddrinfo': getaddrinfo: nodename nor servname provided, or not known (Socket::ResolutionError)
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/3.3.0/socket.rb:231:in `foreach'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/3.3.0/socket.rb:768:in `tcp_server_sockets'
	from /Users/rschneeman/.gem/ruby/3.3.1/gems/webrick-1.7.0/lib/webrick/utils.rb:60:in `create_listeners'
	from /Users/rschneeman/.gem/ruby/3.3.1/gems/webrick-1.7.0/lib/webrick/server.rb:130:in `listen'
	from /Users/rschneeman/.gem/ruby/3.3.1/gems/webrick-1.7.0/lib/webrick/server.rb:111:in `initialize'
	from /Users/rschneeman/.gem/ruby/3.3.1/gems/webrick-1.7.0/lib/webrick/httpserver.rb:47:in `initialize'
	from /Users/rschneeman/.gem/ruby/3.3.1/gems/rack-2.2.3/lib/rack/handler/webrick.rb:38:in `new'
	from /Users/rschneeman/.gem/ruby/3.3.1/gems/rack-2.2.3/lib/rack/handler/webrick.rb:38:in `run'
	from /Users/rschneeman/.gem/ruby/3.3.1/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
	from /Users/rschneeman/.gem/ruby/3.3.1/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
	from /Users/rschneeman/.gem/ruby/3.3.1/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
	from /Users/rschneeman/.gem/ruby/3.3.1/bin/rackup:25:in `load'
	from /Users/rschneeman/.gem/ruby/3.3.1/bin/rackup:25:in `<top (required)>'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:456:in `exec'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:29:in `start'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.23/exe/bundle:28:in `block in <top (required)>'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/site_ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.5.23/exe/bundle:20:in `<top (required)>'
	from /Users/rschneeman/.gem/ruby/3.3.1/bin/bundle:25:in `load'
	from /Users/rschneeman/.gem/ruby/3.3.1/bin/bundle:25:in `<main>'
⛄️ 3.3.1 🚀 /Users/rschneeman/Documents/projects/work/buildpacks-ruby/buildpacks/ruby/tests/fixtures/default_ruby (schneems/ipv6-host-default)
$ bundle exec rackup --host "::"
[2024-11-24 20:14:15] INFO  WEBrick 1.7.0
[2024-11-24 20:14:15] INFO  ruby 3.3.1 (2024-04-23) [arm64-darwin23]
[2024-11-24 20:14:15] INFO  WEBrick::HTTPServer#start: pid=13236 port=9292
::1 - - [24/Nov/2024:20:14:27 -0600] "GET / HTTP/1.1" 200 143 0.0015
```
