### ISSUE TITLE
LoadError: cannot load such file -- puma/state_file 

### ISSUE THREAD

**Issue by ramakuka** [puma/puma#1361]
Puma 3.9.1 Ruby 2.4.1p111  Rails 4.2.8
Trying to start Puma and I keep getting 
```
bundler: failed to load command: pumactl (/app/vendor/bundle/ruby/2.4.0/bin/pumactl)
LoadError: cannot load such file -- puma/state_file
  /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
  /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/launcher.rb:108:in `write_state'
  /app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:439:in `run'
  /app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
  /app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/cli.rb:77:in `run'
  /app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/control_cli.rb:259:in `start'
  /app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/control_cli.rb:223:in `run'
  /app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/bin/pumactl:8:in `<top (required)>'
  /app/vendor/bundle/ruby/2.4.0/bin/pumactl:22:in `load'
  /app/vendor/bundle/ruby/2.4.0/bin/pumactl:22:in `<top (required)>'
```
it looks like an issue with `require 'puma/state_file'` for some reason it cannot be found.
I can see that in [PR 1083](https://github.com/puma/puma/commit/ea22ade35270eaefdfaf53b2f86a2eb6259c60a3) @frodsan moved the require to the `write_state` method for better memory allocation.
I was able to start Puma when I tried to move the `require 'puma/state_file'` to where it was originally (outside the method scope).
Can anyone shade light on what might be the issue with the require? any ideas on what we can do to fix it?

**Comment by msuzoagu** [comment]
@nafaabout I am currently running into this issue:  

```
/usr/local/bundle/gems/puma-4.0.1/lib/puma/launcher.rb:111:in `require': cannot load such file -- puma/state_file (LoadError)
	from /usr/local/bundle/gems/puma-4.0.1/lib/puma/launcher.rb:111:in `write_state'
	from /usr/local/bundle/gems/puma-4.0.1/lib/puma/single.rb:103:in `run'
	from /usr/local/bundle/gems/puma-4.0.1/lib/puma/launcher.rb:186:in `run'
	from /usr/local/bundle/gems/puma-4.0.1/lib/puma/cli.rb:80:in `run'
	from /usr/local/bundle/gems/puma-4.0.1/bin/puma:10:in `<top (required)>'
	from /usr/local/bundle/bin/puma:23:in `load'
	from /usr/local/bundle/bin/puma:23:in `<main>'
```

was the bug resolved? Any tips on how to debug it?
