### ISSUE TITLE
pumactl phased_restart failed with Command error: Content-Length: 43

### ISSUE THREAD

**Issue by CptBreeza** [puma/puma#1366]
### Problem description

I deployed my app with mina.Here is my puma.rb

```
environment ENV['RAILS_ENV'] || 'production'

daemonize true

pidfile "/var/www/myapp/shared/tmp/pids/puma.pid"
stdout_redirect "/var/www/myapp/shared/log/puma.stdout.log", "/var/www/myapp/shared/log/puma.stderr.log"
bind "unix:///var/www/myapp/shared/tmp/sockets/puma.sock"
state_path "/var/www/myapp/shared/tmp/sockets/puma.state"
activate_control_app "unix:///var/www/myapp/shared/tmp/sockets/pumactl.sock", { no_token: true }

threads 0, 16
```

1) I tried to restart puma with `bundle exec pumactl -F /var/www/myapp/shared/config/puma.rb phased-restart`

2) An error occured
```
      Command error: Content-Length: 43
       /var/www/myapp/releases/2/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/control_cli.rb:166:in `send_request'
       /var/www/myapp/releases/2/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/control_cli.rb:230:in `run'
       /var/www/myapp/releases/2/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/bin/pumactl:8:in `<top (required)>'
       /var/www/myapp/releases/2/vendor/bundle/ruby/2.4.0/bin/pumactl:22:in `load'
       /var/www/myapp/releases/2/vendor/bundle/ruby/2.4.0/bin/pumactl:22:in `<top (required)>'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
       /home/rails/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
       /home/rails/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
       /home/rails/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
       /home/rails/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
       /home/rails/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

3) But puma still restarted successfully.Although the error interrupted the deploying process.

### System configuration

**System version**: Ubuntu 16.04 LTS
**Ruby version**: 2.4.1
**Rails version**: 5.1.0

**Comment by cbasic7** [comment]
@nateberkopec Is there any way to solve the problem temporarily?I have no idea how this error occured.

**Comment by CptBreeza** [comment]
Sorry. No progress.

**Comment by nateberkopec** [comment]
ControlCLI has gotten a lot of love since this issue was open. If you can reproduce on latest Puma, please create a new issue.
