### ISSUE TITLE
Puma workers won't shut down gracefully

### ISSUE THREAD

**Issue by prvithani** [puma/puma#1382]
### Steps to reproduce

1) Run puma as daemon

2) execute  
``` sh
~/.rvm/bin/rvm default do bundle exec pumactl -S /var/www/fbdash/shared/tmp/pids/puma.state -F /var/www/fbdash/shared/puma.rb restart
```
3) In logs, I see following lines
``` text
[24498] PumaWorkerKiller: Consuming 3081.06640625 mb with master and 4 workers.
[24498] PumaWorkerKiller: Consuming 3081.06640625 mb with master and 4 workers.
[24498] PumaWorkerKiller: Consuming 3081.06640625 mb with master and 4 workers.
[24498] PumaWorkerKiller: Consuming 3081.06640625 mb with master and 4 workers.
[24498] PumaWorkerKiller: Consuming 3081.06640625 mb with master and 4 workers.
[24498] - Gracefully shutting down workers...
[24498] PumaWorkerKiller: Consuming 1250.91796875 mb with master and 4 workers.
[24498] PumaWorkerKiller: Consuming 1250.91796875 mb with master and 4 workers.
[24498] PumaWorkerKiller: Consuming 1250.91796875 mb with master and 4 workers.
[24498] PumaWorkerKiller: Consuming 1250.91796875 mb with master and 4 workers.
[24498] PumaWorkerKiller: Consuming 1250.91796875 mb with master and 4 workers.
[24498] PumaWorkerKiller: Consuming 1250.91796875 mb with master and 4 workers.
```

### Expected behavior
``` text
[3137] PumaWorkerKiller: Consuming 3537.03515625 mb with master and 4 workers.
[3137] PumaWorkerKiller: Consuming 3537.03515625 mb with master and 4 workers.
[3137] PumaWorkerKiller: Consuming 3537.03515625 mb with master and 4 workers.
[3137] PumaWorkerKiller: Consuming 3537.03515625 mb with master and 4 workers.
[3137] - Gracefully shutting down workers...
[3137] * Restarting...
Refreshing Gemfile
[3137] Puma starting in cluster mode...
[3137] * Version 3.8.2 (ruby 2.3.3-p222), codename: Sassy Salamander
[3137] * Min threads: 0, max threads: 16
[3137] * Environment: production
[3137] * Process workers: 4
[3137] * Preloading application
I, [2017-07-28T08:01:34.520097 #3137]  INFO -- sentry: ** [Raven] Raven 2.4.0 ready to catch errors
[3137] * Inherited unix:///var/www/fbdash/shared/tmp/sockets/puma.sock
[3137] ! WARNING: Detected 18 Thread(s) started in app boot:
[3137] ! #<Thread:0x00000004f673f0@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:300 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:302:in `sleep'
[3137] ! #<Thread:0x000000034fb778@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:121 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:123:in `sleep'
[3137] ! #<Thread:0x000000034fa468@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:121 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:123:in `sleep'
[3137] ! #<Thread:0x00000009c17128@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:121 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:123:in `sleep'
[3137] ! #<Thread:0x0000000a15df10@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:121 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:123:in `sleep'
[3137] ! #<Thread:0x0000000a15dc40@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:165 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:167:in `sleep'
[3137] ! #<Thread:0x0000000a26d9f0@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:121 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:123:in `sleep'
[3137] ! #<Thread:0x0000000a26d770@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:165 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:167:in `sleep'
[3137] ! #<Thread:0x0000000a385a18@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:121 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:123:in `sleep'
[3137] ! #<Thread:0x0000000a385798@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:165 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:167:in `sleep'
[3137] ! #<Thread:0x0000000a59d058@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:121 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:123:in `sleep'
[3137] ! #<Thread:0x0000000a59cdd8@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:165 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:167:in `sleep'
[3137] ! #<Thread:0x0000000a7b5890@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:121 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:123:in `sleep'
[3137] ! #<Thread:0x0000000a7b5610@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:165 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:167:in `sleep'
[3137] ! #<Thread:0x0000000a9cdb00@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:121 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:123:in `sleep'
[3137] ! #<Thread:0x0000000a9cd880@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:165 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:167:in `sleep'
[3137] ! #<Thread:0x0000000abe53c0@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:121 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/monitor.rb:123:in `sleep'
[3137] ! #<Thread:0x0000000abe5140@/var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:165 sleep> - /var/www/fbdash/shared/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/cluster/cursor_reaper.rb:167:in `sleep'
[3137] * Daemonizing...
=== puma startup: 2017-07-28 08:01:40 +0000 ===
[7004] - Worker 0 (pid: 7009) booted, phase: 0
[7004] - Worker 1 (pid: 7036) booted, phase: 0
[7004] - Worker 2 (pid: 7074) booted, phase: 0
[7004] - Worker 3 (pid: 7104) booted, phase: 0
[7004] PumaWorkerKiller: Consuming 1617.17578125 mb with master and 4 workers.
[7004] PumaWorkerKiller: Consuming 1635.4765625 mb with master and 4 workers.
[7004] PumaWorkerKiller: Consuming 1684.82421875 mb with master and 4 workers.

```
### Actual behavior

Workers not shutting down gracefully, hence the main Puma process won't stop (Apparently the whole execution hangs, and workers continue listening to old PID). But, it sends success in capistrano logs (Look at **point 3** in **Steps to Reproduce**)

### System configuration

**Ruby version**: 2.3.3
**Rails version**: 5.0.1
**puma.rb**: 4 workers, 16 threads
``` ruby
 #!/usr/bin/env puma

 directory '/var/www/fbdash/current'
 rackup "/var/www/fbdash/current/config.ru"
 environment 'production'

 pidfile "/var/www/fbdash/shared/tmp/pids/puma.pid"
 state_path "/var/www/fbdash/shared/tmp/pids/puma.state"
 stdout_redirect '/var/www/fbdash/shared/log/puma_access.log', '/var/www/fbdash/shared/log/puma_error.log', true

 threads 0,16
 bind 'unix:///var/www/fbdash/shared/tmp/sockets/puma.sock'
 workers 2

 preload_app!

 on_restart do
   puts 'Refreshing Gemfile'
   ENV["BUNDLE_GEMFILE"] = "/var/www/fbdash/current/Gemfile"
 end

 on_worker_boot do
   ActiveSupport.on_load(:active_record) do
     ActiveRecord::Base.establish_connection
   end
 end

  before_fork do
    PumaWorkerKiller.config do |config|
     config.ram           = 8192 # mb # Production is 4096 * 2
     config.frequency     = 50    # seconds
     config.percent_usage = 0.75
     config.rolling_restart_frequency = 12 * 3600 # 12 hours in seconds
   end
   PumaWorkerKiller.start
  end
```
**CPU**: 2 cores, 7.5 GB Ram

**Comment by prashantvithani** [comment]
@schneems: Could this be related to `puma_worker_killer`?

**Comment by schneems** [comment]
If you remove PWK does the problem go away?

**Comment by prashantvithani** [comment]
Tried that as well, the problem is still there

**Comment by nateberkopec** [comment]
Can you try 3.10?

**Comment by oklaiss-gpsw** [comment]
We're seeing the same issue with Puma 3.6.0 with and without Puma Worker Killer 0.1.0

**Comment by BlackNightFury** [comment]
Gracefully shutting down workers...

Puma server is not shutting down. And it is stucking with this message.

Puma version is 3.11.3 and ruby version is 2.2.6

This is kinda urgent problem! So please help me out, then it will be appreciated.

Thanks

**Comment by ashu210890** [comment]
This is still happening with Puma version 3.11.0 and Ruby version 2.4.2p198.
