### ISSUE TITLE
undefined method closed?

### ISSUE THREAD

**Issue by vincentwoo** [puma/puma#1510]
just saw this in my dev logs, using SSL:

```
14:34:06 web.1     | Error reached top of thread-pool: EOFError (EOFError)
14:34:06 web.1     | Error in reactor loop escaped: undefined method `closed?' for #<Puma::MiniSSL::Socket:0x00007fb06edf4a28>
14:34:06 web.1     | Did you mean?  close (NoMethodError)
14:34:06 web.1     | (eval):2:in `closed?'
14:34:06 web.1     | /Users/vwoo/.gem/ruby/2.5.0/gems/puma-3.11.2/lib/puma/reactor.rb:32:in `block in run_internal'
14:34:06 web.1     | /Users/vwoo/.gem/ruby/2.5.0/gems/puma-3.11.2/lib/puma/reactor.rb:32:in `any?'
14:34:06 web.1     | /Users/vwoo/.gem/ruby/2.5.0/gems/puma-3.11.2/lib/puma/reactor.rb:32:in `rescue in run_internal'
14:34:06 web.1     | /Users/vwoo/.gem/ruby/2.5.0/gems/puma-3.11.2/lib/puma/reactor.rb:28:in `run_internal'
14:34:06 web.1     | /Users/vwoo/.gem/ruby/2.5.0/gems/puma-3.11.2/lib/puma/reactor.rb:154:in `block in run_in_thread'
```

**Comment by dayudodo** [comment]
a little different:
Error reached top of thread-pool: EOFError (EOFError)
2018-02-06 14:23:51 +0800: SSL error, peer: 127.0.0.1, peer cert: , #<Puma::MiniSSL::SSLError: System error: Undefined error: 0 - 0>

**Comment by mirelon** [comment]
I have the same issue:

```
2018-02-13 11:36:05 +0100: SSL error, peer: <ip>, peer cert: , #<Puma::MiniSSL::SSLError: OpenSSL error: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request - 336027804>
Error in reactor loop escaped: undefined method `closed?' for #<Puma::MiniSSL::Socket:0x007f969584f2c8> (NoMethodError)
(eval):2:in `closed?'
<path>/vendor/bundle/ruby/2.3.0/gems/puma-3.7.0/lib/puma/reactor.rb:31:in `block in run_internal'
<path>/vendor/bundle/ruby/2.3.0/gems/puma-3.7.0/lib/puma/reactor.rb:31:in `any?'
<path>/vendor/bundle/ruby/2.3.0/gems/puma-3.7.0/lib/puma/reactor.rb:31:in `rescue in run_internal'
<path>/vendor/bundle/ruby/2.3.0/gems/puma-3.7.0/lib/puma/reactor.rb:28:in `run_internal'
<path>/vendor/bundle/ruby/2.3.0/gems/puma-3.7.0/lib/puma/reactor.rb:153:in `block in run_in_thread'
```

**Comment by sb8244** [comment]
I am seeing this on 3.11.2 as well
