### ISSUE TITLE
Segfault when start puma

### ISSUE THREAD

**Issue by bbrabbitt** [puma/puma#1574]
I recently migrated the development enviroment from ubuntu16.04 on WSL to mac os x 10.13.3 and I used the same config and gemfile. However, puma reported a segfault when I type in "rails s" or "bundle exec puma". 
I am using ruby 2.3.3p222 and rails version is 5.1.4
I originally used puma 3.9.1 and I have tried to install 3.11.1 and 3.11.4. But the error occurs each time.

here is the backtrace information
```
/Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/puma/puma_http11.bundle: [BUG] Segmentation fault at 0x00000000000000
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]


c:0053 p:-17587910730600 s:0235 e:000234 TOP    [FINISH]
c:0052 p:---- s:0233 e:000232 CFUNC  :require
c:0051 p:0012 s:0229 e:000228 BLOCK  /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292
c:0050 p:0057 s:0227 e:000226 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:258
c:0049 p:0017 s:0222 e:000221 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292
c:0048 p:0116 s:0217 e:000216 TOP    /Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/puma/server.rb:15 [FINISH]
c:0047 p:---- s:0215 e:000214 CFUNC  :require
c:0046 p:0012 s:0211 e:000210 BLOCK  /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292
c:0045 p:0057 s:0209 e:000208 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:258
c:0044 p:0017 s:0204 e:000203 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292
c:0043 p:0008 s:0199 e:000198 TOP    /Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/puma/runner.rb:1 [FINISH]
c:0042 p:---- s:0197 e:000196 CFUNC  :require
c:0041 p:0012 s:0193 e:000192 BLOCK  /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292
c:0040 p:0057 s:0191 e:000190 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:258
c:0039 p:0017 s:0186 e:000185 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292
c:0038 p:0008 s:0181 e:000180 TOP    /Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/puma/cluster.rb:1 [FINISH]
c:0037 p:---- s:0179 e:000178 CFUNC  :require
c:0036 p:0012 s:0175 e:000174 BLOCK  /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292
c:0035 p:0057 s:0173 e:000172 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:258
c:0034 p:0017 s:0168 e:000167 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292
c:0033 p:0026 s:0163 e:000162 TOP    /Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/puma/launcher.rb:4 [FINISH]
c:0032 p:---- s:0161 e:000160 CFUNC  :require
c:0031 p:0012 s:0157 e:000156 BLOCK  /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292
c:0030 p:0057 s:0155 e:000154 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:258
c:0029 p:0017 s:0150 e:000149 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292
c:0028 p:0041 s:0145 e:000144 METHOD /Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/rack/handler/puma.rb:15
c:0027 p:0016 s:0137 e:000136 METHOD /Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/rack/handler/puma.rb:62
c:0026 p:0231 s:0129 E:0026d8 METHOD /Library/Ruby/Gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:297
c:0025 p:0059 s:0123 E:002690 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/commands/server/server_command.rb:44
c:0024 p:0049 s:0120 e:000119 BLOCK  /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/commands/server/server_command.rb:135 [FINISH]
c:0023 p:---- s:0117 e:000116 CFUNC  :tap
c:0022 p:0031 s:0114 e:000113 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/commands/server/server_command.rb:130
c:0021 p:0078 s:0111 e:000110 METHOD /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27
c:0020 p:0058 s:0104 e:000103 METHOD /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126
c:0019 p:0303 s:0098 e:000097 METHOD /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369
c:0018 p:0051 s:0086 e:000085 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/command/base.rb:63
c:0017 p:0154 s:0080 e:000079 METHOD /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/command.rb:44
c:0016 p:0097 s:0070 e:000069 TOP    /Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/commands.rb:16 [FINISH]
c:0015 p:---- s:0066 e:000065 CFUNC  :require
c:0014 p:0063 s:0062 e:000061 TOP    /Users/kafuuchino/Documents/hdchina/bin/rails:9 [FINISH]
c:0013 p:---- s:0059 e:000058 CFUNC  :load
c:0012 p:0141 s:0055 e:000054 METHOD /Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28
c:0011 p:0013 s:0051 e:000050 METHOD /Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7
c:0010 p:0018 s:0047 e:000046 METHOD /Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30
c:0009 p:0337 s:0042 e:000041 TOP    /Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/bin/spring:49 [FINISH]
c:0008 p:---- s:0037 e:000036 CFUNC  :load
c:0007 p:0185 s:0033 e:000032 TOP    /Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31 [FINISH]
c:0006 p:---- s:0028 e:000027 CFUNC  :require
c:0005 p:0182 s:0024 e:000023 METHOD /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:68
c:0004 p:0150 s:0013 e:000012 TOP    /Users/kafuuchino/Documents/hdchina/bin/spring:15 [FINISH]
c:0003 p:---- s:0009 e:000008 CFUNC  :load
c:0002 p:0022 s:0005 E:001488 EVAL   bin/rails:3 [FINISH]
c:0001 p:0000 s:0002 E:0019d0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
bin/rails:3:in `<main>'
bin/rails:3:in `load'
/Users/kafuuchino/Documents/hdchina/bin/spring:15:in `<top (required)>'
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/Library/Ruby/Gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/Users/kafuuchino/Documents/hdchina/bin/rails:9:in `<top (required)>'
/Users/kafuuchino/Documents/hdchina/bin/rails:9:in `require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/commands.rb:16:in `<top (required)>'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/command.rb:44:in `invoke'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/command/base.rb:63:in `perform'
/Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/commands/server/server_command.rb:130:in `perform'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/commands/server/server_command.rb:130:in `tap'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/commands/server/server_command.rb:135:in `block in perform'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/railties/lib/rails/commands/server/server_command.rb:44:in `start'
/Library/Ruby/Gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:297:in `start'
/Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/rack/handler/puma.rb:62:in `run'
/Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/rack/handler/puma.rb:15:in `config'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `block in require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `require'
/Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/puma/launcher.rb:4:in `<top (required)>'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `block in require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `require'
/Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/puma/cluster.rb:1:in `<top (required)>'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `block in require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `require'
/Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/puma/runner.rb:1:in `<top (required)>'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `block in require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `require'
/Library/Ruby/Gems/2.3.0/gems/puma-3.11.4/lib/puma/server.rb:15:in `<top (required)>'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `block in require'
/Users/kafuuchino/.bundle/ruby/2.3.0/rails-44da91d2302a/activesupport/lib/active_support/dependencies.rb:292:in `require'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000008 rbx: 0x00007ff8059635e8 rcx: 0xffffffffffffffff
 rdx: 0x00007fff36c10c2d rdi: 0x0000000000000000 rsi: 0x0000000000000000
 rbp: 0x00007ffee8945ae0 rsp: 0x00007ffee8945ac8  r8: 0x00007ffee8945950
  r9: 0x00007ffee8945a38 r10: 0x00007ffee8945a90 r11: 0x00007ff809500000
 r12: 0x00007ffee8945af5 r13: 0x00000001076603c0 r14: 0x00007ff8059635e8
 r15: 0x00007ffee8945af0 rip: 0x0000000000000000 rfl: 0x0000000000010246

-- C level backtrace information -------------------------------------------
(nothing here)
```

here is puma.rb
```
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['RAILS_MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup DefaultRackup
port 80
environment ENV['RACK_ENV'] || 'production'

on_worker_boot do
  ActiveRecord::Base.establish_connection
end
```

**Comment by alexdowad** [comment]
Looks like something is dereferencing a null pointer in `puma_http11`, probably something called from `Init_puma_http11()` (ext/puma_http11/puma_http11.c:471-500).

Can't help you debug this because I don't have a Mac. Otherwise I would be happy to diagnose and fix the segfault.

If you want to have a go at it, add `#include <stdio.h>` at the top, put `printf`s in the code for that function, then rebuild the C extension (run extconf.rb to generate a Makefile, then `make`) and run your failing test case again. You should be able to see how far it is getting into that function before crashing.

**Comment by paulmillr** [comment]
Same shit here. Latest puma simply segfaults on Ruby 2.4.

**Comment by alexdowad** [comment]
@paulmillr, Are you also running on OS X?

**Comment by paulmillr** [comment]
@alexdowad it's FreeBSD — all good on MacOS.

**Comment by paulmillr** [comment]
@alexdowad Nevermind. All is good with Ruby 2.6. We should not use non-latest rubies.
