### ISSUE TITLE
activesupport (via Sinatra) + puma `[BUG] vm_call_cfunc - cfp consistency error`

### ISSUE THREAD

**Issue by h4xnoodle** [puma/puma#1645]
### Steps to reproduce

Occurred randomly and only once while deploying with (bosh)[https://github.com/cloudfoundry/bosh].

### Expected behavior

No crash and dump when calling https://github.com/rails/rails/blob/v5.1.4/activesupport/lib/active_support/core_ext/time/calculations.rb#L267. 

### Actual behavior

Unsure how puma is involved here, though from the trace below the originating method seems to be from `lib/puma/cluster.rb`. 

```
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/core_ext/time/calculations.rb:267: [BUG] vm_call_cfunc - cfp consistency error
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0007 p:---- s:0051 e:000050 CFUNC  :select
c:0006 p:0532 s:0043 E:001c00 METHOD /var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cluster
c:0005 p:0143 s:0029 e:000028 METHOD /var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/puma-3.12.0/lib/puma/launche
c:0004 p:0244 s:0022 E:0000b8 TOP    /var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/bin/bosh-director:42 [FINISH]
c:0003 p:---- s:0012 e:000011 CFUNC  :load
c:0002 p:0179 s:0007 E:0016f8 EVAL   /var/vcap/packages/director/bin/bosh-director:29 [FINISH]
c:0001 p:0000 s:0003 E:000b10 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/var/vcap/packages/director/bin/bosh-director:29:in `<main>'
/var/vcap/packages/director/bin/bosh-director:29:in `load'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/bin/bosh-director:42:in `<top (required)>'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cluster.rb:488:in `run'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cluster.rb:488:in `select'

-- C level backtrace information -------------------------------------------
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c3891eb8]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c3892334]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0](rb_bug+0x112) [0x5560c390085f]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c38736af]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c38737b2]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c3879273]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c388a9f5]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0](rb_iseq_eval+0x36) [0x5560c388b670]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c376a10e]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c376a1fa]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c376a4db]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c3872b55]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c3873688]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c38737b2]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c387493b]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c387503a]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c3875188]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c3879273]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c388a9f5]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0](rb_iseq_eval_main+0x36) [0x5560c388b6b0]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c37223f1]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0](ruby_exec_node+0x24) [0x5560c372251a]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0](ruby_run_node+0x3e) [0x5560c37224ed]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c37201f2]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7fe599158f45]
puma 3.12.0 (tcp://127.0.0.1:25556) [2.4.0] [0x5560c37200a9]

```

### System configuration

**Ruby version**: ruby 2.4.4p296
**Rails version**: activesupport-5.1.4 (sintra 1.4.2)  
**Puma version**: 3.12.0

**Comment by evanphx** [comment]
Sadly that is a ruby bug, not much puma can do about it.
