### ISSUE TITLE
Error in reactor loop escaped: no implicit conversion of Hash into String (TypeError)

### ISSUE THREAD

**Issue by ik5** [puma/puma#1662]
### Steps to reproduce

1) Use Ruby v2.0.0 (CentOS 7 for example)
2) Use TLS Connection
3) Get an exception

### Expected behavior

Communication over TLS

### Actual behavior

Exception:
```
Error in reactor loop escaped: no implicit conversion of Hash into String (TypeError)                                                                                                                              
/home/ik/.rvm/gems/ruby-2.0.0-p648/gems/puma-3.11.4/lib/puma/minissl.rb:56:in `read_nonblock'                                                                                                                      
/home/ik/.rvm/gems/ruby-2.0.0-p648/gems/puma-3.11.4/lib/puma/minissl.rb:56:in `read_nonblock'                                                                                                                      
/home/ik/.rvm/gems/ruby-2.0.0-p648/gems/puma-3.11.4/lib/puma/minissl.rb:127:in `read_and_drop'                                                                                                                     
/home/ik/.rvm/gems/ruby-2.0.0-p648/gems/puma-3.11.4/lib/puma/minissl.rb:144:in `close'                                                                                                                             
/home/ik/.rvm/gems/ruby-2.0.0-p648/gems/puma-3.11.4/lib/puma/client.rb:112:in `close'                                                                                                                              
/home/ik/.rvm/gems/ruby-2.0.0-p648/gems/puma-3.11.4/lib/puma/reactor.rb:115:in `rescue in block in run_internal'                                                                                                   
/home/ik/.rvm/gems/ruby-2.0.0-p648/gems/puma-3.11.4/lib/puma/reactor.rb:73:in `block in run_internal'                                                                                                              
/home/ik/.rvm/gems/ruby-2.0.0-p648/gems/puma-3.11.4/lib/puma/reactor.rb:43:in `each'                                                                                                                               
/home/ik/.rvm/gems/ruby-2.0.0-p648/gems/puma-3.11.4/lib/puma/reactor.rb:43:in `run_internal'                                                                                                                       
/home/ik/.rvm/gems/ruby-2.0.0-p648/gems/puma-3.11.4/lib/puma/reactor.rb:154:in `block in run_in_thread'
```

### System configuration

**Ruby version**: 2.0.0
**Puma version**: 3.11.xx

### Cause
The support of hash values was introduced at Ruby v2.3.0. and Puma v3.11.xx uses that newer API version.

However I'm not sure if to send a patch to fix that to that series or not. v3.10.0 of Puma still uses the old API.

**Comment by MSP-Greg** [comment]
Apology for that, as [minissl.rb:56](https://github.com/puma/puma/blob/v3.11.4/lib/puma/minissl.rb#L56) was from my PR 1444 (https://github.com/puma/puma/pull/1444/commits/ac5acc8bf9498fff7b44c710365aaa6feb2cb168) approx a year ago.  I normally work with trunk, then run a CI, which has passed with Ruby 2.2.x since.  But, as you mentioned, the `exception:` kwarg was added in Ruby 2.3.

It could be re-written to use rescue instead of the symbols, I think...

**Comment by evanphx** [comment]
Given the age, I'm going to say that for ruby 2.0, you'll need to stay on an older puma release instead.
