### ISSUE TITLE
rbenv + puma.sevice/puma.socket with ExecStop breaks restart bundler: failed to load command: puma 

### ISSUE THREAD

**Issue by rromanchuk** [puma/puma#1664]
Opening and closing for SEO,  wasted too much time on this. 

```
ExecStart=/home/ubuntu/.rbenv/bin/rbenv exec bundle exec puma -C {{deploy_directory}}/shared/config/puma/production.rb
ExecStop=/home/ubuntu/.rbenv/bin/rbenv exec bundle exec pumactl -S {{deploy_directory}}/shared/tmp/pids/puma.state stop
```

on `sudo systemctl restart puma`

```
Oct 24 08:33:37  puma[14012]: [14012] - Gracefully shutting down workers...
Oct 24 08:33:37 puma[14012]: On worker shutdown...
Oct 24 08:33:37 puma[14012]: On worker shutdown...
Oct 24 08:33:37  puma[18850]: Command stop sent success
Oct 24 08:33:37  puma[14012]: On worker shutdown...
Oct 24 08:33:37 puma[14012]: [14012] - Gracefully shutting down workers...
Oct 24 08:33:37puma[14012]: bundler: failed to load command: puma (/var/www/spar/releases/20181024082043Z/vendor/bundle/ruby/2.5.0/bin/puma)
Oct 24 08:33:37 ipuma[14012]: Errno::ECHILD: No child processes
Oct 24 08:33:37  puma[14012]:   /var/www/spar/shared/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:38:in `waitpid'
Oct 24 08:33:37  puma[14012]:   /var/www/spar/shared/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:38:in `block in stop_workers'
Oct 24 08:33:37 puma[14012]:   /var/www/spar/shared/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:38:in `each'
Oct 24 08:33:37  puma[14012]:   /var/www/spar/shared/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:38:in `stop_workers'
Oct 24 08:33:37 puma[14012]:   /var/www/spar/shared/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:391:in `block in setup_signals'
Oct 24 08:33:37  puma[14012]:   /var/www/spar/shared/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:515:in `rescue in run'
Oct 24 08:33:37puma[14012]:   /var/www/spar/shared/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:478:in `run'
Oct 24 08:33:37  puma[14012]:   /var/www/spar/shared/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
Oct 24 08:33:37  puma[14012]:   /var/www/spar/shared/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
Oct 24 08:33:37  puma[14012]:   /var/www/spar/releases/20181024082043Z/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
Oct 24 08:33:37 i puma[14012]:   /var/www/spar/releases/20181024082043Z/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
Oct 24 08:33:37  puma[14012]:   /var/www/spar/releases/20181024082043Z/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
Oct 24 08:33:37  systemd[1]: puma.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 08:33:37  systemd[1]: puma.service: Failed with result 'exit-code'.
Oct 24 08:33:37 systemd[1]: Stopped puma.
-- Subject: Unit puma.service has finished shutting down
```

The funny thing is, puma's very own documentation is correct https://github.com/puma/puma/blob/master/docs/systemd.md

long story short, RTFM

**Comment by rromanchuk** [comment]
Also anyone reading, be aware, with `Restart=always` the service *will* successfully start again, so if you're not paying attention to logs and status codes your restart may be broken and you may not even realize it.
