### ISSUE TITLE
 Error: in _load_from Undefined Local Variable or Method 'config'

### ISSUE THREAD

**Issue by kayceejjay** [puma/puma#1666]
### Steps to reproduce

1) ... Ubuntu 18.04/Apache2/Puma on VPS

2) ...Gemfile

[Gemfile.txt](https://github.com/puma/puma/files/2526448/Gemfile.txt)

3) ..site.conf
[site.conf.txt](https://github.com/puma/puma/files/2526488/site.conf.txt)

4) ..puma.conf.
[puma.conf.txt](https://github.com/puma/puma/files/2526491/puma.conf.txt)

### Expected behavior
Puma doesn't start

Tell us what should happen ...
Attempt to run puma in production environment get the following:
```
Traceback (most recent call last):
        14: from /home/kenneth/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
        13: from /home/kenneth/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
        12: from /home/kenneth/.rvm/gems/ruby-2.5.1/bin/puma:23:in `<main>'
        11: from /home/kenneth/.rvm/gems/ruby-2.5.1/bin/puma:23:in `load'
        10: from /home/kenneth/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/bin/puma:8:in `<top (required)>'
         9: from /home/kenneth/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/bin/puma:8:in `new'
         8: from /home/kenneth/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/cli.rb:69:in `initialize'
         7: from /home/kenneth/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/cli.rb:69:in `new'
         6: from /home/kenneth/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/launcher.rb:59:in `initialize'
         5: from /home/kenneth/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/configuration.rb:192:in `load'
         4: from /home/kenneth/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/configuration.rb:192:in `each'
         3: from /home/kenneth/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/configuration.rb:192:in `block in load'
         2: from /home/kenneth/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/dsl.rb:41:in `_load_from'
         1: from /home/kenneth/.rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/dsl.rb:41:in `instance_eval'
config/puma.rb:32:in `_load_from': undefined local variable or method `config' for #<Puma::DSL:0x0000560208a67538> (NameError)
Did you mean?  @config
```
### Actual behavior

Tell us what happens instead ...

### System configuration

**Ruby version**: ruby 2.5.1
**Rails version**: rails 5.2.1
**Puma version**: puma 3.12.0

**Comment by nateberkopec** [comment]
If this issue is still valid, please post your Puma config file.
