### ISSUE TITLE
Restart (SIGUSR2) doesn't work with Ruby 2.6.0 and Bundler 2

### ISSUE THREAD

**Issue by exviva** [puma/puma#1705]
### Steps to reproduce

1) Install Ruby 2.6.0 (ships with Bundler 1.17.2)
2) Install Bundler 2.0.1 and use it for your app
3) Start puma
4) Send SIGUSR2 to the puma process

### Expected behavior

Puma process should be restarted.

### Actual behavior

```
~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:95:in `initialize'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `new'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `initialize'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:234:in `new'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:234:in `to_definition'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:13:in `evaluate'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:34:in `build'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler.rb:135:in `definition'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler.rb:101:in `setup'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from ~/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require
```

### System configuration

**Ruby version**: 2.6.0
**Rails version**: 5.2.2
**Puma version**: 3.12.0

### More context

I played around with `lib/puma/launcher.rb`, changed `restart_command` to `bundle exec puma`, but the problem seems to be related to adding `-rbundler/setup` to `ENV['RUBYOPT']` [here](https://github.com/puma/puma/blob/v3.12.0/lib/puma/launcher.rb#L172). That addition is actually requiring Bundler code shipped with Ruby 2.6.0 (i.e. the default/"bundled" gem), on boot of the Ruby process, before `bundle exec` even kicks in. I tried it with bundle binstubs, same thing.

I can work on a PR, but don't know what the best fix should be. Maybe just detect Bundler 2 and Ruby 2.6.0 for now, and skip adding that `RUBYOPT`, or just provide an option to skip it?

**Comment by exviva** [comment]
Here's my idea for a fix: https://github.com/puma/puma/pull/1706.

**Comment by exviva** [comment]
Hmm, updating rubygems to 3.0.2 seems to have fixed the issue...:thinking:
