### ISSUE TITLE
Warmup problem when using workers

### ISSUE THREAD

**Issue by GuiTeK** [puma/puma#1757]
### Steps to reproduce

1) Clone sample project from https://github.com/GuiTeK/puma-workers-warmup-bug. This is a brand new project created with `rails new /Users/xxx/Development/puma-workers-warmup-bug --api --skip`
2) Install the necessary dependencies: if you use rbenv: `rbenv install && gem install bundler -v 1.17.2 && rbenv rehash && bundle && rbenv rehash`
3) Run server: `rails s`
4) Notice the [`puma.rb` conf](https://github.com/GuiTeK/puma-workers-warmup-bug/blob/master/config/puma.rb): `workers 2` and `threads 5, 5`. This should allow to process up to 10 (`2*5`) requests concurrently.
5) Run **two times** this command in a row: `curl http://localhost:3000/slow &`. This will query in background `http://localhost:3000/slow`, which is basically a controller returning a small JSON but with a `sleep 10` to simulate a (very) long request.
6) Right after (**dont wait more than 10sec!**), run `curl http://localhost:3000/fast`. This will query `http://localhost:3000/fast`, which is basically the same controller as `/slow` but without the `sleep 10`.

### Expected behavior

All three requests should be processed concurrently because there are 2 workers with 5 threads each, so up to 10 requests should be able to be processed concurrently.

In other words, when running `curl http://localhost:3000/fast`, it should return the response instantly.

### Actual behavior

The two first requests (`/slow`, which take 10 seconds to complete) are processed concurrently but the third one (`/fast`) hangs and is processed only after one of the first two requests has been processed.

In other words, when running `curl http://localhost:3000/fast`, it will wait about 10 seconds (the time for at least one of the two first requests to complete) before returning.

**Note that, from my tests and understanding, this behaviour is only present when the workers have not received `NB_WORKERS` requests _yet_**.

Indeed, if you re-run the 3 requests above (2 slow, 1 fast) , you will see that they are processed concurrently and that the fast one returns instantly as expected. However, **if you kill the workers or restart them, the problem occurs again**.

### System configuration

**Ruby version**: 2.5.1
**Rails version**: 5.2.3
**Puma version**: 3.11

**Comment by dannyfallon** [comment]
I can reproduce this with your test app with just one worker and 2 threads. Send the first request to `/slow` and the second to `/fast` - you expect to have the `/fast` request finish immediately but it does get blocked behind the `/slow` one.

It turns out this is not Puma's fault, but Rails and boy have I learned a lot 😂. In development you've got the following config:

```ruby
  config.cache_classes = false

  # Do not eager load code on boot.
  config.eager_load = false
```

By my rudimentary understanding the very first request is going to attempt to load a bunch of code and to do so will take a lock. It's supposed to release the lock when it's done but it's going to `sleep` as soon as it hits the controller's code. 

When the second request arrives it believes it needs the lock too, some state that is supposed to be set by the first request isn't set yet. But now the second request's thread is blocked and will wait until the first request's thread completes (or dies) and gives up the lock so it can continue.

If you change the order of the requests and visit `/fast` first it will complete and the code will be loaded which is why subsequent requests to `/slow` do not block other `/fast` requests.

Knowing this, you can even trigger this blocking behaviour on an already warm server: simply change a class (e.g. increase the `sleep` time to 15 seconds) and then for the first request after that change hit `/slow` and then try to send a request to `/fast` again - it's blocked once more. 

I'm not an expert on code unloading/reloading or the relatively new stuff Rails does to sychronise these operations. The [Rails Guide on Threading and Code Execution](https://guides.rubyonrails.org/threading_and_code_execution.html) is a decent start place for it and by adding the suggested [`ActionDispatch::DebugLocks` middleware](https://guides.rubyonrails.org/threading_and_code_execution.html#actiondispatch-debuglocks) I'm able to see the following after bumping `threads` to 3 and going to http://localhost:3000/rails/locks:


```
Thread 0 [0x3fefb00e5968 sleep]  No lock (yielded share)
  Waiting in start_exclusive to "unload"
  may be pre-empted for: "load", "unload"
  blocked by: 1

/Users/danny/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `sleep'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `wait'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:109:in `wait'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:121:in `wait_while'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:221:in `wait_for'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:83:in `block (2 levels) in start_exclusive'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:82:in `block in start_exclusive'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:77:in `start_exclusive'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:25:in `start_unloading'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:101:in `require_unload_lock!'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:120:in `class_unload!'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:177:in `block (2 levels) in <module:Finisher>'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:434:in `instance_exec'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:434:in `block in make_lambda'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:206:in `block (2 levels) in halting'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:614:in `block (2 levels) in default_terminator'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:613:in `catch'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:613:in `block in default_terminator'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:207:in `block in halting'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:521:in `block in invoke_before'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:521:in `each'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:521:in `invoke_before'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:110:in `run!'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:115:in `run!'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:72:in `block in run!'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:69:in `tap'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:69:in `run!'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:64:in `run!'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:13:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:62:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:34:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:39:in `call_app'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:27:in `block in call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:27:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:28:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:23:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:30:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:15:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:112:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_locks.rb:41:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:525:in `call'
/Users/danny/src/puma/lib/puma/configuration.rb:228:in `call'
/Users/danny/src/puma/lib/puma/server.rb:654:in `handle_request'
/Users/danny/src/puma/lib/puma/server.rb:467:in `process_client'
/Users/danny/src/puma/lib/puma/server.rb:328:in `block in run'
/Users/danny/src/puma/lib/puma/thread_pool.rb:136:in `block in spawn_thread'


---


Thread 1 [0x3fefb00e5ae4 sleep]  Sharing
  blocking: 0

/Users/danny/src/puma-workers-warmup-bug/app/controllers/tests_controller.rb:9:in `sleep'
/Users/danny/src/puma-workers-warmup-bug/app/controllers/tests_controller.rb:9:in `slow'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:100:in `run_callbacks'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:53:in `block in serve'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:36:in `each'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:36:in `serve'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:26:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:26:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:13:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:559:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:100:in `run_callbacks'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:15:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:62:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:34:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:39:in `call_app'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:27:in `block in call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:27:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:28:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:23:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:30:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:15:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:112:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_locks.rb:41:in `call'
/Users/danny/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:525:in `call'
/Users/danny/src/puma/lib/puma/configuration.rb:228:in `call'
/Users/danny/src/puma/lib/puma/server.rb:654:in `handle_request'
/Users/danny/src/puma/lib/puma/server.rb:467:in `process_client'
/Users/danny/src/puma/lib/puma/server.rb:328:in `block in run'
/Users/danny/src/puma/lib/puma/thread_pool.rb:136:in `block in spawn_thread'
```

If you want this to work, then you should disable code reloading by setting both the above config variables to `true`.

**Comment by nateberkopec** [comment]
@dannyfallon coming in with the incredible detective work again. Just wondering, does this still lock for quite as long on Rails 6, given that code loading has been completely redone by @fxn?

**Comment by dannyfallon** [comment]
This happens on Rails 6.0.0.rc1 too 😞 I nerdsniped @eugeneius who helped me a little with this earlier today. 

It doesn't happen if you do not operate in clustered mode. It doesn't happen if you swap the file watcher from `ActiveSupport::EventedFileUpdateChecker` to `ActiveSupport::FileUpdateChecker`. 

Thanks to https://github.com/rails/rails/pull/25302 if you `fork` a Rails process the `EventedFileUpdateChecker` will kick off a listener for each process that was forked. As you can see from the `Thread 1` output above there is no `InterLock` or `Reloader` in the call stack so I'd expect the lock to be given up before we enter the controller and go to sleep but I'm very likely not familiar enough with this to have a better opinion 🙈

**Comment by fxn** [comment]
Not familiar with the problem, but let me just confirm that the classic autoloader takes an exclusive lock while it is loading code, and another one when it is reloading. Each request must acquire the lock for reading.

The new autoloader does not need the one for loading. You still need the one when reloading though (but I guess there is no reloading going on here anyway).

**Comment by nateberkopec** [comment]
Considering this isn't a puma issue, closing. But great work tracking this down Danny!
