### ISSUE TITLE
I can never update with bundler, but gem is fine?

### ISSUE THREAD

**Issue by will** [puma/puma#1845]
I don’t know where to start looking for this problem since it's weird, and I've never (to my memory) seen it with another gem. For a while now, `bundle update` fails like it can't compile the c extensions, but then immediately doing `gem install puma` is fine, then bundle works. 

``` 
> bundle update
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.......
# …
Installing puma 4.0.1 (was 4.0.0) with native extensions
Using webmock 3.6.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/will/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-4.0.1/ext/puma_http11
/Users/will/.rbenv/versions/2.5.3/bin/ruby -I /Users/will/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0 -r ./siteconf20190715-47873-1gc7itw.rb extconf.rb --with-ldflags\=-L/usr/local/opt/openssl/lib\
--with-cppflags\=-I/usr/local/opt/openssl/include
checking for BIO_read() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/will/.rbenv/versions/2.5.3/bin/$(RUBY_BASE_NAME)
	--with-puma_http11-dir
	--without-puma_http11-dir
	--with-puma_http11-include
	--without-puma_http11-include=${puma_http11-dir}/include
	--with-puma_http11-lib
	--without-puma_http11-lib=${puma_http11-dir}/lib
	--with-openssl-dir
	--with-openssl-include
	--without-openssl-include=${openssl-dir}/include
	--with-openssl-lib
	--without-openssl-lib=${openssl-dir}/lib
	--with-cryptolib
	--without-cryptolib
/Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:541:in `try_link0'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:559:in `try_link'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:771:in `try_func'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:1005:in `block in have_library'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:948:in `block in checking_for'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:320:in `open'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:350:in `block in postpone'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:320:in `open'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:346:in `postpone'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:947:in `checking_for'
	from /Users/will/.rbenv/versions/2.5.3/lib/ruby/2.5.0/mkmf.rb:1000:in `have_library'
	from extconf.rb:8:in `block in <main>'
	from extconf.rb:8:in `each'
	from extconf.rb:8:in `find'
	from extconf.rb:8:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/will/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-18/2.5.0-static/puma-4.0.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/will/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-4.0.1 for inspection.
Results logged to /Users/will/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-18/2.5.0-static/puma-4.0.1/gem_make.out

An error occurred while installing puma (4.0.1), and Bundler cannot continue.
Make sure that `gem install puma -v '4.0.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  puma

> gem install puma
Building native extensions. This could take a while...
Successfully installed puma-4.0.1
1 gem installed

> bundle update
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.......
# …
Using puma 4.0.1 (was 4.0.0)
Bundle updated!
```

mkmf.log
<details>

```
have_library: checking for BIO_read() in -lcrypto... -------------------- yes

"clang -o conftest -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/x86_64-darwin18 -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/usr/local/opt/openssl/include -I/Users/will/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/will/.rbenv/versions/2.5.3/lib -L/usr/local/opt/openssl/lib -L. -L/Users/will/.rbenv/versions/2.5.3/lib  -fstack-protector -L/usr/local/lib     -lruby.2.5.3-static -framework Foundation  -lpthread -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"clang -o conftest -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/x86_64-darwin18 -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/usr/local/opt/openssl/include -I/Users/will/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/will/.rbenv/versions/2.5.3/lib -L/usr/local/opt/openssl/lib -L. -L/Users/will/.rbenv/versions/2.5.3/lib  -fstack-protector -L/usr/local/lib     -lruby.2.5.3-static -framework Foundation -lcrypto  -lpthread -ldl -lobjc "
conftest.c:13:57: error: use of undeclared identifier 'BIO_read'
int t(void) { void ((*volatile p)()); p = (void ((*)()))BIO_read; return !p; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))BIO_read; return !p; }
/* end */

"clang -o conftest -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/x86_64-darwin18 -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/usr/local/opt/openssl/include -I/Users/will/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/will/.rbenv/versions/2.5.3/lib -L/usr/local/opt/openssl/lib -L. -L/Users/will/.rbenv/versions/2.5.3/lib  -fstack-protector -L/usr/local/lib     -lruby.2.5.3-static -framework Foundation -lcrypto  -lpthread -ldl -lobjc "
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: extern void BIO_read();
14: int t(void) { BIO_read(); return 0; }
/* end */

--------------------

have_library: checking for SSL_CTX_new() in -lssl... -------------------- yes

"clang -o conftest -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/x86_64-darwin18 -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/usr/local/opt/openssl/include -I/Users/will/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/will/.rbenv/versions/2.5.3/lib -L/usr/local/opt/openssl/lib -L. -L/Users/will/.rbenv/versions/2.5.3/lib  -fstack-protector -L/usr/local/lib    -lcrypto  -lruby.2.5.3-static -framework Foundation -lssl -lcrypto  -lpthread -ldl -lobjc "
conftest.c:13:57: error: use of undeclared identifier 'SSL_CTX_new'
int t(void) { void ((*volatile p)()); p = (void ((*)()))SSL_CTX_new; return !p; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))SSL_CTX_new; return !p; }
/* end */

"clang -o conftest -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/x86_64-darwin18 -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/usr/local/opt/openssl/include -I/Users/will/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/will/.rbenv/versions/2.5.3/lib -L/usr/local/opt/openssl/lib -L. -L/Users/will/.rbenv/versions/2.5.3/lib  -fstack-protector -L/usr/local/lib    -lcrypto  -lruby.2.5.3-static -framework Foundation -lssl -lcrypto  -lpthread -ldl -lobjc "
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: extern void SSL_CTX_new();
14: int t(void) { SSL_CTX_new(); return 0; }
/* end */

--------------------

have_header: checking for openssl/bio.h... -------------------- yes

"clang -E -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/x86_64-darwin18 -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/usr/local/opt/openssl/include -I/Users/will/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <openssl/bio.h>
/* end */

--------------------

have_func: checking for DTLS_method() in openssl/ssl.h... -------------------- yes

"clang -o conftest -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/x86_64-darwin18 -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/usr/local/opt/openssl/include -I/Users/will/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/will/.rbenv/versions/2.5.3/lib -L/usr/local/opt/openssl/lib -L. -L/Users/will/.rbenv/versions/2.5.3/lib  -fstack-protector -L/usr/local/lib    -lssl -lcrypto  -lruby.2.5.3-static -framework Foundation -lssl -lcrypto  -lpthread -ldl -lobjc "
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <openssl/ssl.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12: 
13:   return 0;
14: }
15: int t(void) { void ((*volatile p)()); p = (void ((*)()))DTLS_method; return !p; }
/* end */

--------------------

have_func: checking for TLS_server_method() in openssl/ssl.h... -------------------- no

"clang -o conftest -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/x86_64-darwin18 -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/usr/local/opt/openssl/include -I/Users/will/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/will/.rbenv/versions/2.5.3/lib -L/usr/local/opt/openssl/lib -L. -L/Users/will/.rbenv/versions/2.5.3/lib  -fstack-protector -L/usr/local/lib    -lssl -lcrypto  -lruby.2.5.3-static -framework Foundation -lssl -lcrypto  -lpthread -ldl -lobjc "
conftest.c:15:57: error: use of undeclared identifier 'TLS_server_method'
int t(void) { void ((*volatile p)()); p = (void ((*)()))TLS_server_method; return !p; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <openssl/ssl.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12: 
13:   return 0;
14: }
15: int t(void) { void ((*volatile p)()); p = (void ((*)()))TLS_server_method; return !p; }
/* end */

"clang -o conftest -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/x86_64-darwin18 -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/usr/local/opt/openssl/include -I/Users/will/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/will/.rbenv/versions/2.5.3/lib -L/usr/local/opt/openssl/lib -L. -L/Users/will/.rbenv/versions/2.5.3/lib  -fstack-protector -L/usr/local/lib    -lssl -lcrypto  -lruby.2.5.3-static -framework Foundation -lssl -lcrypto  -lpthread -ldl -lobjc "
Undefined symbols for architecture x86_64:
  "_TLS_server_method", referenced from:
      _t in conftest-9a0fda.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <openssl/ssl.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12: 
13:   return 0;
14: }
15: extern void TLS_server_method();
16: int t(void) { TLS_server_method(); return 0; }
/* end */

--------------------

have_macro: checking for SSL_CTX_set_min_proto_version in openssl/ssl.h... -------------------- no

"clang -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/x86_64-darwin18 -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/will/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/usr/local/opt/openssl/include -I/Users/will/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe   -c conftest.c"
conftest.c:6:3: error: 
# error
  ^
conftest.c:7:1: error: expected identifier or '('
|:/ === SSL_CTX_set_min_proto_version undefined === /:|
^
2 errors generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <openssl/ssl.h>
4: /*top*/
5: #ifndef SSL_CTX_set_min_proto_version
6: # error
7: |:/ === SSL_CTX_set_min_proto_version undefined === /:|
8: #endif
/* end */

--------------------

```
</detials>

**Comment by nateberkopec** [comment]
I'm guessing openssl doesnt actually reside at `/usr/local/opt/openssl/include`. perhaps you have some bundler config which is pointing it to the wrong location. In any case, not a puma issue, but an issue with your bundler config (or rubygems config if not that).
