### ISSUE TITLE
binder.rb:273:in `initialize': getaddrinfo: Name or service not known (SocketError)

### ISSUE THREAD

**Issue by soumojit** [puma/puma#1909]
### Steps to reproduce
shell> rails s (produces the error as seen in the log)
shell> rails s -b 0.0.0.0 (works fine, starts server at port 3000 and acknowledges hostnames in /etc/hosts)

```
=> Booting Puma
=> Rails 5.2.3 application starting in development 
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.12.1 (ruby 2.4.5-p335), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
Exiting
/home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/puma-3.12.1/lib/puma/binder.rb:273:in `initialize': getaddrinfo: Name or service not known (SocketError)
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/puma-3.12.1/lib/puma/binder.rb:273:in `new'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/puma-3.12.1/lib/puma/binder.rb:273:in `add_tcp_listener'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/puma-3.12.1/lib/puma/binder.rb:106:in `block in parse'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/puma-3.12.1/lib/puma/binder.rb:90:in `each'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/puma-3.12.1/lib/puma/binder.rb:90:in `parse'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/puma-3.12.1/lib/puma/runner.rb:153:in `load_and_bind'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/puma-3.12.1/lib/puma/single.rb:98:in `run'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/puma-3.12.1/lib/puma/launcher.rb:186:in `run'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/puma-3.12.1/lib/rack/handler/puma.rb:73:in `run'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/rack-2.0.7/lib/rack/server.rb:297:in `start'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:53:in `start'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
	from /home/soumojit/.rbenv/versions/2.4.5/lib64/ruby/gems/2.4.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

### Expected behavior
Ideally, both the commands are identical and should work.

### System configuration

**Ruby version**: 2.4.5
**Rails version**: 5.2.3
**Puma version**: 3.12.1
**Operation System**: OpenSuse Leap 15.1

**Comment by nateberkopec** [comment]
https://github.com/puma/puma/issues/1623

**Comment by soumojit** [comment]
@nateberkopec 

The solution mentioned in #1623 -> adding 127.0.0.1 workstation to /etc/hosts
I have already tried that but still it does not seem to work!

**Comment by shawnngtq** [comment]
@soumojit @nateberkopec 

I faced the same issue. 
```
Rails 5.2.3
Version 3.12.1 (ruby 2.5.1-p57), codename: Llamas in Pajamas
/home/computername/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/binder.rb:273:in `initialize': getaddrinfo: Temporary failure in name resolution (SocketError)
```

In my `/etc/hosts`
```
127.0.0.1    localhost
```

This issue happen suddenly, I don't update any gems / ruby

**Comment by shawnngtq** [comment]
For anyone looking for solution. I don't find the solution. So I completely reinstall Ruby + Rails.
