### ISSUE TITLE
Parent Process Dying 

### ISSUE THREAD

**Issue by andresbarcenas** [puma/puma#1923]
Every since we upgraded to 4.1.0 during phased-restart and/or randomly, the parent process dies:

```deployer  76629  0.6  2.1 2527720 312060 ?      Sl   06:50   2:00 puma: cluster worker 0: 63277 [20190822104252]
deployer  76665  0.6  2.2 2461156 328136 ?      Sl   06:50   2:07 puma: cluster worker 1: 63277 [20190822104252]
deployer  76691  0.6  2.0 2391392 294372 ?      Sl   06:50   2:07 puma: cluster worker 2: 63277 [20190822104252]
deployer  76732  0.6  2.1 2593228 313772 ?      Sl   06:50   1:56 puma: cluster worker 3: 63277 [20190822104252]
deployer  76772  0.7  2.2 2461316 322060 ?      Sl   06:50   2:10 puma: cluster worker 4: 63277 [20190822104252]
deployer  76829  0.6  2.2 2460260 323980 ?      Sl   06:50   1:52 puma: cluster worker 5: 63277 [20190822104252]
deployer  76878  0.7  2.3 2392656 343968 ?      Sl   06:50   2:12 puma: cluster worker 6: 63277 [20190822104252]
deployer  76919  0.6  2.1 2325972 301644 ?      Sl   06:50   2:08 puma: cluster worker 7: 63277 [20190822104252]
deployer  76951  0.6  2.1 2390560 309164 ?      Sl   06:50   2:03 puma: cluster worker 8: 63277 [20190822104252]
deployer  76988  0.7  2.1 2463328 303716 ?      Sl   06:50   2:15 puma: cluster worker 9: 63277 [20190822104252]
deployer  77023  0.6  2.0 2459168 297592 ?      Sl   06:50   2:04 puma: cluster worker 10: 63277 [20190822104252]
deployer  77057  1.1  2.1 2390060 305028 ?      Sl   06:50   3:40 puma: cluster worker 11: 63277 [20190822104252]
```

You can see on the above output that there is no parent process running. The socket file still exists so the app is still serving traffic but the processes won't roll-restart because puma worker killer is not running

#puma.conf

```
# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers: a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
#
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 10 }
threads threads_count, threads_count

environment ENV.fetch("RAILS_ENV") { "development" }



#
# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
#
if ['development'].include?(ENV['RAILS_ENV'])
    port ENV.fetch("PORT") { 3000 }
end

if ['production','staging'].include?(ENV['RAILS_ENV'])
  app_root = File.expand_path("../../../../", __FILE__)
  pidfile "#{app_root}/shared/tmp/pids/puma.pid"
  state_path "#{app_root}/shared/tmp/pids/puma.state"
  bind "unix://#{app_root}/shared/tmp/sockets/puma.sock"
  directory "#{app_root}/current"
  daemonize true
  stdout_redirect "#{app_root}/shared/log/out.puma.log", "#{app_root}/shared/log/err.puma.log", true
  prune_bundler
end

# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked webserver processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
workers ENV.fetch("WEB_CONCURRENCY") { 1 }

# Use the `preload_app!` method when specifying a `workers` number.
# This directive tells Puma to first boot the application and load code
# before forking the application. This takes advantage of Copy On Write
# process behavior so workers use less memory. If you use this option
# you need to make sure to reconnect any threads in the `on_worker_boot`
# block.
#
# preload_app!

# If you are preloading your application and using Active Record, it's
# recommended that you close any connections to the database before workers
# are forked to prevent connection leakage.
#
initialized = false

before_fork do
  require 'puma_worker_killer'

  PUMA_MAX_MEMORY = ENV['PUMA_MAX_MEMORY'].to_f

  PumaWorkerKiller.config do |config|
    config.ram           = PUMA_MAX_MEMORY > 0 ? PUMA_MAX_MEMORY : 768 # mb
    config.frequency     = 10    # seconds
    config.percent_usage = 0.98
    config.rolling_restart_frequency = 48 * 3600 # 48 hours in seconds
    config.reaper_status_logs = ENV['PUMA_REAPER_STATUS'] || false # setting this to false will not log lines like:
    # PumaWorkerKiller: Consuming 54.34765625 mb with master and 2 workers.

    config.pre_term = -> (worker) { puts "Worker #{worker.inspect} being killed" }
  end

  unless initialized
    # router warm up
    Rails.application.routes.recognize_path('abc') rescue nil

    # get rid of rubbish so we don't share it
    GC.start

    initialized = true
  end

  PumaWorkerKiller.start



  ApplicationRecord.connection_pool.disconnect! if defined?(ActiveRecord)
end

# The code in the `on_worker_boot` will be called if you are using
# clustered mode by specifying a number of `workers`. After each worker
# process is booted, this block will be run. If you are using the `preload_app!`
# option, you will want to use this block to reconnect to any threads
# or connections that may have been created at application boot, as Ruby
# cannot share connections between processes.
#
on_worker_boot do
  ApplicationRecord.establish_connection if defined?(ActiveRecord)
end
#

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart
```

**Ruby version**: 2.6.2
**Rails version**: 5.2.2
**Puma version**: 4.1.0

**Comment by roccoblues** [comment]
Same here. Log except:

```
=== puma startup: 2019-08-28 09:05:05 +0000 ===
#<Thread:0x000055cb659a4b48@/home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/cluster.rb:279 run> terminated with exception (report_on_exception is true):
#<Thread:0x000055cb659a5188@/home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/cluster.rb:279 run> terminated with exception (report_on_exception is true):
#<Thread:0x000055cb659a41e8@/home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/cluster.rb:279 run> terminated with exception (report_on_exception is true):
/home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `write': Input/output error @ io_writev - <STDOUT>/home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `write' (: Errno::EIOInput/output error @ io_writev - <STDOUT>/home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `write') (: 
Errno::EIOInput/output error @ io_writev - <STDOUT>     from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `puts'
) (     from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `log'

Errno::EIO      from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/runner.rb:33:in `log'
        from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `puts'
)       from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/cluster.rb:281:in `block in worker'
        from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `log'

        from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/runner.rb:33:in `log'
        from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `puts'
        from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/cluster.rb:281:in `block in worker'
        from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `log'
        from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/runner.rb:33:in `log'
        from /home/deploy/apps/twentybn/shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/cluster.rb:281:in `block in worker'
```

**Comment by aligo** [comment]
same here:

/deploy/app/shared/bundle/ruby/2.4.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `write': Broken pipe @ io_write - <STDOUT> (Errno::EPIPE)
        from /deploy/app/shared/bundle/ruby/2.4.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `puts'
        from /deploy/app/shared/bundle/ruby/2.4.0/gems/puma-4.1.0/lib/puma/events.rb:69:in `log'
        from /deploy/app/shared/bundle/ruby/2.4.0/gems/puma-4.1.0/lib/puma/runner.rb:33:in `log'
        from /deploy/app/shared/bundle/ruby/2.4.0/gems/puma-4.1.0/lib/puma/cluster.rb:531:in `run'
        from /deploy/app/shared/bundle/ruby/2.4.0/gems/puma-4.1.0/lib/puma/launcher.rb:188:in `run'
        from /deploy/app/shared/bundle/ruby/2.4.0/gems/puma-4.1.0/lib/puma/cli.rb:80:in `run'
        from /deploy/app/shared/bundle/ruby/2.4.0/gems/puma-4.1.0/bin/puma-wild:31:in `<main>'

**Comment by nateberkopec** [comment]
If you're having probems with `output error @ io_writev` or `roken pipe @ io_write` you're experiencing #1905.

**Comment by roccoblues** [comment]
Probably, after downgrading to 4.0.1 everthing works as expected.

**Comment by nateberkopec** [comment]
@andresbarcenas Can you please check your logs and look for exactly what stacktrace Puma is putting out when it dies?

**Comment by andresbarcenas** [comment]
Hello @nateberkopec, I've been running puma in the foreground on a screen session and surprisingly enough, it hasn't crashed. The last few times it crashed, I couldn't see anything in the logs.

**Comment by MSP-Greg** [comment]
Kind of odd that everything listed is either from Ruby net/http or Ruby OpenSSL.  No Puma file is shown. Maybe an issue with 2.6.2?

**Comment by andresbarcenas** [comment]
Here is the error message when it dies running on development mode on the foreground 

[39897] ! Terminating timed out worker: 39908
Exiting
Traceback (most recent call last):
	17: from bin/rails:4:in `<main>'
	16: from bin/rails:4:in `require’

**Comment by nateberkopec** [comment]
I agree with @MSP-Greg, that stack should be reported to Ruby core instead.
