### ISSUE TITLE
systemd AF_UNIX domain socket activation not working

### ISSUE THREAD

**Issue by risen** [puma/puma#1976]
Even though I try to follow the guide at: [systemd.md](https://github.com/puma/puma/blob/master/docs/systemd.md), if the systemd `hellopuma.socket` file is started first and creates an AF_UNIX domain socket file, then the `hellopuma.service` fails with:

```
Sep 18 22:53:17 gretel hellopuma[13387]: /srv/user/.gem/ruby/2.5.0/gems/puma-4.1.1/lib/puma/binder.rb:377:in `add_unix_listener': There is already a server bound to: puma.sock (RuntimeError)
```

## systemd config

using a per-user systemd instance, using `loginctl enable-linger user` and `systemctl --user …`

```ini
[Unit]
Description=hellopuma service
After=network.target
Requires=hellopuma.socket

[Service]
Type=simple
Environment=PUMA_DEBUG=1
WorkingDirectory=/srv/user/hellopuma
ExecStart=/srv/user/.gem/ruby/2.5.0/bin/puma -b unix://puma.sock hello.ru
ExecReload=/bin/kill -USR2
Restart=always
SyslogIdentifier=hellopuma

[Install]
WantedBy=multi-user.target
```

```ini
[Unit]
Description=hellopuma socket

[Socket]
ListenStream=/srv/user/hellopuma/puma.sock
Backlog=1024

[Install]
WantedBy=sockets.target
```

## rack application

```ruby
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

## expected behavior

Puma takes over/binds to systemd's AF_UNIX domain socket file

## used versions

- ruby: 2.5.5p157 (and 2.6.3)
- OS: Debian GNU/Linux 10 (buster)
- puma: 4.1.1

## full log

```
Sep 18 22:53:17 gretel systemd[5700]: Started hellopuma service.
Sep 18 22:53:17 gretel hellopuma[13387]: % Registered unix:/srv/user/hellopuma/puma.sock for activation from LISTEN_FDS
Sep 18 22:53:17 gretel hellopuma[13387]: Puma starting in single mode...
Sep 18 22:53:17 gretel hellopuma[13387]: * Version 4.1.1 (ruby 2.5.5-p157), codename: Fourth and One
Sep 18 22:53:17 gretel hellopuma[13387]: * Min threads: 0, max threads: 16
Sep 18 22:53:17 gretel hellopuma[13387]: * Environment: development
Sep 18 22:53:17 gretel hellopuma[13387]: /srv/user/.gem/ruby/2.5.0/gems/puma-4.1.1/lib/puma/binder.rb:377:in `add_unix_listener': There is already a server bound to: puma.sock (RuntimeError)
Sep 18 22:53:17 gretel hellopuma[13387]:         from /srv/user/.gem/ruby/2.5.0/gems/puma-4.1.1/lib/puma/binder.rb:148:in `block in parse'
Sep 18 22:53:17 gretel hellopuma[13387]:         from /srv/user/.gem/ruby/2.5.0/gems/puma-4.1.1/lib/puma/binder.rb:97:in `each'
Sep 18 22:53:17 gretel hellopuma[13387]:         from /srv/user/.gem/ruby/2.5.0/gems/puma-4.1.1/lib/puma/binder.rb:97:in `parse'
Sep 18 22:53:17 gretel hellopuma[13387]:         from /srv/user/.gem/ruby/2.5.0/gems/puma-4.1.1/lib/puma/runner.rb:154:in `load_and_bind'
Sep 18 22:53:17 gretel hellopuma[13387]:         from /srv/user/.gem/ruby/2.5.0/gems/puma-4.1.1/lib/puma/single.rb:98:in `run'
Sep 18 22:53:17 gretel hellopuma[13387]:         from /srv/user/.gem/ruby/2.5.0/gems/puma-4.1.1/lib/puma/launcher.rb:188:in `run'
Sep 18 22:53:17 gretel hellopuma[13387]:         from /srv/user/.gem/ruby/2.5.0/gems/puma-4.1.1/lib/puma/cli.rb:80:in `run'
Sep 18 22:53:17 gretel hellopuma[13387]:         from /srv/user/.gem/ruby/2.5.0/gems/puma-4.1.1/bin/puma:10:in `<top (required)>'
Sep 18 22:53:17 gretel hellopuma[13387]:         from /srv/user/.gem/ruby/2.5.0/bin/puma:23:in `load'
Sep 18 22:53:17 gretel hellopuma[13387]:         from /srv/user/.gem/ruby/2.5.0/bin/puma:23:in `<main>'
Sep 18 22:53:17 gretel systemd[5700]: hellopuma.service: Main process exited, code=exited, status=1/FAILURE
Sep 18 22:53:17 gretel systemd[5700]: hellopuma.service: Failed with result 'exit-code'.
Sep 18 22:53:18 gretel systemd[5700]: hellopuma.service: Service RestartSec=100ms expired, scheduling restart.
Sep 18 22:53:18 gretel systemd[5700]: hellopuma.service: Scheduled restart job, restart counter is at 5.
Sep 18 22:53:18 gretel systemd[5700]: Stopped hellopuma service.
Sep 18 22:53:18 gretel systemd[5700]: hellopuma.service: Start request repeated too quickly.
Sep 18 22:53:18 gretel systemd[5700]: hellopuma.service: Failed with result 'exit-code'.
Sep 18 22:53:18 gretel systemd[5700]: Failed to start hellopuma service.
```

**Comment by dentarg** [comment]
Same as #1842 (#1775)? If so, the fix, https://github.com/puma/puma/pull/1970, will be released in [4.2.0](https://github.com/puma/puma/pull/1974/files).

Are you able to try the master branch and see if there still is a problem?

**Comment by risen** [comment]
Just tried with master, same error:

```
Sep 19 01:46:43 gretel hellopuma[18420]: /srv/user/.gem/ruby/2.5.0/gems/puma-4.2.0/lib/puma/binder.rb:378:in `add_unix_listener': There is already a server bound to: puma.sock (RuntimeError)
```


The code around there is this:

```ruby
        if File.exist? path
          begin
            old = UNIXSocket.new path
          rescue SystemCallError, IOError
            File.unlink path
          else
            old.close
            raise "There is already a server bound to: #{path}"
          end
        end

        s = UNIXServer.new(path)
```

… UNIXSocket.new('puma.sock') doesn't raise an exception until you do somethin with it, not sure how this check is supposed to work.

**Comment by nateberkopec** [comment]
👋 I've just committed an example Dockerfile to the repo: 58acb805f560f85b41128b

If you could kindly construct a Dockerfile that reproduces the issue, we can nail down the problem 👍

**Comment by rromanchuk** [comment]
@nateberkopec i need to do this too https://github.com/puma/puma/pull/1970#issuecomment-533328395

**Comment by nateberkopec** [comment]
👍

**Comment by risen** [comment]
I'm not sure what you're asking… this is about socket activation with systemd. Running systemd in a Docker container is pretty difficult, Docker and systemd don't play nice together (see: https://lwn.net/Articles/676831/ for example).

Also, did you intend to close this issue?

**Comment by nateberkopec** [comment]
whoops, I did not

**Comment by nateberkopec** [comment]
Ah I didn't know that. I guess I'll have to repro on AWS or something then, as I don't have access to a physical Linux machine.

**Comment by dentarg** [comment]
Vagrant is pretty sweet for stuff like this

**Comment by sorah** [comment]
try `-b unix:/srv/user/hellopuma/puma.sock`

**Comment by risen** [comment]
I've just tried again with version 4.3.5, and it seems to work now.

The socket triggers the service, as expected. Puma mentions LISTEN_FDS on startup:

```
May 26 12:36:52 pino hellopuma[49388]: % Registered unix:/srv/user/hellopuma/hellopuma.sock for activation from LISTEN_FDS
May 26 12:36:52 pino hellopuma[49388]: Puma starting in single mode...
May 26 12:36:52 pino hellopuma[49388]: * Version 4.3.5 (ruby 2.6.6-p146), codename: Mysterious Traveller
May 26 12:36:52 pino hellopuma[49388]: * Min threads: 0, max threads: 16
May 26 12:36:52 pino hellopuma[49388]: * Environment: development
May 26 12:36:52 pino hellopuma[49388]: * Activated unix:///srv/user/hellopuma/hellopuma.sock
May 26 12:36:52 pino hellopuma[49388]: Use Ctrl-C to stop
```

For completeness sake, here's my `~/.config/systemd/user/hellopuma.service`
```
[Unit]
Description=hellopuma service
After=network.target
Requires=hellopuma.socket

[Service]
Type=simple
Environment=PUMA_DEBUG=1
WorkingDirectory=/srv/user/hellopuma
ExecStart=/usr/bin/rbenv exec bundle exec puma --bind "unix:///srv/user/hellopuma/hellopuma.sock" --pidfile /srv/user/hellopuma/hellopuma.pid hellopuma.ru
Restart=always
SyslogIdentifier=hellopuma

[Install]
WantedBy=multi-user.target
```
And my `~/.config/systemd/user/hellopuma.socket`:
```
[Unit]
Description=hellopuma socket

[Socket]
ListenStream=/srv/user/hellopuma/hellopuma.sock
Backlog=1024

[Install]
WantedBy=sockets.target
```

I'm not sure in which version this issue got resolved, but thanks for fixing this.
