### ISSUE TITLE
Puma fails to start with Symbol not found: _ffi_type_double…  Expected in: flat namespace error

### ISSUE THREAD

**Issue by marvindanig** [puma/puma#2096]
**Describe the bug**
Unable to start Puma on my rails app after the `bundle update`.

**Puma config:**

```
# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers: a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
#
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
threads threads_count, threads_count

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
#
port        ENV.fetch("PORT") { 3000 }

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV") { "development" }

# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked webserver processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
# workers ENV.fetch("WEB_CONCURRENCY") { 2 }

# Use the `preload_app!` method when specifying a `workers` number.
# This directive tells Puma to first boot the application and load code
# before forking the application. This takes advantage of Copy On Write
# process behavior so workers use less memory.
#
# preload_app!

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart


```
**To Reproduce**

`$ bundle exec puma` throws the following error:

```
! Unable to load application: LoadError: dlopen(/Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.11.3/lib/ffi_c.bundle, 9): Symbol not found: _ffi_type_double
  Referenced from: /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.11.3/lib/ffi_c.bundle
  Expected in: flat namespace
 in /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.11.3/lib/ffi_c.bundle - /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.11.3/lib/ffi_c.bundle
Traceback (most recent call last):
	60: from /Users/sa/.rbenv/versions/2.5.1/bin/puma:23:in `<main>'
	59: from /Users/sa/.rbenv/versions/2.5.1/bin/puma:23:in `load'
	58: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-4.3.1/bin/puma:10:in `<top (required)>'
	57: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-4.3.1/lib/puma/cli.rb:80:in `run'
	56: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-4.3.1/lib/puma/launcher.rb:172:in `run'
	55: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-4.3.1/lib/puma/single.rb:98:in `run'
	54: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-4.3.1/lib/puma/runner.rb:155:in `load_and_bind'
	53: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-4.3.1/lib/puma/configuration.rb:246:in `app'
	52: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-4.3.1/lib/puma/configuration.rb:321:in `load_rackup'
	51: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/builder.rb:40:in `parse_file'
	50: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/builder.rb:49:in `new_from_string'
	49: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/builder.rb:49:in `eval'
	48: from config.ru:in `<main>'
	47: from config.ru:in `new'
	46: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/builder.rb:55:in `initialize'
	45: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.8/lib/rack/builder.rb:55:in `instance_eval'
	44: from config.ru:3:in `block in <main>'
	43: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	42: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	41: from /Users/sa/Projects/ror/bubblin.io/bubblin.io/config/environment.rb:2:in `<top (required)>'
	40: from /Users/sa/Projects/ror/bubblin.io/bubblin.io/config/environment.rb:2:in `require_relative'
	39: from /Users/sa/Projects/ror/bubblin.io/bubblin.io/config/application.rb:7:in `<top (required)>'
	38: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
	37: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
	36: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
	35: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
	34: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
	33: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	32: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	31: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	30: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	29: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	28: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	27: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
	26: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	25: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	24: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	23: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	22: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	21: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	20: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	19: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	18: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
	17: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	16: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	15: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	14: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	13: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	12: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	11: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	10: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 9: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.11.3/lib/ffi.rb:3:in `<top (required)>'
	 8: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.11.3/lib/ffi.rb:6:in `rescue in <top (required)>'
	 7: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	 6: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	 5: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	 4: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 3: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 2: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 1: from /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': dlopen(/Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.11.3/lib/ffi_c.bundle, 9): Symbol not found: _ffi_type_double (LoadError)
  Referenced from: /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.11.3/lib/ffi_c.bundle
  Expected in: flat namespace
 in /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.11.3/lib/ffi_c.bundle - /Users/sa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.11.3/lib/ffi_c.bundle
```

**Expected behavior**
The server to start normally at port 3000?

**Desktop (please complete the following information):**
 - MacOS Mohave, 10.14.6
 - Puma Version: 4.3.1

**Comment by nateberkopec** [comment]
Looks like something in `ethon`, or maybe `typhoeus` from the stack you posted. This is not a Puma issue. Good luck!
