### ISSUE TITLE
Raising from config.ru doesn't always behave the same

### ISSUE THREAD

**Issue by qortex** [puma/puma#2222]
**Describe the bug**
Let's say you have this in the first line of `config.ru`:
```ruby
raise 'This is an error'
```
When running puma, the exception will sometimes be swallowed and you just see `Early termination of worker`. Sometimes you'll see the full backtrace and the proper exception raise.

See an example run:
```
[17665] Puma starting in cluster mode...
[17665] * Version 4.3.3 (ruby 2.7.1-p83), codename: Mysterious Traveller
[17665] * Min threads: 1, max threads: 1
[17665] * Environment: development
[17665] * Process workers: 1
[17665] * Phased restart available
[17665] * Listening on tcp://0.0.0.0:9292
[17665] Use Ctrl-C to stop
Traceback (most recent call last):
        20: from /home/mic/.rbenv/versions/2.7.1/bin/puma:23:in `<main>'
        19: from /home/mic/.rbenv/versions/2.7.1/bin/puma:23:in `load'
        18: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/bin/puma:10:in `<top (required)>'
        17: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cli.rb:80:in `run'
        16: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/launcher.rb:172:in `run'
        15: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:469:in `run'
        14: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:134:in `spawn_workers'
        13: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:134:in `times'
        12: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:138:in `block in spawn_workers'
        11: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:138:in `fork'
        10: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:138:in `block (2 levels) in spawn_workers'
         9: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:269:in `worker'
         8: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/runner.rb:172:in `start_server'
         7: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/runner.rb:165:in `app'
         6: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/configuration.rb:246:in `app'
         5: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/configuration.rb:321:in `load_rackup'
         4: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
         3: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
         2: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
         1: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
config.ru:9:in `block in <main>': This is an error (RuntimeError)
[17687] Early termination of worker
[17690] Early termination of worker
[17692] Early termination of worker
[17704] Early termination of worker
[17708] Early termination of worker
[17710] Early termination of worker
[17713] Early termination of worker
[17715] Early termination of worker
[17718] Early termination of worker
Traceback (most recent call last):
        21: from /home/mic/.rbenv/versions/2.7.1/bin/puma:23:in `<main>'
        20: from /home/mic/.rbenv/versions/2.7.1/bin/puma:23:in `load'
        19: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/bin/puma:10:in `<top (required)>'
        18: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cli.rb:80:in `run'
        17: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/launcher.rb:172:in `run'
        16: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:487:in `run'
        15: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:204:in `check_workers'
        14: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:134:in `spawn_workers'
        13: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:134:in `times'
        12: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:138:in `block in spawn_workers'
        11: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:138:in `fork'
        10: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:138:in `block (2 levels) in spawn_workers'
         9: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/cluster.rb:269:in `worker'
         8: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/runner.rb:172:in `start_server'
         7: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/runner.rb:165:in `app'
         6: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/configuration.rb:246:in `app'
         5: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/configuration.rb:321:in `load_rackup'
         4: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
         3: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
         2: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
         1: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
config.ru:9:in `block in <main>': This is an error (RuntimeError)
[17726] Early termination of worker
^C[17665] - Gracefully shutting down workers...
[17665] === puma shutdown: 2020-04-11 12:23:43 +0200 ===
[17665] - Goodbye!
```

**Puma config:**

Single thread, single worker.

**Expected behavior**
I would expect the behaviour to be always the same and not randomly change.

I would expect the exception to generate a backtrace to console.
And would like the whole puma process to stop, but don't know if it's feasible or has unwanted side effects.

**Desktop (please complete the following information):**
 - OS: Linux fedora 31.
 - Puma Version: 4.3.3

**Comment by qortex** [comment]
I suspect it is a race condition regarding this code: https://github.com/puma/puma/blob/19b2a213f51921a3400854ed500ba9d336f81b7c/lib/puma/cluster.rb#L405

I suspect the exception sometimes happens before the worker has setup its signal handling?

**Comment by qortex** [comment]
Using `preload_app!` does what I initially expected.

**Comment by nateberkopec** [comment]
I agree that this is some kind of race, but I think we could probably create a reproducible example with a few `sleep` calls in the right places.

**Comment by qortex** [comment]
Here is a repro:

```ruby
# config.ru
raise 'This is an error from config.ru'
```

```ruby
# puma.rb

threads_count = 1
threads threads_count, threads_count
port 9293
workers 1

raise_exception_on_sigterm true
```
Then:
```sh
puma --config puma.rb config.ru
```

**Comment by nateberkopec** [comment]
Perfect! Thank you, I'm seeing the same now.

**Comment by dentarg** [comment]
@qortex do you mind seeing if this is still an issue with Puma 5?

**Comment by qortex** [comment]
Yes, still an issue in v5.0.4.
This repo is available for easy reproduction: https://github.com/qortex/puma-repro-2222

Run `./cmd.sh` to reproduce the issue.

```
$ puma --version
puma version 5.0.4
$ ./cmd.sh 
[27948] Puma starting in cluster mode...
[27948] * Version 5.0.4 (ruby 2.7.2-p137), codename: Spoony Bard
[27948] * Min threads: 1, max threads: 1
[27948] * Environment: development
[27948] * Process workers: 1
[27948] * Phased restart available
[27948] * Listening on http://0.0.0.0:9293
[27948] Use Ctrl-C to stop
Traceback (most recent call last):
	22: from /home/mic/.rbenv/versions/2.7.2/bin/puma:23:in `<main>'
	21: from /home/mic/.rbenv/versions/2.7.2/bin/puma:23:in `load'
	20: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/bin/puma:10:in `<top (required)>'
	19: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cli.rb:80:in `run'
	18: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/launcher.rb:171:in `run'
	17: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:394:in `run'
	16: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:71:in `spawn_workers'
	15: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:71:in `times'
	14: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:78:in `block in spawn_workers'
	13: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:96:in `spawn_worker'
	12: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:96:in `fork'
	11: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:96:in `block in spawn_worker'
	10: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:195:in `worker'
	 9: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster/worker.rb:57:in `run'
	 8: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/runner.rb:146:in `start_server'
	 7: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/runner.rb:142:in `app'
	 6: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/configuration.rb:257:in `app'
	 5: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/configuration.rb:331:in `load_rackup'
	 4: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	 3: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	 2: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	 1: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
config.ru:1:in `block in <main>': This is an error from config.ru (RuntimeError)
[27963] Early termination of worker
[27965] Early termination of worker
[27967] Early termination of worker
[27969] Early termination of worker
[27971] Early termination of worker
[27973] Early termination of worker
[27975] Early termination of worker
[27977] Early termination of worker
[27979] Early termination of worker
[27981] Early termination of worker
[27983] Early termination of worker
[27985] Early termination of worker
[27987] Early termination of worker
	23: from /home/mic/.rbenv/versions/2.7.2/bin/puma:23:in `<main>'
	22: from /home/mic/.rbenv/versions/2.7.2/bin/puma:23:in `load'
	21: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/bin/puma:10:in `<top (required)>'
	20: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cli.rb:80:in `run'
	19: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/launcher.rb:171:in `run'
	18: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:410:in `run'
	17: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:142:in `check_workers'
	16: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:71:in `spawn_workers'
	15: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:71:in `times'
	14: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:78:in `block in spawn_workers'
	13: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:96:in `spawn_worker'
	12: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:96:in `fork'
	11: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:96:in `block in spawn_worker'
	10: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster.rb:195:in `worker'
	 9: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/cluster/worker.rb:57:in `run'
	 8: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/runner.rb:146:in `start_server'
	 7: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/runner.rb:142:in `app'
	 6: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/configuration.rb:257:in `app'
	 5: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.0.4/lib/puma/configuration.rb:331:in `load_rackup'
	 4: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	 3: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	 2: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	 1: from /home/mic/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
config.ru:1:in `block in <main>': This is an error from config.ru (RuntimeError)
[27991] Early termination of worker
[27993] Early termination of worker
[27995] Early termination of worker
[27997] Early termination of worker
[27999] Early termination of worker
```
