### ISSUE TITLE
create a native gem with SSL support on Ubuntu

### ISSUE THREAD

**Issue by micheelengronne** [puma/puma#2277]
I would like to create a native gem with the SSL extension on Ubuntu to upload it in my gemstash and use it on a production server without any dev/compile dependency.

So far, no luck.

I use the `gem-compiler` gem to do it. I installed `libssl-dev` before fetching the gem and I compile with that command:

`gem compile puma-4.3.3.gem --prune`

It creates a `puma-4.3.3-x86_64-linux.gem` gem but it doesn't seem to have the SSL support as when I use it (in a gemstash docker install) I have:

```
gemstash_1  | /home/ruby/vendor/bundle/ruby/2.5.0/gems/puma-4.3.3-x86_64-linux/lib/puma/minissl/context_builder.rb:6:in `check': SSL not available in this build (StandardError)
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/puma-4.3.3-x86_64-linux/lib/puma/minissl/context_builder.rb:6:in `initialize'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/puma-4.3.3-x86_64-linux/lib/puma/binder.rb:158:in `new'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/puma-4.3.3-x86_64-linux/lib/puma/binder.rb:158:in `block in parse'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/puma-4.3.3-x86_64-linux/lib/puma/binder.rb:90:in `each'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/puma-4.3.3-x86_64-linux/lib/puma/binder.rb:90:in `parse'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/puma-4.3.3-x86_64-linux/lib/puma/cluster.rb:436:in `run'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/puma-4.3.3-x86_64-linux/lib/puma/launcher.rb:172:in `run'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/puma-4.3.3-x86_64-linux/lib/puma/cli.rb:80:in `run'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/gemstash-2.1.0/lib/gemstash/cli/start.rb:16:in `run'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/gemstash-2.1.0/lib/gemstash/cli.rb:79:in `start'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/gemstash-2.1.0/lib/gemstash/cli.rb:34:in `start'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/gems/gemstash-2.1.0/exe/gemstash:6:in `<top (required)>'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/bin/gemstash:23:in `load'
gemstash_1  | 	from /home/ruby/vendor/bundle/ruby/2.5.0/bin/gemstash:23:in `<main>'
```

**Comment by nateberkopec** [comment]
Based on your discussion over at https://github.com/luislavena/gem-compiler/issues/55, it sounds like you either have a local build env issue or an issue with the compiler gem. Good luck, but I don't believe there is anything wrong with Puma here.
