### ISSUE TITLE
Phantom tests fail with `Errno::EBADF: Bad file descriptor`

### ISSUE THREAD

**Issue by AlexWayfer** [puma/puma#2320]
**Describe the bug**

Tests are failing sometimes in current `master` (df57cecce593f1438ae4dde196231ba1b721c73f):

```
> bundle exec rake
Running RuboCop...
Inspecting 116 files
....................................................................................................................

116 files inspected, no offenses detected
mkdir -p tmp/x86_64-linux/puma_http11/2.7.1
cd tmp/x86_64-linux/puma_http11/2.7.1
/home/alex/.rbenv/versions/2.7.1/bin/ruby -I. ../../../../ext/puma_http11/extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for openssl/bio.h... yes
checking for DTLS_method() in openssl/ssl.h... yes
checking for TLS_server_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_min_proto_version in openssl/ssl.h... yes
creating Makefile
cd -
cd tmp/x86_64-linux/puma_http11/2.7.1
/usr/bin/make
compiling ../../../../ext/puma_http11/http11_parser.c
compiling ../../../../ext/puma_http11/mini_ssl.c
../../../../ext/puma_http11/mini_ssl.c: In function ‘engine_init_server’:
../../../../ext/puma_http11/mini_ssl.c:145:7: warning: unused variable ‘min’ [-Wunused-variable]
  145 |   int min, ssl_options;
      |       ^~~
../../../../ext/puma_http11/mini_ssl.c: In function ‘raise_error’:
../../../../ext/puma_http11/mini_ssl.c:299:6: warning: function might be candidate for attribute ‘noreturn’ [-Wsuggest-attribute=noreturn]
  299 | void raise_error(SSL* ssl, int result) {
      |      ^~~~~~~~~~~
../../../../ext/puma_http11/mini_ssl.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
compiling ../../../../ext/puma_http11/puma_http11.c
linking shared-object puma/puma_http11.so
cd -
cp History.md tmp/x86_64-linux/stage/History.md
cp README.md tmp/x86_64-linux/stage/README.md
cp bin/puma-wild tmp/x86_64-linux/stage/bin/puma-wild
cp docs/deployment.md tmp/x86_64-linux/stage/docs/deployment.md
cp docs/fork_worker.md tmp/x86_64-linux/stage/docs/fork_worker.md
mkdir -p tmp/x86_64-linux/stage/docs/jungle
cp docs/jungle/README.md tmp/x86_64-linux/stage/docs/jungle/README.md
mkdir -p tmp/x86_64-linux/stage/docs/jungle/rc.d
cp docs/jungle/rc.d/README.md tmp/x86_64-linux/stage/docs/jungle/rc.d/README.md
cp docs/jungle/rc.d/puma tmp/x86_64-linux/stage/docs/jungle/rc.d/puma
cp docs/jungle/rc.d/puma.conf tmp/x86_64-linux/stage/docs/jungle/rc.d/puma.conf
mkdir -p tmp/x86_64-linux/stage/docs/jungle/upstart
cp docs/jungle/upstart/README.md tmp/x86_64-linux/stage/docs/jungle/upstart/README.md
cp docs/jungle/upstart/puma-manager.conf tmp/x86_64-linux/stage/docs/jungle/upstart/puma-manager.conf
cp docs/jungle/upstart/puma.conf tmp/x86_64-linux/stage/docs/jungle/upstart/puma.conf
cp docs/signals.md tmp/x86_64-linux/stage/docs/signals.md
cp docs/systemd.md tmp/x86_64-linux/stage/docs/systemd.md
cp ext/puma_http11/PumaHttp11Service.java tmp/x86_64-linux/stage/ext/puma_http11/PumaHttp11Service.java
cp ext/puma_http11/extconf.rb tmp/x86_64-linux/stage/ext/puma_http11/extconf.rb
cp ext/puma_http11/http11_parser.c tmp/x86_64-linux/stage/ext/puma_http11/http11_parser.c
cp ext/puma_http11/http11_parser.rl tmp/x86_64-linux/stage/ext/puma_http11/http11_parser.rl
cp ext/puma_http11/mini_ssl.c tmp/x86_64-linux/stage/ext/puma_http11/mini_ssl.c
cp ext/puma_http11/org/jruby/puma/Http11.java tmp/x86_64-linux/stage/ext/puma_http11/org/jruby/puma/Http11.java
cp ext/puma_http11/org/jruby/puma/MiniSSL.java tmp/x86_64-linux/stage/ext/puma_http11/org/jruby/puma/MiniSSL.java
cp ext/puma_http11/puma_http11.c tmp/x86_64-linux/stage/ext/puma_http11/puma_http11.c
cp lib/puma.rb tmp/x86_64-linux/stage/lib/puma.rb
cp lib/puma/app/status.rb tmp/x86_64-linux/stage/lib/puma/app/status.rb
cp lib/puma/binder.rb tmp/x86_64-linux/stage/lib/puma/binder.rb
cp lib/puma/cli.rb tmp/x86_64-linux/stage/lib/puma/cli.rb
cp lib/puma/client.rb tmp/x86_64-linux/stage/lib/puma/client.rb
cp lib/puma/cluster.rb tmp/x86_64-linux/stage/lib/puma/cluster.rb
cp lib/puma/configuration.rb tmp/x86_64-linux/stage/lib/puma/configuration.rb
cp lib/puma/const.rb tmp/x86_64-linux/stage/lib/puma/const.rb
cp lib/puma/control_cli.rb tmp/x86_64-linux/stage/lib/puma/control_cli.rb
cp lib/puma/detect.rb tmp/x86_64-linux/stage/lib/puma/detect.rb
cp lib/puma/dsl.rb tmp/x86_64-linux/stage/lib/puma/dsl.rb
cp lib/puma/error_logger.rb tmp/x86_64-linux/stage/lib/puma/error_logger.rb
cp lib/puma/events.rb tmp/x86_64-linux/stage/lib/puma/events.rb
cp lib/puma/jruby_restart.rb tmp/x86_64-linux/stage/lib/puma/jruby_restart.rb
cp lib/puma/launcher.rb tmp/x86_64-linux/stage/lib/puma/launcher.rb
cp lib/puma/minissl.rb tmp/x86_64-linux/stage/lib/puma/minissl.rb
cp lib/puma/null_io.rb tmp/x86_64-linux/stage/lib/puma/null_io.rb
cp lib/puma/plugin.rb tmp/x86_64-linux/stage/lib/puma/plugin.rb
cp lib/puma/rack/builder.rb tmp/x86_64-linux/stage/lib/puma/rack/builder.rb
cp lib/puma/reactor.rb tmp/x86_64-linux/stage/lib/puma/reactor.rb
cp lib/puma/runner.rb tmp/x86_64-linux/stage/lib/puma/runner.rb
cp lib/puma/server.rb tmp/x86_64-linux/stage/lib/puma/server.rb
cp lib/puma/single.rb tmp/x86_64-linux/stage/lib/puma/single.rb
cp lib/puma/state_file.rb tmp/x86_64-linux/stage/lib/puma/state_file.rb
cp lib/puma/thread_pool.rb tmp/x86_64-linux/stage/lib/puma/thread_pool.rb
cp lib/rack/handler/puma.rb tmp/x86_64-linux/stage/lib/rack/handler/puma.rb
cp tools/Dockerfile tmp/x86_64-linux/stage/tools/Dockerfile
install -c tmp/x86_64-linux/puma_http11/2.7.1/puma_http11.so lib/puma/puma_http11.so
cp tmp/x86_64-linux/puma_http11/2.7.1/puma_http11.so tmp/x86_64-linux/stage/lib/puma/puma_http11.so

ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
RUBYOPT: -r/home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/setup
                         Puma::MiniSSL                   OpenSSL
OPENSSL_LIBRARY_VERSION: OpenSSL 1.1.1g  21 Apr 2020     OpenSSL 1.1.1g  21 Apr 2020
        OPENSSL_VERSION: OpenSSL 1.1.1g  21 Apr 2020     OpenSSL 1.1.1f  31 Mar 2020

Run options: --seed 6454

# Running:

..................................................................................................................................................................S.....S...........................................................S......................................................................................................E..S..............S..........

Fabulous run in 136.208514s, 2.6430 runs/s, 6.8425 assertions/s.

  1) Error:
TestIntegrationCluster#test_usr1_all_respond_tcp:
Errno::EBADF: Bad file descriptor
    /home/alex/Projects/ruby/puma/test/helpers/integration.rb:28:in `close'
    /home/alex/Projects/ruby/puma/test/helpers/integration.rb:28:in `block in teardown'
    /home/alex/Projects/ruby/puma/test/helpers/integration.rb:27:in `each'
    /home/alex/Projects/ruby/puma/test/helpers/integration.rb:27:in `teardown'
    /home/alex/Projects/ruby/puma/test/test_integration_cluster.rb:16:in `teardown'

360 runs, 932 assertions, 0 failures, 1 errors, 5 skips

You have skipped tests. Run with --verbose for details.

------------------------------------------------------------ Debugging Info
TestIntegrationCluster#test_term_closes_listeners_unix
    10 successes, 0 resets, 30 refused, failures 0
TestIntegrationCluster#test_term_closes_listeners_tcp
    11 successes, 1 resets, 28 refused, failures 0
---------------------------------------------------------------------------

rake aborted!
Command failed with status (1)
/home/alex/Projects/ruby/puma/.bundle/puma/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/alex/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/home/alex/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
Tasks: TOP => default => test:all => test
(See full trace by running task with --trace)
```

The second run was successful.

**Puma config:**

No, it's just `puma` tests.

**To Reproduce**

`bundle exec rake`, seed in logs above.

**Expected behavior**

Always successful tests.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Puma Version: df57cecce593f1438ae4dde196231ba1b721c73f

**Comment by nateberkopec** [comment]
@AlexWayfer Still seeing this issue? Have a CI build log anywhere we can look at?

**Comment by chaymaeBZ** [comment]
Using the same seeds on a macos machine. Macos has a `ulimit -n 256`. When we set the limit to `ulimit -n 10200`, it passes.

```
➜  puma git:(fix-2320) ✗ SEED=6454 bundle exec rake
Running RuboCop...
Inspecting 148 files
....................................................................................................................................................
148 files inspected, no offenses detected
install -c tmp/x86_64-darwin19/puma_http11/2.7.1/puma_http11.bundle lib/puma/puma_http11.bundle
cp tmp/x86_64-darwin19/puma_http11/2.7.1/puma_http11.bundle tmp/x86_64-darwin19/stage/lib/puma/puma_http11.bundle
RUBY_GC_MALLOC_LIMIT=1000000000 (default value: 16777216)
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
RUBYOPT: -r/Users/olle/.rvm/rubies/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/bundler/setup
                         Puma::MiniSSL                   OpenSSL
OPENSSL_LIBRARY_VERSION: OpenSSL 1.1.1i  8 Dec 2020      OpenSSL 1.1.1i  8 Dec 2020
        OPENSSL_VERSION: OpenSSL 1.1.1i  8 Dec 2020      OpenSSL 1.1.1f  31 Mar 2020
Run options: --seed 6454
# Running:
........................................................................................................................................SS...........................................................................................................................................................................................................................S..............S............................................E....................
Fabulous run in 173.664817s, 2.5221 runs/s, 7.3360 assertions/s.
  1) Error:
TestIntegrationCluster#test_refork:
Errno::EMFILE: Too many open files - socket(2) for "127.0.0.1" port 56037
    /Users/olle/opensource/puma/test/helpers/integration.rb:123:in `initialize'
    /Users/olle/opensource/puma/test/helpers/integration.rb:123:in `new'
    /Users/olle/opensource/puma/test/helpers/integration.rb:123:in `fast_connect'
    /Users/olle/opensource/puma/test/test_integration_cluster.rb:205:in `test_refork'
    /Users/olle/opensource/puma/test/helper.rb:67:in `block (4 levels) in run'
    /Users/olle/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
    /Users/olle/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
    /Users/olle/opensource/puma/test/helper.rb:65:in `block (3 levels) in run'
438 runs, 1274 assertions, 0 failures, 1 errors, 4 skips
You have skipped tests. Run with --verbose for details.
------------------------------------------------------------ Debugging Info
TestIntegrationSingle#test_hot_restart_does_not_drop_connections_threads
   restart_count 2, reset 0, success after restart 866
TestIntegrationSingle#test_hot_restart_does_not_drop_connections
   restart_count 5, reset 0, success after restart 465
TestIntegrationCluster#test_term_closes_listeners_unix
    10 successes, 0 resets, 30 refused, failures 0
TestIntegrationCluster#test_hot_restart_does_not_drop_connections
   restart_count 8, reset 0, success after restart 965
TestIntegrationCluster#test_hot_restart_does_not_drop_connections_threads
   restart_count 4, reset 0, success after restart 2769
TestIntegrationCluster#test_term_closes_listeners_tcp
    10 successes, 0 resets, 30 refused, failures 0
---------------------------------------------------------------------------
rake aborted!
Command failed with status (1)
/Users/olle/.rvm/gems/ruby-2.7.1/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/olle/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
/Users/olle/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => default => test:all => test
(See full trace by running task with --trace)
```

When on ubuntu: and setting ulimit -n 256, we got this failure:

```
20:26:55 olle@devbox puma  master*$ SEED=6454 bundle exec rake
Running RuboCop...
Inspecting 148 files
....................................................................................................................................................
148 files inspected, no offenses detected
install -c tmp/x86_64-linux/puma_http11/2.7.1/puma_http11.so lib/puma/puma_http11.so
cp tmp/x86_64-linux/puma_http11/2.7.1/puma_http11.so tmp/x86_64-linux/stage/lib/puma/puma_http11.so
RUBY_GC_HEAP_INIT_SLOTS=800000 (default value: 10000)
RUBY_GC_MALLOC_LIMIT=79000000 (default value: 16777216)
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
RUBYOPT: -r/opt/devbox/dependencies/ruby-ruby-2.7.1-gems-3.2.7-bundler-2.2.7-wti-2.4.11/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/setup
                         Puma::MiniSSL                   OpenSSL
OPENSSL_LIBRARY_VERSION: OpenSSL 1.1.1  11 Sep 2018      OpenSSL 1.1.1  11 Sep 2018
        OPENSSL_VERSION: OpenSSL 1.1.1  11 Sep 2018      OpenSSL 1.1.1  11 Sep 2018
Run options: --seed 6454
# Running:
..................................................................................................................................................................
......S...........................................................................................................................................................
..................................S..............S...................................S......E.....................
Fabulous run in 143.103130s, 3.0607 runs/s, 8.9236 assertions/s.
  1) Error:                                                                                                                                               [0/1902]
TestIntegrationCluster#test_refork:
Errno::EMFILE: Too many open files - socket(2) for "127.0.0.1" port 40175
    /home/olle/puma/test/helpers/integration.rb:123:in `initialize'
    /home/olle/puma/test/helpers/integration.rb:123:in `new'
    /home/olle/puma/test/helpers/integration.rb:123:in `fast_connect'
    /home/olle/puma/test/test_integration_cluster.rb:205:in `test_refork'
    /home/olle/puma/test/helper.rb:67:in `block (4 levels) in run'
    /opt/devbox/dependencies/ruby-ruby-2.7.1-gems-3.2.7-bundler-2.2.7-wti-2.4.11/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
    /opt/devbox/dependencies/ruby-ruby-2.7.1-gems-3.2.7-bundler-2.2.7-wti-2.4.11/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
    /home/olle/puma/test/helper.rb:65:in `block (3 levels) in run'
438 runs, 1277 assertions, 0 failures, 1 errors, 4 skips
You have skipped tests. Run with --verbose for details.e
```

It was solved by increasing the number of open files. Example:

```
21:02:31 olle@devbox puma  master*$ ulimit -aH
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31034
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31034
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by MSP-Greg** [comment]
@chaymaeBZ

Thanks for pointing that out.  I should have connected that.  Good to know what the normal macOS limit is.

The GitHub Actions macOS runners have a limit of 10240, Ubuntu is 65536. I've got a repo for Actions runner info.

I use WSL2/Ubuntu, and its normal limit is 1024, or maybe 4096, either way, way too low.  Also, we may have some test changes that throw a lot more connections at Puma for CI, but normally they're closed immediately...
