### ISSUE TITLE
Where is daemonize directive in 5.0.2?  

### ISSUE THREAD

**Issue by mrPsycho** [puma/puma#2437]
**Describe the bug**
Trying to start puma, and see error:
```
redmine@redmine:~/redmine$ cd /home/redmine/redmine; rbenv rehash; bundle exec puma -C /home/redmine/redmine/config/puma.rb -e production   Traceback (most recent call last):
        12: from /home/redmine/.bundler/ruby/2.7.0/bin/puma:23:in `<main>'
        11: from /home/redmine/.bundler/ruby/2.7.0/bin/puma:23:in `load'
        10: from /home/redmine/.bundler/ruby/2.7.0/gems/puma-5.0.2/bin/puma:8:in `<top (required)>'
         9: from /home/redmine/.bundler/ruby/2.7.0/gems/puma-5.0.2/bin/puma:8:in `new'
         8: from /home/redmine/.bundler/ruby/2.7.0/gems/puma-5.0.2/lib/puma/cli.rb:71:in `initialize'
         7: from /home/redmine/.bundler/ruby/2.7.0/gems/puma-5.0.2/lib/puma/cli.rb:71:in `new'
         6: from /home/redmine/.bundler/ruby/2.7.0/gems/puma-5.0.2/lib/puma/launcher.rb:59:in `initialize'
         5: from /home/redmine/.bundler/ruby/2.7.0/gems/puma-5.0.2/lib/puma/configuration.rb:205:in `load'
         4: from /home/redmine/.bundler/ruby/2.7.0/gems/puma-5.0.2/lib/puma/configuration.rb:205:in `each'
         3: from /home/redmine/.bundler/ruby/2.7.0/gems/puma-5.0.2/lib/puma/configuration.rb:205:in `block in load'
         2: from /home/redmine/.bundler/ruby/2.7.0/gems/puma-5.0.2/lib/puma/dsl.rb:47:in `_load_from'
         1: from /home/redmine/.bundler/ruby/2.7.0/gems/puma-5.0.2/lib/puma/dsl.rb:47:in `instance_eval'
/home/redmine/redmine/config/puma.rb:13:in `_load_from': undefined method `daemonize' for #<Puma::DSL:0x00005569bff4e290> (NoMethodError)
```

**Puma config:**
```
application_path = '/home/redmine/redmine'
directory application_path
environment 'production'
daemonize true
pidfile "#{application_path}/tmp/pids/puma.pid"
state_path "#{application_path}/tmp/pids/puma.state"
stdout_redirect "#{application_path}/log/puma.stdout.log", "#{application_path}/log/puma.stderr.log"
bind "unix://#{application_path}/tmp/sockets/redmine.sock"
```

**To Reproduce**
update puma to latest

**Comment by cjlarose** [comment]
Daemonization was removed without replacement in puma 5.0.0 

See History.md for the full list of changes https://github.com/puma/puma/blob/master/History.md#500--2020-09-17

If you want to run puma in the background, consider using a service manager like systemd, upstart, or supervisor.

**Comment by mrPsycho** [comment]
ok.... thanks!
