### ISSUE TITLE
Getting weird error after upgrading from Ruby 2.4 to 2.5

### ISSUE THREAD

**Issue by kassuro** [puma/puma#2456]
Hi, so I don't think it's an bug in puma, but I'm totally lost right now as I don't find any hint whats going on.

I'm tasked with upgrading an older Rails project from ruby 2.3 to current version and current Rails version. So I started with upgrading the ruby version to 2.4, all worked right out of the box. So I tried going to 2.5. As soon I use 2.5.0 or higher I get the following error:

## Error
```
Puma starting in single mode...
* Version 3.12.0 (ruby 2.5.0-p0), codename: Llamas in Pajamas
* Min threads: 0, max threads: 16
* Environment: development
IPAddr::InvalidPrefixError: invalid mask 127.255.255.255
  /usr/local/lib/ruby/2.5.0/ipaddr.rb:509:in `mask!'
  /usr/local/lib/ruby/2.5.0/ipaddr.rb:593:in `initialize'
  /box/gems/web-console-3.3.1/lib/web_console/whitelist.rb:34:in `new'
  /box/gems/web-console-3.3.1/lib/web_console/whitelist.rb:34:in `coerce_network_to_ipaddr'
  /box/gems/web-console-3.3.1/lib/web_console/whitelist.rb:13:in `map'
  /box/gems/web-console-3.3.1/lib/web_console/whitelist.rb:13:in `initialize'
  /box/gems/web-console-3.3.1/lib/web_console/railtie.rb:53:in `new'
  /box/gems/web-console-3.3.1/lib/web_console/railtie.rb:53:in `block in <class:Railtie>'
  /box/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `instance_exec'
  /box/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `run'
  /box/gems/railties-5.0.7/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /box/gems/railties-5.0.7/lib/rails/initializable.rb:54:in `run_initializers'
  /box/gems/railties-5.0.7/lib/rails/application.rb:352:in `initialize!'
  /demv_homepage/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /box/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
  /box/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /box/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
  /box/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
  /box/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
  /box/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
  /box/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
  /box/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
  /box/gems/puma-3.12.0/lib/puma/single.rb:96:in `run'
  /box/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
  /box/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
  /box/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
  /box/bin/puma:23:in `load'
  /box/bin/puma:23:in `<top (required)>'
! Unable to load application: IPAddr::InvalidPrefixError: invalid mask 127.255.255.255
bundler: failed to load command: puma (/box/bin/puma)
```

## System:
* Docker image ruby-2.5.0-slim 
* Rails: 5.0.7
* puma: 3.12.0

## puma config:
```
bind "tcp://#{ENV['BIND_ON']}"
threads_count = ENV.fetch('RAILS_MAX_THREADS') { 5 }.to_i
threads threads_count, threads_count
workers ENV.fetch('WEB_CONCURRENCY') { 2 }
worker_timeout 30
restart_command 'puma'
environment ENV.fetch('RACK_ENV') { 'production' }

```

My guess is that it's connected to the changes in ruby 2.5 in the IPAddr class. But since I haven't worked with ruby for years I'm really out of ideas how to approach this.
I hope I didn't forget any important information.

**Comment by nateberkopec** [comment]
Dunno, good luck! It's not Puma though.

It looks like whatever is creating this `IPAddr` is doing it inside a rails initializer from the web_console gem. It would maybe be helpful to look at your web_console config (whitelist?) and look for this IP.

**Comment by kassuro** [comment]
> Dunno, good luck! It's not Puma though.
> 
> It looks like whatever is creating this `IPAddr` is doing it inside a rails initializer from the web_console gem. It would maybe be helpful to look at your web_console config (whitelist?) and look for this IP.

Well thanks, your guess was totally correct. :man_facepalming: 
I'm sorry for creating this stupid issues... :(
