### ISSUE TITLE
Persistent, intermittent timeout error that makes people pull their hair out while trying to figure it out...

### ISSUE THREAD

**Issue by AdamaTNT** [puma/puma#2571]
**Describe the bug**

I have an nginx - puma server that's been running well for months.

Recently been getting 502 errors occasionally. When the issue happens nginx says:

2021/03/09 18:45:57 [error] 1341982#1341982: *1878517 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 204.237.88.42, server: www.myserver.com, request: "GET / HTTP/1.1", upstream: "http://unix:/home/app/shared/tmp/sockets/puma.sock/", host: "www.myserver.com", referrer: "https://www.referrer.ca/"

When the timeouts start happening, it lasts anywhere between 1 to 15 mins. I get the same timeout error happening multiple times in sequence. The urls being requested don't have a pattern (both computationally intensive and insignificant pages are requested that timeout). There are also no patterns in memory, disk io, cpu usage, or bandwidth that correlate with timeouts. 

When the timeouts happen, they kinda just happen...

When I take a look at the puma_error.log I see the following sequence over (I think it's related) 

```
Error during failsafe response: ActionController::UnknownFormat
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_controller/metal/mime_responds.rb:216:in `respond_to'
  /home/app/releases/20210218001340/app/controllers/errors_controller.rb:6:in `generic'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/abstract_controller/base.rb:228:in `process_action'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actiontext-6.1.1/lib/action_text/rendering.rb:20:in `with_renderer'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actiontext-6.1.1/lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:126:in `instance_exec'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/notifications.rb:203:in `block in instrument'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/notifications.rb:203:in `instrument'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activerecord-6.1.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/abstract_controller/base.rb:165:in `process'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionview-6.1.1/lib/action_view/rendering.rb:39:in `process'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_controller/metal.rb:190:in `dispatch'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_controller/metal.rb:254:in `dispatch'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/journey/router.rb:32:in `each'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/journey/router.rb:32:in `serve'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:842:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/show_exceptions.rb:52:in `render_exception'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/railties-6.1.1/lib/rails/rack/logger.rb:37:in `call_app'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/railties-6.1.1/lib/rails/rack/logger.rb:26:in `block in call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/tagged_logging.rb:37:in `tagged'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/tagged_logging.rb:99:in `tagged'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/railties-6.1.1/lib/rails/rack/logger.rb:26:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/static.rb:24:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/ssl.rb:77:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/railties-6.1.1/lib/rails/engine.rb:539:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/puma-5.2.0/lib/puma/configuration.rb:247:in `call'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/puma-5.2.0/lib/puma/request.rb:76:in `block in handle_request'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/puma-5.2.0/lib/puma/thread_pool.rb:337:in `with_force_shutdown'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/puma-5.2.0/lib/puma/request.rb:75:in `handle_request'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/puma-5.2.0/lib/puma/server.rb:432:in `process_client'
  /mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/puma-5.2.0/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

**Puma config:**
#!/usr/bin/env puma

directory '/home/app/current'
rackup "/home/app/current/config.ru"
environment 'production'

tag ''

pidfile "/home/app/shared/tmp/pids/puma.pid"
state_path "/home/app/shared/tmp/pids/puma.state"
stdout_redirect '/home/app/shared/log/puma_access.log', '/home/app/shared/log/puma_error.log', true

threads 0,16

bind 'unix:///home/app/shared/tmp/sockets/puma.sock'

workers 0

prune_bundler

on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = ""
end

**To Reproduce**
Happens about once a week.. Sometimes 2 times. Usually resolves itself over time. 

**Expected behavior**
Should not cause a timeout. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Puma Version 5.2.0

The box is 2 vCPUs, 2GB Ram + 36GB swap and lots and lots of HDD

**Comment by nateberkopec** [comment]
Not enough information here to figure out if this is a Puma issue or not. We can fix one thing though:

```
/mnt/volume_tor1_01/production-shared/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_controller/metal/mime_responds.rb:216:in `respond_to'
  /home/app/releases/20210218001340/app/controllers/errors_controller.rb:6:in `generic'
```

It looks like your errors controller only responds to certain formats. You need a catch-all response for any format. I'm guess you having a respond_to block in there, so you need to add an `any` format response:

```ruby
respond_to do |format|
  format.html
  format.any { render plain: "Error", status: 500 }
end
```

But beyond that, could be anything, man. You Puma process goes down and randomly comes back up after 15 minutes... dunno? Could be the machine, could be Puma's fault, could be your traffic, could be aliens 👽 

Do _all_ requests time out during the 15 minute period or just a percentage? What's the timeout set to on Nginx?

**Comment by nateberkopec** [comment]
Closed due to inactivity from OP, will reopen if response.
