### ISSUE TITLE
Hangs on "Gracefully shutting down workers..." with a Rails app and > 1 workers

### ISSUE THREAD

**Issue by morgler** [puma/puma#2621]
**Describe the bug**
When I start the server using `rails s` and then try to shut it down using `ctrl-c`, puma hangs with the message `Gracefully shutting down workers...`. The culprit seems to be the number of workers: if I go with 1 worker in the config, everything works; only if I use more workers, puma will hang on shutdown.

**Puma config:**

```
max_threads_count = ENV.fetch("MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

port        ENV.fetch("PORT") { 3000 }

environment ENV.fetch("RAILS_ENV") { "development" }

pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }

# Commenting out the following line makes the problem go away!
workers ENV.fetch("WEB_CONCURRENCY") { 2 }

before_fork do
  ActiveRecord::Base.connection_pool.disconnect! if defined?(ActiveRecord)
  Barnes.start
end

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart
```

**To Reproduce**
Create a simple Rails 6 application and add the puma gem. The `config/puma.rb` should have `workers 2`.

I also tried to start puma directly with two workers via `puma -w 2`. The result is also a hanging server on shutdown, but I get other errors:

```
[92869] Puma starting in cluster mode...
[92869] * Puma version: 5.2.2 (ruby 2.7.1-p83) ("Fettisdagsbulle")
[92869] *  Min threads: 5
[92869] *  Max threads: 5
[92869] *  Environment: development
[92869] *   Master PID: 92869
[92869] *      Workers: 2
[92869] *     Restarts: (✔) hot (✖) phased
[92869] * Preloading application
^C[92869] * Listening on http://0.0.0.0:3000
[92869] ! WARNING: Detected 5 Thread(s) started in app boot:
[92869] ! #<Thread:0x00007fa980d57da8 /Users/morgler/code/gixtra/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:334 sleep> - /Users/morgler/code/gixtra/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:337:in `sleep'
[92869] ! #<Thread:0x00007fa97e429a80 /Users/morgler/code/gixtra/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 sleep> - /Users/morgler/code/gixtra/vendor/bundle/ruby/2.7.0/gems/rb-fsevent-0.9.4/lib/rb-fsevent/fsevent.rb:42:in `select'
[92869] ! #<Thread:0x00007fa983ee3728 /Users/morgler/code/gixtra/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 sleep> - /Users/morgler/code/gixtra/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/config.rb:19:in `sleep'
[92869] ! #<Thread:0x00007fa98564d620 /Users/morgler/code/gixtra/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 sleep> - /Users/morgler/code/gixtra/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/record/entry.rb:53:in `open'
[92869] ! #<Thread:0x00007fa9881ef8f0 /Users/morgler/code/gixtra/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 sleep> - /Users/morgler/code/gixtra/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/config.rb:19:in `sleep'
[92869] Use Ctrl-C to stop
[92869] - Gracefully shutting down workers...
[92885] Early termination of worker
[92886] Early termination of worker
```

Running the `hello.ru` with my config, however, has no problems: even though it runs two workers, it shuts down gracefully upon `ctrl-c`.

```
→ be puma -C config/puma.rb hello.ru
[92981] Puma starting in cluster mode...
[92981] * Puma version: 5.2.2 (ruby 2.7.1-p83) ("Fettisdagsbulle")
[92981] *  Min threads: 5
[92981] *  Max threads: 5
[92981] *  Environment: development
[92981] *   Master PID: 92981
[92981] *      Workers: 2
[92981] *     Restarts: (✔) hot (✖) phased
[92981] * Preloading application
[92981] * Listening on http://0.0.0.0:3000
[92981] Use Ctrl-C to stop
[92981] - Worker 0 (PID: 92994) booted, phase: 0
[92981] - Worker 1 (PID: 92995) booted, phase: 0
^C[92981] - Gracefully shutting down workers...
[92981] === puma shutdown: 2021-05-05 08:23:06 +0200 ===
[92981] - Goodbye!
```

I also saw #1674 , which looks pretty similar to my issue. However, the fix from back then obviously didn't solve my issue in puma 5.2.2.

**Expected behavior**
I expect puma to shutdown upon `ctrl-c`.

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3
 - Puma Version 5.2.2
 - Rails 6.0.3.6

**Comment by nateberkopec** [comment]
If anyone else could try the stated reproduction steps here and confirm that they work, that would help.

**Comment by ye-lin-aung** [comment]
@morgler How about waiting a few seconds after sending Ctrl-c ? Does it eventually stopped the process ? or Does it stuck? I was able to reproduce similar issue but after issuing Ctrl-c and waiting for a few seconds, it will stop automatically.

**Comment by dentarg** [comment]
> Running the `hello.ru` with my config, however, has no problems: even though it runs two workers, it shuts down gracefully upon `ctrl-c`.

Doesn't sound like an issue with Puma then? Maybe you can report the issue on the rails repo? For anyone to be able to reproduce this more easily I think you need to share a complete app (Gemfile, Gemfile.lock) that exhibits the problem)

**Comment by dentarg** [comment]
@morgler still having this problem? if so, can you provide a complete repro?
