### ISSUE TITLE
WARNING: Detected 1 Thread(s) started in app boot (Puma 5.4.0

### ISSUE THREAD

**Issue by ollym** [puma/puma#2670]
**Describe the bug**
- Using ARM (AWS Graviton2)
- Ruby 3
- Rails 6
- Puma 5.4

On starting puma we get the following warning:

```
[1] ! WARNING: Detected 1 Thread(s) started in app boot:
[1] ! #<Thread:0x0000aaaae1e4e918@puma server threadpool 001 /usr/local/bundle/gems/puma-5.4.0/lib/puma/thread_pool.rb:104 sleep_forever> - /usr/local/bundle/gems/puma-5.4.0/lib/puma/thread_pool.rb:133:in `sleep'
```

Full Message:

```
[1] * Starting metrics server on tcp://0.0.0.0:23678
[1] Puma starting in cluster mode...
[1] * Puma version: 5.4.0 (ruby 3.0.1-p64) ("Super Flight")
[1] *  Min threads: 4
[1] *  Max threads: 4
[1] *  Environment: production
[1] *   Master PID: 1
[1] *      Workers: 4
[1] *     Restarts: (✔) hot (✖) phased
[1] * Preloading application
[1] * Listening on http://0.0.0.0:30454
[1] ! WARNING: Detected 1 Thread(s) started in app boot:
[1] ! #<Thread:0x0000aaaae1e4e918@puma server threadpool 001 /usr/local/bundle/gems/puma-5.4.0/lib/puma/thread_pool.rb:104 sleep_forever> - /usr/local/bundle/gems/puma-5.4.0/lib/puma/thread_pool.rb:133:in `sleep'
[1] Use Ctrl-C to stop
[1] - Worker 0 (PID: 36) booted in 0.01s, phase: 0
[1] - Worker 1 (PID: 48) booted in 0.01s, phase: 0
[1] - Worker 2 (PID: 60) booted in 0.0s, phase: 0
[1] - Worker 3 (PID: 72) booted in 0.0s, phase: 0
```

**Puma config:**

```
# Load the metrics plugin
plugin 'metrics' if ENV['PORT_METRICS']

workers Integer(ENV['WEB_CONCURRENCY'] || 0)
threads_count = Integer(ENV['RAILS_MAX_THREADS'] || 1)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

# Bind the metric server to "url". "tcp://" is the only accepted protocol.
metrics_url "tcp://0.0.0.0:#{ENV['PORT_METRICS']}" if ENV['PORT_METRICS']

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
end

lowlevel_error_handler do |e|
  Bugsnag.notify(e)
  [500, {}, ["An error has occurred, and engineers have been informed. Please reload the page. If you continue to have problems, contact support@example.com\n"]]
end
```

**To Reproduce**
Will see if i can put together a simple app to reproduce the error

**Comment by nateberkopec** [comment]
Huh... I wonder how you could be starting a threadpool thread _before_ the app even booted completely...

**Comment by cjlarose** [comment]
@ollym Puma 5.4 was just released earlier today. Did you experience the same warning before Puma 5.4? Or is this new behavior you're seeing after upgrading?

**Comment by ollym** [comment]
We tested it with the previous version and it happened there too. We figured out it was being caused by this:
https://github.com/harmjanblok/puma-metrics

Not sure how or why, but removing the metrics plugin the error went.

**Comment by dentarg** [comment]
Maybe because of https://github.com/harmjanblok/puma-metrics/blob/4655d30c26574b95370ddc84dbb37c18d20eb3d5/lib/puma/plugin/metrics.rb#L15
