### ISSUE TITLE
ssl_bind not compatible with localhost integration

### ISSUE THREAD

**Issue by erikaxel** [puma/puma#2708]
Hi,

I'm really happy that it is now (from v 5.5.0) possible to run Puma with self signed certificates generated by the localhost gem, However, I met a small bump trying to set it up.

I can run self signed SSL from the command line like this:
```puma -b 'ssl://localhost:9292' config.ru```
I would therefore expect one of the following to work in `puma.rb`:
```
ssl_bind 'localhost', '9292'
ssl_bind 'localhost', '9292', {}
```
However this does not work, I have to set it up like this:
```
  ssl_bind 'localhost', '9292', {
    key: "#{ENV["HOME"]}/.localhost/localhost.key",
    cert: "#{ENV["HOME"]}/.localhost/localhost.crt"
  }
```
I found this approach by reading #2706.

I think it would make sense to either support the first version (best in my opinion) or document the second one.

**Comment by nateberkopec** [comment]
As mentioned in #2096, you must `require localhost` inside your application (in your case, inside `config.ru`).

**Comment by nateberkopec** [comment]
Oh! I'm sorry, I didn't read your report closely enough. You're right, that doesn't work and it totally should. Marking as bug.

**Comment by rodzyn** [comment]
@erikaxel Is it still a bug? I failed to reproduce that in the latest master

**Comment by dentarg** [comment]
@rodzyn How did you try?

Using current master branch at 909f51e711ceada8e34820fdb9f07148281984a5, this still fails for me:

<Details>
<Summary><code>ssl_bind "localhost", "9292"</code></Summary>

```shell
$ cat test/config/ssl_self_signed_config.rb
require "localhost"
ssl_bind "localhost", "9292"
app do |env|
  [200, {}, ["embedded app"]]
end

$ b e bin/puma -C test/config/ssl_self_signed_config.rb
bundler: failed to load command: bin/puma (bin/puma)
/Users/dentarg/src/puma/lib/puma/dsl.rb:465:in `ssl_bind': wrong number of arguments (given 2, expected 3) (ArgumentError)
  from test/config/ssl_self_signed_config.rb:2:in `_load_from'
  from /Users/dentarg/src/puma/lib/puma/dsl.rb:81:in `instance_eval'
  from /Users/dentarg/src/puma/lib/puma/dsl.rb:81:in `_load_from'
  from /Users/dentarg/src/puma/lib/puma/configuration.rb:216:in `block in load'
  from /Users/dentarg/src/puma/lib/puma/configuration.rb:216:in `each'
  from /Users/dentarg/src/puma/lib/puma/configuration.rb:216:in `load'
  from /Users/dentarg/src/puma/lib/puma/launcher.rb:59:in `initialize'
  from /Users/dentarg/src/puma/lib/puma/cli.rb:71:in `new'
  from /Users/dentarg/src/puma/lib/puma/cli.rb:71:in `initialize'
  from bin/puma:8:in `new'
  from bin/puma:8:in `<top (required)>'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
  from /Users/dentarg/.gem/ruby/3.0.2/bin/bundle:23:in `load'
  from /Users/dentarg/.gem/ruby/3.0.2/bin/bundle:23:in `<main>'
```

</Details>

<Details>
<Summary><code>ssl_bind "localhost", "9292", {}</code></Summary>

```shell
$ cat test/config/ssl_self_signed_config.rb
require "localhost"
ssl_bind "localhost", "9292", {}
app do |env|
  [200, {}, ["embedded app"]]
end

$ b e bin/puma -C test/config/ssl_self_signed_config.rb
Puma starting in single mode...
* Puma version: 5.5.2 (ruby 3.0.2-p107) ("Zawgyi")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 90874
bundler: failed to load command: bin/puma (bin/puma)
/Users/dentarg/src/puma/lib/puma/minissl.rb:243:in `key=': No such key file '' (ArgumentError)
  from /Users/dentarg/src/puma/lib/puma/minissl/context_builder.rb:30:in `context'
  from /Users/dentarg/src/puma/lib/puma/binder.rb:247:in `block in parse'
  from /Users/dentarg/src/puma/lib/puma/binder.rb:156:in `each'
  from /Users/dentarg/src/puma/lib/puma/binder.rb:156:in `parse'
  from /Users/dentarg/src/puma/lib/puma/runner.rb:155:in `load_and_bind'
  from /Users/dentarg/src/puma/lib/puma/single.rb:44:in `run'
  from /Users/dentarg/src/puma/lib/puma/launcher.rb:181:in `run'
  from /Users/dentarg/src/puma/lib/puma/cli.rb:80:in `run'
  from bin/puma:10:in `<top (required)>'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  from /Users/dentarg/.gem/ruby/3.0.2/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
  from /Users/dentarg/.gem/ruby/3.0.2/bin/bundle:23:in `load'
  from /Users/dentarg/.gem/ruby/3.0.2/bin/bundle:23:in `<main>'
```

</Details>
