### ISSUE TITLE
LoadError: Error relocating /usr/local/bundle/gems/puma-5.5.0/lib/puma/puma_http11.so: SSL_CTX_get0_param: symbol not found - /usr/local/bundle/gems/puma-5.5.0/lib/puma/puma_http11.so

### ISSUE THREAD

**Issue by keisukeYamagishi** [puma/puma#2718]
**Describe the bug**

I tried to build a mariadb Database with rake in a Rails app running on puma.

**To Reproduce**
execute bellow command line
```
bash-4.4# rake db:create
```
or 
```
bash-4.4# rake db:migrate
```
`LoadError: Error relocating /usr/local/bundle/gems/puma-5.5.0/lib/puma/puma_http11.so: SSL_CTX_get0_param: symbol not found - /usr/local/ bundle/gems/puma-5.5.0/lib/puma/puma_http11.so`, 
I got that log so
do I need to install a different version?

Please let me know.

Run-time Log

```
bash-4.4# rake db:migrate
rake aborted!
LoadError: Error relocating /usr/local/bundle/gems/puma-5.5.0/lib/puma/puma_http11.so: SSL_CTX_get0_param: symbol not found - /usr/local/bundle/gems/puma-5.5.0/lib/puma/puma_http11.so
/usr/local/bundle/gems/puma-5.5.0/lib/puma.rb:13:in `require'
/usr/local/bundle/gems/puma-5.5.0/lib/puma.rb:13:in `<top (required)>'
/app/config/application.rb:7:in `<top (required)>'
/app/Rakefile:4:in `require_relative'
/app/Rakefile:4:in `<top (required)>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

```

**Comment by MSP-Greg** [comment]
Guessing that Puma cannot find the OpenSSL so files.  Not Ruby OpenSSL, but the system files.  I haven't had the issue locally, so not sure about the cause.  Normally, the files are located in `usr/local/ssl/lib`...

**Comment by keisukeYamagishi** [comment]
The `ssl` file does not exist directly under `/usr/local/`.
I am running it in docker.
OS is `ruby:2.5.1-alpine`.
Is there something wrong with the installation process?

**Comment by nateberkopec** [comment]
Hmmm... alpine definitely might have something to do with it. Can you `apk upgrade --update-cache --available && apk add openssl openssl-dev`?

**Comment by keisukeYamagishi** [comment]
I tried to install it, but it did not create `ssl` under `/usr/local/`,
I also get the following log

```
bash-4.4# rake db:migrate
rake aborted!
LoadError: Error relocating /usr/local/bundle/gems/puma-5.5.0/lib/puma/puma_http11.so: SSL_CTX_get0_param: symbol not found - /usr/local/bundle/gems/puma-5.5.0/lib/puma/puma_http11.so
/usr/local/bundle/gems/puma-5.5.0/lib/puma.rb:13:in `require'
/usr/local/bundle/gems/puma-5.5.0/lib/puma.rb:13:in `<top (required)>'
/app/config/application.rb:7:in `<top (required)>'
/app/Rakefile:4:in `require_relative'
/app/Rakefile:4:in `<top (required)>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
bash-4.4# 

```

**Comment by dentarg** [comment]
I'll just note that [`ruby:2.5.1-alpine`](https://hub.docker.com/layers/ruby/library/ruby/2.5.1-alpine/images/sha256-4aae041a707f8b63c5ce9ed03ae0a5b34bf8ead1a3986a86f6c5b76590015656?context=explore) is over 3 years old, so you might want to look at using something newer.

That said, I think it works? If you like Nate said above install/update OpenSSL and re-install Puma.

Here's logs from `docker run --rm -it -v $(pwd):/app -w /app ruby:2.5.1-alpine sh` (`$PWD` is checkout of Puma at `tags/v5.5.2` but I've modified `test/config/ssl_config.rb` so the cert files can be found).


```bash
/app # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
v3.7.3-184-gffd32bfd09 [http://dl-cdn.alpinelinux.org/alpine/v3.7/main]
v3.7.3-194-gcddd1b2302 [http://dl-cdn.alpinelinux.org/alpine/v3.7/community]
OK: 9057 distinct packages available

/app # apk add build-base
(1/19) Upgrading musl (1.1.18-r3 -> 1.1.18-r4)
(2/19) Installing binutils-libs (2.30-r2)
(3/19) Installing binutils (2.30-r2)
(4/19) Installing gmp (6.1.2-r1)
(5/19) Installing isl (0.18-r0)
(6/19) Installing libgomp (6.4.0-r5)
(7/19) Installing libatomic (6.4.0-r5)
(8/19) Installing libgcc (6.4.0-r5)
(9/19) Installing mpfr3 (3.1.5-r1)
(10/19) Installing mpc1 (1.0.3-r1)
(11/19) Installing libstdc++ (6.4.0-r5)
(12/19) Installing gcc (6.4.0-r5)
(13/19) Installing musl-dev (1.1.18-r4)
(14/19) Installing libc-dev (0.7.1-r0)
(15/19) Installing g++ (6.4.0-r5)
(16/19) Installing make (4.2.1-r0)
(17/19) Installing fortify-headers (0.9-r0)
(18/19) Installing build-base (0.5-r0)
(19/19) Upgrading musl-utils (1.1.18-r3 -> 1.1.18-r4)
Executing busybox-1.27.2-r11.trigger
OK: 171 MiB in 47 packages

/app # gem install puma
Building native extensions. This could take a while...
Successfully installed nio4r-2.5.8
Fetching: puma-5.5.2.gem (100%)
Building native extensions. This could take a while...
Successfully installed puma-5.5.2
2 gems installed

/app # puma -C test/config/ssl_config.rb
Puma starting in single mode...
* Puma version: 5.5.2 (ruby 2.5.1-p57) ("Zawgyi")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 136
Traceback (most recent call last):
  9: from /usr/local/bundle/bin/puma:23:in `<main>'
  8: from /usr/local/bundle/bin/puma:23:in `load'
  7: from /usr/local/bundle/gems/puma-5.5.2/bin/puma:10:in `<top (required)>'
  6: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/cli.rb:80:in `run'
  5: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/launcher.rb:181:in `run'
  4: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/single.rb:44:in `run'
  3: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/runner.rb:155:in `load_and_bind'
  2: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/binder.rb:155:in `parse'
  1: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/binder.rb:155:in `each'
/usr/local/bundle/gems/puma-5.5.2/lib/puma/binder.rb:228:in `block in parse': Puma compiled without SSL support (RuntimeError)

/app # apk add openssl openssl-dev
(1/4) Installing libcrypto1.0 (1.0.2t-r0)
(2/4) Installing libssl1.0 (1.0.2t-r0)
(3/4) Installing openssl (1.0.2t-r0)
(4/4) Installing openssl-dev (1.0.2t-r0)
Executing busybox-1.27.2-r11.trigger
Executing ca-certificates-20171114-r0.trigger
OK: 192 MiB in 51 packages

/app # puma -C test/config/ssl_config.rb
Puma starting in single mode...
* Puma version: 5.5.2 (ruby 2.5.1-p57) ("Zawgyi")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 144
Traceback (most recent call last):
  9: from /usr/local/bundle/bin/puma:23:in `<main>'
  8: from /usr/local/bundle/bin/puma:23:in `load'
  7: from /usr/local/bundle/gems/puma-5.5.2/bin/puma:10:in `<top (required)>'
  6: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/cli.rb:80:in `run'
  5: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/launcher.rb:181:in `run'
  4: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/single.rb:44:in `run'
  3: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/runner.rb:155:in `load_and_bind'
  2: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/binder.rb:155:in `parse'
  1: from /usr/local/bundle/gems/puma-5.5.2/lib/puma/binder.rb:155:in `each'
/usr/local/bundle/gems/puma-5.5.2/lib/puma/binder.rb:228:in `block in parse': Puma compiled without SSL support (RuntimeError)

/app # gem uninstall puma
Remove executables:
  puma, pumactl

in addition to the gem? [Yn]  y
Removing puma
Removing pumactl
Successfully uninstalled puma-5.5.2

/app # gem install puma
Fetching: puma-5.5.2.gem (100%)
Building native extensions. This could take a while...
Successfully installed puma-5.5.2
1 gem installed

/app # puma -C test/config/ssl_config.rb
Puma starting in single mode...
* Puma version: 5.5.2 (ruby 2.5.1-p57) ("Zawgyi")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 230
* Listening on ssl://0.0.0.0:9292?cert=/app/examples/puma/cert_puma.pem&key=/app/examples/puma/puma_keypair.pem&verify_mode=peer&ca=/app/examples/puma/client-certs/ca.crt
Use Ctrl-C to stop
```

**Comment by dentarg** [comment]
> I've modified `test/config/ssl_config.rb` so the cert files can be found

Fixed that in https://github.com/puma/puma/pull/2750

**Comment by keisukeYamagishi** [comment]
Thank you,
I Fixed it🎉
Version updated alpine
