### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _SSL_get1_peer_certificate

### ISSUE THREAD

**Issue by Uysim** [puma/puma#2727]
**Describe the bug**
I try to run rails server with ssl in the localhost. But I got error 
```
dyld: lazy symbol binding failed: Symbol not found: _SSL_get1_peer_certificate
  Referenced from: /Users/uysim/.rvm/gems/ruby-3.0.2@opt/gems/puma-5.5.2/lib/puma/puma_http11.bundle
  Expected in: flat namespace

dyld: Symbol not found: _SSL_get1_peer_certificate
  Referenced from: /Users/uysim/.rvm/gems/ruby-3.0.2@opt/gems/puma-5.5.2/lib/puma/puma_http11.bundle
  Expected in: flat namespace
```

I get the error after I upgraded to Rails 6 and Ruby 3. 

**Puma config:**

```ruby
max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count
port        ENV.fetch("PORT") { 3000 }
environment ENV.fetch("RAILS_ENV") { "development" }
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }
plugin :tmp_restart
```

Run it with:

```
rails s -b 'ssl://localhost:3000?key=/path/to/localhost.key&cert=/path/to/localhost.crt'
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Puma: 5.5.2
 - Rails 6
 - Ruby 3
- Openssl 3

**Comment by lukad** [comment]
I'm having this issue with Ruby 2.7.3 and openssl 1.1

```
~ ❯ gem install puma -v '5.4.0'
Fetching puma-5.4.0.gem
Building native extensions. This could take a while...
Successfully installed puma-5.4.0
Parsing documentation for puma-5.4.0
Installing ri documentation for puma-5.4.0
Done installing documentation for puma after 0 seconds
1 gem installed
~ ❯ puma --help
Traceback (most recent call last):
	10: from /Users/luka/.asdf/installs/ruby/2.7.3/bin/puma:23:in `<main>'
	 9: from /Users/luka/.asdf/installs/ruby/2.7.3/bin/puma:23:in `load'
	 8: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/bin/puma:6:in `<top (required)>'
	 7: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 5: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma/cli.rb:6:in `<top (required)>'
	 4: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 3: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 2: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma.rb:13:in `<top (required)>'
	 1: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': dlopen(/Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma/puma_http11.bundle, 0x0009): symbol not found in flat namespace '_SSL_get1_peer_certificate' - /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma/puma_http11.bundle (LoadError)
~ ❯ otool -L /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma/puma_http11.bundle
/Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma/puma_http11.bundle:
	/Users/luka/.asdf/installs/ruby/2.7.3/lib/libruby.2.7.dylib (compatibility version 2.7.0, current version 2.7.3)
	/Users/luka/.asdf/installs/ruby/2.7.3/openssl/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/Users/luka/.asdf/installs/ruby/2.7.3/openssl/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

I'm confused now, if that missing symbol is defined in OpenSSL 3 then why did downgrading to version 1.1 resolve the issue? And why am I having that issue with version 1.1?

**Comment by dentarg** [comment]
@lukad have you tried reinstalling/rebuilding Ruby?

**Comment by lukad** [comment]
@dentarg yes, I tried rebuilding ruby. That didn't change anything. The openssl 1.1 lib that ruby-build builds and links ruby against has the symbol `_SSL_get_peer_certificate` (`get` instead of `get1`). I don't know what to make of that.

```
~ ❯ nm -gU /Users/luka/.asdf/installs/ruby/2.7.3/openssl/lib/libssl.1.1.dylib | grep peer_certificate
000000000001b70c T _SSL_get_peer_certificate
```

**Comment by dentarg** [comment]
@lukad Can you post all the steps to reproduce this? Also include what version of macOS (I'm assuming) you are using

Can you post the output from

    ruby -r rbconfig -e 'puts RbConfig::CONFIG["configure_args"]'

And can you try to start Puma using Bundler?

Add a `Gemfile`

```ruby
# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem "puma", "5.4.0"
```

```bash
bundle install
bundle exec puma --help
```

It is likely something in your environment, I don't have this problem and we would see many reports if it was something wrong in Puma I think

**Comment by lukad** [comment]
Thanks for the help @dentarg, much appreciated.

I managed to resolve the issue by uninstalling openssl3 completely and linking ruby against my system version of openssl 1.1 by running `RUBY_CONFIGURE_OPTS="--with-openssl-dir=/opt/local/libexec/openssl11" asdf install ruby 2.7.3`

---

But here is the outputs from the commands from your command in case anyone is interested.

I installed ruby 2.7.3 on Macos 12.0.1 using asdf:

```
$ asdf install ruby 2.7.3
Downloading openssl-1.1.1l.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/0b7a3e5e59c34827fe0c3a74b7ec8baef302b98fa80088d7f9153aa16fa76bd1
Installing openssl-1.1.1l...
Installed openssl-1.1.1l to /Users/luka/.asdf/installs/ruby/2.7.3

Downloading ruby-2.7.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.3.tar.bz2
Installing ruby-2.7.3...
Installed ruby-2.7.3 to /Users/luka/.asdf/installs/ruby/2.7.3
```

Here are the configure args:

```
$ ruby -r rbconfig -e 'puts RbConfig::CONFIG["configure_args"]'
 '--prefix=/Users/luka/.asdf/installs/ruby/2.7.3' '--with-openssl-dir=/Users/luka/.asdf/installs/ruby/2.7.3/openssl' '--enable-shared' 'CC=clang' 'LDFLAGS=-L/Users/luka/.asdf/installs/ruby/2.7.3/lib ' 'CPPFLAGS=-I/Users/luka/.asdf/installs/ruby/2.7.3/include '
```

And here is the `puma --help` output using that Gemfile:

```
bundle exec puma --help
bundler: failed to load command: puma (/Users/luka/.asdf/installs/ruby/2.7.3/bin/puma)
Traceback (most recent call last):
	22: from /Users/luka/.asdf/installs/ruby/2.7.3/bin/bundle:23:in `<main>'
	21: from /Users/luka/.asdf/installs/ruby/2.7.3/bin/bundle:23:in `load'
	20: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
	19: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	18: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
	17: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli.rb:25:in `start'
	16: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	15: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli.rb:31:in `dispatch'
	14: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	13: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	12: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	11: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli.rb:478:in `exec'
	10: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:23:in `run'
	 9: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `kernel_load'
	 8: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `load'
	 7: from /Users/luka/.asdf/installs/ruby/2.7.3/bin/puma:23:in `<top (required)>'
	 6: from /Users/luka/.asdf/installs/ruby/2.7.3/bin/puma:23:in `load'
	 5: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/bin/puma:6:in `<top (required)>'
	 4: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/bin/puma:6:in `require'
	 3: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma/cli.rb:6:in `<top (required)>'
	 2: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma/cli.rb:6:in `require'
	 1: from /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma.rb:13:in `<top (required)>'
/Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma.rb:13:in `require': dlopen(/Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma/puma_http11.bundle, 0x0009): symbol not found in flat namespace '_SSL_get1_peer_certificate' - /Users/luka/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/puma-5.4.0/lib/puma/puma_http11.bundle (LoadError)
```

**Comment by dentarg** [comment]
Nice to hear that you managed to solve the issue @lukad 🎉

For the record, I'll connect this issue with https://github.com/ruby/openssl/issues/369 where OpenSSL 3.0 support for Ruby is tracked
