### ISSUE TITLE
bind and control-uri causes UNIX socket issue

### ISSUE THREAD

**Issue by DaAwesomeP** [puma/puma#2789]
**Describe the bug**
When using `--bind` and `--control-url` simultaneously in systemd with socket activation, Puma attempts to unlink the control UNIX socket. It seems to think that this is an unused socket that should be closed.

**Puma config:**

`puma.rb`:
```ruby
# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers: a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
#
max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
#
port        ENV.fetch("PORT") { 3000 }

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV") { "development" }

# Specifies the `pidfile` that Puma will use.
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }

# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked web server processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
# workers ENV.fetch("WEB_CONCURRENCY") { 2 }

# Use the `preload_app!` method when specifying a `workers` number.
# This directive tells Puma to first boot the application and load code
# before forking the application. This takes advantage of Copy On Write
# process behavior so workers use less memory.
#
# preload_app!

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart
```
`my-service@.service`
```ini
[Unit]
Description=my-service Puma HTTP Server
After=network.target

Requires=my-service@.socket

[Service]
EnvironmentFile=/srv/my-service/%i/my-service.env
WorkingDirectory=/srv/my-service/%i/repo
User=my-service-user
Environment=PUMA_BIND="unix:///srv/my-service/%i/run/puma.sock"
Environment=PUMA_CONTROL_URL="unix:///srv/my-service/%i/run/puma-ctl.sock"
Environment=PUMA_FILE="config/puma.rb"

Type=notify

WatchdogSec=10

ExecStart=/srv/my-service/%i/rbenv/shims/bundle exec --keep-file-descriptors puma -C $PUMA_FILE --control-url $PUMA_CONTROL_URL --bind $PUMA_BIND

Restart=always

[Install]
WantedBy=multi-user.target
```

`my-service@.socket`:
```ini
[Unit]
Description=my-service Puma HTTP Server Accept Sockets

[Socket]
# ListenStream=0.0.0.0:9292
# ListenStream=0.0.0.0:9293

# AF_UNIX domain socket
# SocketUser, SocketGroup, etc. may be needed for Unix domain sockets
ListenStream=/srv/my-service/%i/run/puma.sock
ListenStream=/srv/my-service/%i/run/puma-ctl.sock

SocketUser=my-service-user
SocketGroup=my-service-user

# Socket options matching Puma defaults
NoDelay=true
ReusePort=true
Backlog=1024

[Install]
WantedBy=sockets.target
```

`my-service.env`:
```env
RAILS_ENV="production"
RAILS_RELATIVE_URL_ROOT="/"
DATABASE_URL="mysql2://my-service-user@localhost/my-service-production-01?socket=/var/run/mysqld/mysqld.sock&pool=5"
RAILS_SERVE_STATIC_FILES="false"
RBENV_ROOT="/srv/my-service/production-01/rbenv"
PIDFILE="/srv/my-service/production-01/pids/puma.pid"
RAILS_MIN_THREADS="5"
RAILS_MAX_THREADS="5"
PUMA_DEBUG=1
```

Output:
```log
bundle[45493]: % ENV['LISTEN_FDS'] "2"  env_hash['LISTEN_PID'] "45493"
bundle[45493]: % Registered unix:/srv/my-service/production-01/run/puma.sock for activation from LISTEN_FDS
bundle[45493]: % Registered unix:/srv/my-service/production-01/run/puma-ctl.sock for activation from LISTEN_FDS
bundle[45493]: * Enabling systemd notification integration
bundle[45493]: Pinging systemd watchdog every 5.0 sec
bundle[45493]: Puma starting in single mode...
bundle[45493]: * Puma version: 5.5.2 (ruby 2.5.8-p224) ("Zawgyi")
bundle[45493]: *  Min threads: 5
bundle[45493]: *  Max threads: 5
bundle[45493]: *  Environment: production
bundle[45493]: *          PID: 45493
bundle[45493]: * Activated unix:///srv/my-service/production-01/run/puma.sock
bundle[45493]: * Closing unused activated socket: unix:///srv/my-service/production-01/run/puma-ctl.sock
bundle[45493]: bundler: failed to load command: puma (/srv/my-service/production-01/repo/vendor/bundle/ruby/2.5.0/bin/puma)
bundle[45493]: /srv/my-service/production-01/repo/vendor/bundle/ruby/2.5.0/gems/puma-5.5.2/lib/puma/binder.rb:290:in `unlink': Permission denied @ apply2files - /srv/my-service/production-01/run/puma-ctl.sock (Errno::EACCES)
```

Now, if I change `my-service@.socket` to only listen on one socket and remove the `--control-url` flag it works fine:
```log
bundle[45593]: % ENV['LISTEN_FDS'] "1"  env_hash['LISTEN_PID'] "45593"
bundle[45593]: % Registered unix:/srv/my-service/production-01/run/puma.sock for activation from LISTEN_FDS
bundle[45593]: * Enabling systemd notification integration
bundle[45593]: Pinging systemd watchdog every 5.0 sec
bundle[45593]: Puma starting in single mode...
bundle[45593]: * Puma version: 5.5.2 (ruby 2.5.8-p224) ("Zawgyi")
bundle[45593]: *  Min threads: 5
bundle[45593]: *  Max threads: 5
bundle[45593]: *  Environment: production
bundle[45593]: *          PID: 45593
bundle[45593]: * Activated unix:///srv/my-service/production-01/run/puma.sock
bundle[45593]: Use Ctrl-C to stop
```

**To Reproduce**

Try it out with my systemd unit files and Puma command line options above. 

**Expected behavior**
Puma should bind to both sockets.

**Desktop :**
 - OS: Debian 11 x86_64 running in KVM
 - Puma Version 5.5.2 on Ruby 2.5.8

**Comment by DaAwesomeP** [comment]
Issue seems to be coming from here:

https://github.com/puma/puma/blob/cec07ac780755755351462fed254f7edd2752631/lib/puma/binder.rb#L291-L304

Looking through that file I can't find any logic that tells it to keep open the UNIX sockets used by the control listener.

Looking here it is not adding it to any bind lists to be excluded from being closed: https://github.com/puma/puma/blob/cec07ac780755755351462fed254f7edd2752631/lib/puma/control_cli.rb#L178-L181

**Comment by MSP-Greg** [comment]
@DaAwesomeP can you try a patch?

**Comment by DaAwesomeP** [comment]
Of course! Where should I find it?

**Comment by MSP-Greg** [comment]
```patch
diff --git a/lib/puma/binder.rb b/lib/puma/binder.rb
index a9d2bda3..f4157d23 100644
--- a/lib/puma/binder.rb
+++ b/lib/puma/binder.rb
@@ -153,6 +153,7 @@ module Puma
     end
 
     def parse(binds, logger, log_msg = 'Listening')
+      is_control = log_msg == Puma::Runner::CTRL_LOG_MSG
       binds.each do |str|
         uri = URI.parse str
         case uri.scheme
@@ -289,7 +290,7 @@ module Puma
       end
 
       # Also close any unused activated sockets
-      unless @activated_sockets.empty?
+      unless @activated_sockets.empty? || is_control
         fds = @ios.map(&:to_i)
         @activated_sockets.each do |key, sock|
           next if fds.include? sock.to_i
diff --git a/lib/puma/runner.rb b/lib/puma/runner.rb
index 3dd598ae..d1ec0665 100644
--- a/lib/puma/runner.rb
+++ b/lib/puma/runner.rb
@@ -8,6 +8,9 @@ module Puma
   # serve requests. This class spawns a new instance of `Puma::Server` via
   # a call to `start_server`.
   class Runner
+
+    CTRL_LOG_MSG = 'Starting control server'
+
     def initialize(cli, events)
       @launcher = cli
       @events = events
@@ -67,7 +70,7 @@ module Puma
       control = Puma::Server.new app, @launcher.events,
         { min_threads: 0, max_threads: 1, queue_requests: false }
 
-      control.binder.parse [str], self, 'Starting control server'
+      control.binder.parse [str], self, CTRL_LOG_MSG
 
       control.run thread_name: 'ctl'
       @control = control
```

**Comment by DaAwesomeP** [comment]
Doesn't look like it printed `CTRL_LOG_MSG` before it started closing sockets:
```log
bundle[49311]: % ENV['LISTEN_FDS'] "2"  env_hash['LISTEN_PID'] "49311"
bundle[49311]: % Registered unix:/srv/my-service/production-01/run/puma.sock for activation from LISTEN_FDS
bundle[49311]: % Registered unix:/srv/my-service/production-01/run/puma-ctl.sock for activation from LISTEN_FDS
bundle[49311]: * Enabling systemd notification integration
bundle[49311]: Pinging systemd watchdog every 5.0 sec
bundle[49311]: Puma starting in single mode...
bundle[49311]: * Puma version: 5.5.2 (ruby 2.5.8-p224) ("Zawgyi")
bundle[49311]: *  Min threads: 5
bundle[49311]: *  Max threads: 5
bundle[49311]: *  Environment: production
bundle[49311]: *          PID: 49311
bundle[49311]: * Activated unix:///srv/my-service/production-01/run/puma.sock
bundle[49311]: * Closing unused activated socket: unix:///srv/my-service/production-01/run/puma-ctl.sock
bundle[49311]: bundler: failed to load command: puma (/srv/my-service/production-01/repo/vendor/bundle/ruby/2.5.0/bin/puma)
bundle[49311]: /srv/my-service/production-01/repo/vendor/bundle/ruby/2.5.0/gems/puma-5.5.2/lib/puma/binder.rb:291:in `unlink': Permission denied @ apply2files - /srv/my-service/production-01/run/puma-ctl.sock (Errno::EACCES)
```

**Comment by MSP-Greg** [comment]
@DaAwesomeP do you know if the patch worked? created the patch on master, not 5.5.2.  Regardless, I don't think that patch will work.  I'll take another look.

**Comment by DaAwesomeP** [comment]
Yeah I simply patched the files in `vendoer/bundle`, so 5.5.2. Above log output is from that. Thank you very much for looking into this!

**Comment by nateberkopec** [comment]
Good report @DaAwesomeP 👍
