### ISSUE TITLE
Thread didn't start in 5.0 seconds (in state: :starting) (Listen::Error::NotStarted)

### ISSUE THREAD

**Issue by janklimo** [puma/puma#2835]
**Describe the bug**
Starting puma with multiple workers leads to the crash detailed below.

**Puma config:**

N/A

**To Reproduce**

```
puma -t 8:32 -w 2
```
Terminal output:

```
[89950] Puma starting in cluster mode...
[89950] * Puma version: 5.6.2 (ruby 3.1.1-p18) ("Birdie's Version")
[89950] *  Min threads: 8
[89950] *  Max threads: 32
[89950] *  Environment: development
[89950] *   Master PID: 89950
[89950] *      Workers: 2
[89950] *     Restarts: (✔) hot (✖) phased
[89950] * Preloading application
WARNING: Use strings for Figaro configuration. 3000 was converted to "3000".
WARNING: Use strings for Figaro configuration. true was converted to "true".
[89950] * Listening on http://0.0.0.0:3000
[89950] ! WARNING: Detected 8 Thread(s) started in app boot:
[89950] ! #<Thread:0x0000000113fd0cc8@DEBUGGER__::SESSION@server /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:148 sleep_forever> - /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:193:in `pop'
[89950] ! #<Thread:0x00000001172b9b58@listen-wait_thread /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/thread.rb:17 sleep_forever> - /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/forwardable.rb:238:in `pop'
[89950] ! #<Thread:0x000000011782a588@listen-worker_thread /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/thread.rb:17 sleep> - /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rb-fsevent-0.11.1/lib/rb-fsevent/fsevent.rb:44:in `select'
[89950] ! #<Rack::MiniProfiler::FileStore::CacheCleanupThread:0x0000000117c23180 /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rack-mini-profiler-2.3.4/lib/mini_profiler/storage/file_store.rb:65 sleep> - /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rack-mini-profiler-2.3.4/lib/mini_profiler/storage/file_store.rb:83:in `sleep'
[89950] ! #<Thread:0x0000000117d0b408@listen-wait_thread /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/thread.rb:17 sleep_forever> - /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/forwardable.rb:238:in `pop'
[89950] ! #<Thread:0x0000000117d13068@listen-worker_thread /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/thread.rb:17 sleep> - /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rb-fsevent-0.11.1/lib/rb-fsevent/fsevent.rb:44:in `select'
[89950] ! #<Thread:0x000000011877a240@listen-run_thread /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/thread.rb:17 sleep> - /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/record/entry.rb:26:in `lstat'
[89950] ! #<Thread:0x0000000118779958@listen-wait_thread /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/thread.rb:17 sleep_forever> - /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/forwardable.rb:238:in `pop'
[89950] Use Ctrl-C to stop
/Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/event/loop.rb:57:in `start': thread didn't start in 5.0 seconds (in state: :starting) (Listen::Error::NotStarted)
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/listener.rb:75:in `block in <class:Listener>'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:124:in `instance_eval'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:124:in `call'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:105:in `transition_with_callbacks!'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:72:in `transition'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/listener.rb:93:in `start'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.2/lib/active_support/evented_file_update_checker.rb:109:in `start'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.2/lib/active_support/evented_file_update_checker.rb:89:in `block in initialize'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.2/lib/active_support/fork_tracker.rb:43:in `each'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.2/lib/active_support/fork_tracker.rb:43:in `check!'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.2/lib/active_support/fork_tracker.rb:9:in `_fork'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:2121:in `fork'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:2121:in `fork'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cluster.rb:97:in `spawn_worker'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cluster.rb:79:in `block in spawn_workers'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cluster.rb:72:in `times'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cluster.rb:72:in `spawn_workers'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cluster.rb:415:in `run'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/launcher.rb:182:in `run'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cli.rb:81:in `run'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/bin/puma:10:in `<top (required)>'
	from /Users/jan/.asdf/installs/ruby/3.1.1/bin/puma:25:in `load'
	from /Users/jan/.asdf/installs/ruby/3.1.1/bin/puma:25:in `<main>'
/Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/event/loop.rb:57:in `start': thread didn't start in 5.0 seconds (in state: :starting) (Listen::Error::NotStarted)
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/listener.rb:75:in `block in <class:Listener>'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:124:in `instance_eval'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:124:in `call'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:105:in `transition_with_callbacks!'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:72:in `transition'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/listen-3.7.1/lib/listen/listener.rb:93:in `start'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.2/lib/active_support/evented_file_update_checker.rb:109:in `start'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.2/lib/active_support/evented_file_update_checker.rb:89:in `block in initialize'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.2/lib/active_support/fork_tracker.rb:43:in `each'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.2/lib/active_support/fork_tracker.rb:43:in `check!'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.2/lib/active_support/fork_tracker.rb:9:in `_fork'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:2121:in `fork'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:2121:in `fork'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cluster.rb:97:in `spawn_worker'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cluster.rb:79:in `block in spawn_workers'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cluster.rb:72:in `times'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cluster.rb:72:in `spawn_workers'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cluster.rb:415:in `run'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/launcher.rb:182:in `run'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/lib/puma/cli.rb:81:in `run'
	from /Users/jan/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/puma-5.6.2/bin/puma:10:in `<top (required)>'
	from /Users/jan/.asdf/installs/ruby/3.1.1/bin/puma:25:in `load'
	from /Users/jan/.asdf/installs/ruby/3.1.1/bin/puma:25:in `<main>'
```

This doesn't happen with:

```
puma -t 8:32 -w 0
```

**Expected behavior**

Server starts.

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1
 - Ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]
 - Puma 5.6.2

**Comment by nateberkopec** [comment]
You're starting a lot of threads with `listen` via the evented file checker in Rails.

When Puma `fork`s to create new workers, those threads die. This is the behavior of the `fork(2)` system call. [More explanation](https://thorstenball.com/blog/2014/10/13/why-threads-cant-fork/)

So, what you are seeing is expected behavior from Puma's perspective. Given that `lib/active_support/fork_tracker` exists, this feels like a bug in Rails.

**Comment by janklimo** [comment]
Thanks for the link @nateberkopec 👍

For anyone whose error log looks fairly similar to mine, this has nothing to do with Puma. Swapping out `debug` gem for `byebug` fixed this for everyone on my team. Hope it helps.

**Comment by ralph** [comment]
For everyone coming here from Google, the suggestion by @janklimo seems to work. Also this error went away after re-generating all the binstubs. We had outdated binstubs for bundler, rails and spring in our project, not sure which one it was.

**Comment by johansenja** [comment]
For me, this happened because I had upgraded to rails 7 and not yet run `bin/rails app:update` - the key part of that which fixed it, was that it removed `load File.expand_path("spring", __dir__)` from the `bin/rails` and `bin/rake` files

**Comment by tcannonfodder** [comment]
For folks that want to continue using `debug` (which you should! It's the language default now and they are doing great work!), the solutions are:
- set `workers 0` (since if you're running `debug`, you're likely running in a local development environment).
- Configure `debug` to use remote debugging. See: https://github.com/ruby/debug?tab=readme-ov-file#remote-debugging

Basically, when `workers > 0` (puma running in cluster mode), the debug gem freaks out because it doesn't know where to attach (or it attaches to too many places), because by default the debugger operates directly on the process.
