### ISSUE TITLE
Flaky test_hot_restart_does_not_drop_connections_threads test

### ISSUE THREAD

**Issue by Apteryks** [puma/puma#3114]
**Describe the bug**
The `test_hot_restart_does_not_drop_connections_threads` sometimes fail, like:

```
Finished in 46.952074s, 12.1400 runs/s, 35.8238 assertions/s.
Errors & Failures:

  1) Failure:
TestIntegrationCluster#test_hot_restart_does_not_drop_connections_threads [/tmp/guix-build-ruby-puma-6.2.0.drv-0/source/test/helpers/integration.rb:457]:
Expected: 3000
  Actual: 2999

570 runs, 1682 assertions, 1 failures, 0 errors, 12 skips
```

**To Reproduce**
Run the test suite multiple times until it fails.

**Expected behavior**
Test should always pass.

**Desktop (please complete the following information):**
 - OS: Guix System (GNU/Linux)
 - Puma Version 6.2.0.

**Comment by Apteryks** [comment]
Another one:
```
S...........................................................................................................................SSSSS................................................Parsing options from the first comment line is deprecated!
............S...SS........................................S.................S..........................................................S........................................................................................................F..............................S.............................................................

Finished in 47.177169s, 12.0821 runs/s, 35.4621 assertions/s.
Errors & Failures:

  1) Failure:
TestIntegrationCluster#test_hot_restart_does_not_drop_connections [/tmp/guix-build-ruby-puma-6.2.0.drv-0/source/test/helpers/integration.rb:447]:
      0 unexpected_response
      0 refused
      0 read timeout
      1 reset
    999 success
    752 success after restart
      2 restart count
Expected no reset errors.
Expected: 0
  Actual: 1

570 runs, 1673 assertions, 1 failures, 0 errors, 13 skips
```

**Comment by MSP-Greg** [comment]
@Apteryks I haven't had the time, but we/I will have PR's for this, probably this weekend.

**Comment by joshuay03** [comment]
Unsure if related but I'm getting this intermittently on `master` using the MacOS Sonoma 14.0 Beta:

```ruby
#<Thread:0x000000010768ad00 /Users/joshuayoung/Projects/puma/test/helpers/integration.rb:388 run> terminated with exception (report_on_exception is true):
/Users/joshuayoung/Projects/puma/test/helpers/integration.rb:392:in `initialize': Can't assign requested address - connect(2) for "127.0.0.1" port 54325 (Errno::EADDRNOTAVAIL)
        from /Users/joshuayoung/Projects/puma/test/helpers/integration.rb:392:in `new'
        from /Users/joshuayoung/Projects/puma/test/helpers/integration.rb:392:in `block (3 levels) in hot_restart_does_not_drop_connections'
        from /Users/joshuayoung/Projects/puma/test/helpers/integration.rb:389:in `times'
        from /Users/joshuayoung/Projects/puma/test/helpers/integration.rb:389:in `block (2 levels) in hot_restart_does_not_drop_connections'
```

**Comment by Segaja** [comment]
This is still an issue to date. I would hate to have to disable the entire test on arch linux packaging, but stable tests would be appreciated.

Can this be made more stable by using a fixed seed for the tests?

**Comment by dentarg** [comment]
No, I don't think a stable seed will help.

Yes, the tests can be made stable, someone just needs to dig in and solve the problems. Like Samuel did recently: https://github.com/puma/puma/pulls?q=is%3Apr+author%3Aioquatix+

You are welcome to contribute your efforts :-)

**Comment by nateberkopec** [comment]
To make this more actionable, I am changing the title to original OP report: `test_hot_restart_does_not_drop_connections`.
