### ISSUE TITLE
Windows: puma_http11.so breaking when ruby folder is relocated

### ISSUE THREAD

**Issue by nathan-nhm** [puma/puma#3277]
I'm trying to repackage rubyinstaller-3.2.2-1-x64.7z with binary gems compiled, including Puma, so we don't have to install msys64 on customer's machines.

We don't always dictate where we install. It may go on C: , P:, N:

When unzipped on a different drive - paths properly set up - I get the dump

```
<internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': 126: The specified module could not be found.   - p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/puma_http11.so (LoadError)
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma.rb:12:in `<main>'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:60:in `block (2 levels) in require'
        from p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:55:in `each'
        from p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:55:in `block in require'
        from p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:44:in `each'
        from p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:44:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/bundler.rb:187:in `require'
        from P:/NHM/mdw63/plugins/mdw_core/config/application.rb:19:in `<main>'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from P:/NHM/mdw63/solutions/automator/config/application.rb:1:in `<main>'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/server/server_command.rb:139:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/server/server_command.rb:136:in `perform'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/base.rb:178:in `invoke_command'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/base.rb:73:in `perform'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:71:in `block in invoke'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:149:in `with_argv'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:69:in `invoke'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands.rb:18:in `<main>'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
```

p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/puma_http11.so Exists. 
P:\NHM\Ruby3221a\lib\ruby\gems\3.2.0\extensions\x64-mingw-ucrt\3.2.0\puma-6.4.0\puma/puma_http11.so also exists.

If I force re-installation of the gem - so it builds with the paths correct for the system - I have no dump, the server starts. But again, would like to avoid compiling on customer systems if possible.

**Comment by MSP-Greg** [comment]
Normally `The specified module could not be found` indicates that a dll cannot be loaded.  Does `require openssl` work on the `p` drive?

**Comment by nathan-nhm** [comment]
Irb - require works, class responds after.

rails console - After puma is commented out / bundle updated,  OpenSSL is pre-loaded.

Nothing intentionally in bin/ruby_builtin_dlls - I did update versions of the default gems but it doesn't look like it touched that folder. (all date modifieds are 1 April 2023)

**Comment by MSP-Greg** [comment]
So `libcrypto-3-x64.dll` & `libssl-3-x64.dll` are both in `bin/ruby_builtin_dlls` and `ruby_builtin_dlls.manifest` also exists (XML doc)?

**Comment by nathan-nhm** [comment]
They do.

**Comment by MSP-Greg** [comment]
What is the output from:
```
ruby -rpuma -e "puts Puma::MiniSSL::OPENSSL_LIBRARY_VERSION"
```

**Comment by nathan-nhm** [comment]
```

>ruby -rpuma -e "puts Puma::MiniSSL::OPENSSL_LIBRARY_VERSION"
<internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': 126: The specified module could not be found.   - p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/puma_http11.so (LoadError)
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from p:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma.rb:12:in `<top (required)>'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:40:in `require'
<internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- puma (LoadError)
        from <internal:p:/NHM/Ruby3221a/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'

P:\NHM\mdw63>

```

At least it's a more compact error.

**Comment by MSP-Greg** [comment]
Ok.  This shouldn't be happening.  I'm going to copy my Ruby 3.2.2 folder to my D drive, and see what happens.  Problem is, I'm about 100% sure it will work.  Give me a minute.

**Comment by nathan-nhm** [comment]
I should mention - Ruby is not in PATH- In my case, it's in %RUBY3_PATH% if I need a script to resolve it. If that has anything to do with puma's resolution.

**Comment by MSP-Greg** [comment]
> because I need to run multiple rubies

Years ago I wrote a PowerShell path switcher.

Anyway, I see you've updated rubygems/bundler.  That may also cause an issue.

But, the command I listed should work.  I copied the Ruby from C: to D:, and the code loads Puma.  Below is console output, note that I didn't switch Path:
```
PS C:\> ruby -v
ruby 3.3.0dev (2023-11-14T14:34:48Z master 336d81a671) [x64-mingw-ucrt]
PS C:\> gem list puma

*** LOCAL GEMS ***


PS C:\> D:/Ruby32-x64/bin/ruby -rpuma -e "puts Puma::MiniSSL::OPENSSL_LIBRARY_VERSION, Puma::MiniSSL::OPENSSL_VERSION"
OpenSSL 3.1.0 14 Mar 2023
OpenSSL 3.1.4 24 Oct 2023
PS C:\>
```

**Comment by MSP-Greg** [comment]
If I rename `libcrypto-3-x64.dll` or `libssl-3-x64.dll` in `bin/ruby_builtin_dlls`, I get exactly the same error you've shown.

**Comment by MSP-Greg** [comment]
Just to clarify, Puma was compiled/installed with Ruby 3.2.x?

**Comment by MSP-Greg** [comment]
Last item, lets check the puma file for the dll files it's loading.  Using a PowerShell terminal, run the following (change paths to match your system):
```
C:/msys64/ucrt64/bin/objdump.exe -p D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/puma_http11.so | Select-String -Pattern 'DLL Name:' | Sort-Object
```
Output should be identical to:
```
        DLL Name: api-ms-win-crt-environment-l1-1-0.dll
        DLL Name: api-ms-win-crt-heap-l1-1-0.dll
        DLL Name: api-ms-win-crt-private-l1-1-0.dll
        DLL Name: api-ms-win-crt-runtime-l1-1-0.dll
        DLL Name: api-ms-win-crt-stdio-l1-1-0.dll
        DLL Name: api-ms-win-crt-string-l1-1-0.dll
        DLL Name: api-ms-win-crt-time-l1-1-0.dll
        DLL Name: api-ms-win-crt-utility-l1-1-0.dll
        DLL Name: KERNEL32.dll
        DLL Name: libcrypto-3-x64.dll
        DLL Name: libssl-3-x64.dll
        DLL Name: x64-ucrt-ruby320.dll
```

**Comment by nathan-nhm** [comment]
* Yes, Ruby 3.2.2


```
 p:/NHM/msys64/ucrt64/bin/objdump.exe -p P:/NHM/Ruby3221a/lib/ruby/gems/3.2.0/gems/puma-6.4.0/lib/puma/puma_http1
1.so | Select-String -Pattern 'DLL Name:' | Sort-Object

        DLL Name: api-ms-win-crt-environment-l1-1-0.dll
        DLL Name: api-ms-win-crt-heap-l1-1-0.dll
        DLL Name: api-ms-win-crt-private-l1-1-0.dll
        DLL Name: api-ms-win-crt-runtime-l1-1-0.dll
        DLL Name: api-ms-win-crt-stdio-l1-1-0.dll
        DLL Name: api-ms-win-crt-string-l1-1-0.dll
        DLL Name: api-ms-win-crt-time-l1-1-0.dll
        DLL Name: api-ms-win-crt-utility-l1-1-0.dll
        DLL Name: KERNEL32.dll
        DLL Name: libcrypto-1_1-x64.dll
        DLL Name: libssl-1_1-x64.dll
        DLL Name: x64-ucrt-ruby320.dll
        
```

So if there's a difference, I'm not seeing it.

I guess then I report back when I figure out how I screwed myself up, right?

**Comment by nathan-nhm** [comment]
```
ridk exec pacman -Syuu

```
Ran twice ... how did I not recognize pacman the first time

```
ruby -vrpuma -e "puts Puma::MiniSSL::OPENSSL_LIBRARY_VERSION, Puma::MiniSSL::OPENSSL_VERSION"
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]
OpenSSL 3.1.0 14 Mar 2023
OpenSSL 3.1.4 24 Oct 2023
```
And works after being relocated now.

Lovely. Thank you so much @MSP-Greg

**Comment by MSP-Greg** [comment]
@nathan-nhm,

Checking Ruby's OpenSSL version against Puma's OpenSSL version is a good check, especially when working with MSYS2 on Windows or Homebrew on macOS.  Anytime the OpenSSL version is independent of the OS...

We have the below logging that info in our test suite.

https://github.com/puma/puma/blob/cdb23413ae375d2bf2053fe82e5a50f29bb28fd2/test/test_puma_server_ssl.rb#L19-L22
