### ISSUE TITLE
cannot load such file -- puma/minissl

### ISSUE THREAD

**Issue by ismaelga** [puma/puma#330]
Getting errors on ssl bind using

```
bind 'ssl://127.0.0.1:9292?key=server.key&cert=server.crt'
```

```
Puma starting in single mode...
* Version 2.3.2, codename: Delicious Thin Mints
* Min threads: 2, max threads: 16
* Environment: development
/Users/ismael/.gem/ruby/1.9.3/gems/backports-3.3.3/lib/backports/tools.rb:328:in `require': cannot load such file -- puma/minissl (LoadError)
    from /Users/ismael/.gem/ruby/1.9.3/gems/backports-3.3.3/lib/backports/tools.rb:328:in `require_with_backports'
    from /Users/ismael/.gem/ruby/1.9.3/gems/puma-2.3.2/lib/puma/binder.rb:125:in `block in parse'
    from /Users/ismael/.gem/ruby/1.9.3/gems/puma-2.3.2/lib/puma/binder.rb:82:in `each'
    from /Users/ismael/.gem/ruby/1.9.3/gems/puma-2.3.2/lib/puma/binder.rb:82:in `parse'
    from /Users/ismael/.gem/ruby/1.9.3/gems/puma-2.3.2/lib/puma/runner.rb:107:in `load_and_bind'
    from /Users/ismael/.gem/ruby/1.9.3/gems/puma-2.3.2/lib/puma/single.rb:62:in `run'
    from /Users/ismael/.gem/ruby/1.9.3/gems/puma-2.3.2/lib/puma/cli.rb:432:in `run'
    from /Users/ismael/.gem/ruby/1.9.3/gems/puma-2.3.2/bin/puma:10:in `<top (required)>'
    from /Users/ismael/.gem/ruby/1.9.3/bin/puma:23:in `load'
    from /Users/ismael/.gem/ruby/1.9.3/bin/puma:23:in `<main>'
```

**Comment by gonchs** [comment]
I am getting the same issue in 2.14.0

```
puma -b 'ssl://127.0.0.1:3000?key=/Users/sergey/.ssh/server.key&cert=/Users/sergey/.ssh/server.crt'
Puma starting in single mode...
* Version 2.14.0 (ruby 2.2.3-p173), codename: Fuchsia Friday
* Min threads: 0, max threads: 16
* Environment: development
/Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- puma/minissl (LoadError)
        from /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
        from /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/binder.rb:134:in `block in parse'
        from /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/binder.rb:84:in `each'
        from /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/binder.rb:84:in `parse'
        from /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/runner.rb:119:in `load_and_bind'
        from /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/single.rb:79:in `run'
        from /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.14.0/lib/puma/cli.rb:215:in `run'
        from /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/puma-2.14.0/bin/puma:10:in `<top (required)>'
        from /Users/sergey/.rbenv/versions/2.2.3/bin/puma:23:in `load'
        from /Users/sergey/.rbenv/versions/2.2.3/bin/puma:23:in `<main>'
```

**Comment by robinsingh-bw** [comment]
Still not fixed...
