### ISSUE TITLE
libev failures in CI

### ISSUE THREAD

**Issue by dentarg** [puma/puma#3478]
From https://github.com/puma/puma/issues/2905#issuecomment-2227468877

MRI: ubuntu-24.04 head

```
...
TestPumaServer#test_chunked_request_pause_before_closing_cr_lf = 1.00 s = .
(libev) epoll_wait: Invalid argument
/home/runner/work/_temp/c4e73e0b-6fe9-41df-b70c-71f351b3bb11.sh: line 1:  3160 Aborted                 (core dumped) test/runner --verbose
TestPumaServer#test_default_server_port_respects_x_forwarded_proto = 
Error: Process completed with exit code 134.
```

From https://github.com/puma/puma/actions/runs/10687994837/job/29626863117#step:10:609

MRI: macos-14 3.1

```
TestPumaServerSSL#test_ssl_v3_rejection = 0.00 s = S
(libev) kqueue kevent: Bad file descriptor
/Users/runner/work/_temp/65a5407d-3d8f-4479-b210-297713ee86bc.sh: line 1:  3906 Abort trap: 6           test/runner --verbose
TestPumaServerSSL#test_very_large_return = 
```

**Comment by dentarg** [comment]
From https://github.com/puma/puma/issues/2905#issuecomment-2227520800

> My guess is, something is closing the file descriptor while it's still in use in the event loop.

**Comment by dentarg** [comment]
We just had this fail in CI: https://github.com/puma/puma/actions/runs/10688292588/job/29627986699#step:10:970

```
/home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/socket.rb:68:in 'Socket#connect': Errno::ENOENT: No such file or directory - connect(2) for /home/runner/work/_temp/puma_socket20240903-2914-q8h9mh (Puma::SdNotify::NotifyError)
	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/socket.rb:68:in 'Addrinfo#connect_internal'
	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/socket.rb:141:in 'Addrinfo#connect'
	from /home/runner/work/puma/puma/lib/puma/sd_notify.rb:140:in 'Puma::SdNotify.notify'
	from /home/runner/work/puma/puma/lib/puma/sd_notify.rb:57:in 'Puma::SdNotify.reloading'
	from /home/runner/work/puma/puma/lib/puma/plugin/systemd.rb:19:in 'block in start'
	from /home/runner/work/puma/puma/lib/puma/events.rb:17:in 'block in Puma::Events#fire'
	from <internal:array>:53:in 'Array#each'
	from /home/runner/work/puma/puma/lib/puma/events.rb:17:in 'Puma::Events#fire'
	from /home/runner/work/puma/puma/lib/puma/events.rb:50:in 'Puma::Events#fire_on_restart!'
	from /home/runner/work/puma/puma/lib/puma/launcher.rb:283:in 'Puma::Launcher#restart!'
	from /home/runner/work/puma/puma/lib/puma/launcher.rb:279:in 'Puma::Launcher#do_restart'
	from /home/runner/work/puma/puma/lib/puma/launcher.rb:259:in 'Puma::Launcher#do_run_finished'
	from /home/runner/work/puma/puma/lib/puma/launcher.rb:196:in 'Puma::Launcher#run'
	from /home/runner/work/puma/puma/lib/puma/cli.rb:75:in 'Puma::CLI#run'
	from /home/runner/work/puma/puma/bin/puma:10:in '<main>'
/home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/socket.rb:68:in 'Socket#connect': No such file or directory - connect(2) for /home/runner/work/_temp/puma_socket20240903-2914-q8h9mh (Errno::ENOENT)
	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/socket.rb:68:in 'Addrinfo#connect_internal'
	from /home/runner/.rubies/ruby-head/lib/ruby/3.4.0+0/socket.rb:141:in 'Addrinfo#connect'
	from /home/runner/work/puma/puma/lib/puma/sd_notify.rb:140:in 'Puma::SdNotify.notify'
	from /home/runner/work/puma/puma/lib/puma/sd_notify.rb:57:in 'Puma::SdNotify.reloading'
	from /home/runner/work/puma/puma/lib/puma/plugin/systemd.rb:19:in 'block in start'
	from /home/runner/work/puma/puma/lib/puma/events.rb:17:in 'block in Puma::Events#fire'
	from <internal:array>:53:in 'Array#each'
	from /home/runner/work/puma/puma/lib/puma/events.rb:17:in 'Puma::Events#fire'
	from /home/runner/work/puma/puma/lib/puma/events.rb:50:in 'Puma::Events#fire_on_restart!'
	from /home/runner/work/puma/puma/lib/puma/launcher.rb:283:in 'Puma::Launcher#restart!'
	from /home/runner/work/puma/puma/lib/puma/launcher.rb:279:in 'Puma::Launcher#do_restart'
	from /home/runner/work/puma/puma/lib/puma/launcher.rb:259:in 'Puma::Launcher#do_run_finished'
	from /home/runner/work/puma/puma/lib/puma/launcher.rb:196:in 'Puma::Launcher#run'
	from /home/runner/work/puma/puma/lib/puma/cli.rb:75:in 'Puma::CLI#run'
	from /home/runner/work/puma/puma/bin/puma:10:in '<main>'
```

This is the code creating that "socket" file in the test `setup` (and removing it in `teardown`) https://github.com/puma/puma/blob/796d8c6af139a22e29e57e156c05c66ed3082634/test/test_plugin_systemd.rb#L20-L35

I don't see how we are doing something wrong here.

Are temporary files removed by the OS during Puma CI runs?

**Comment by MSP-Greg** [comment]
Re the branch, see https://github.com/MSP-Greg/puma/actions/workflows/tests.yml?query=branch%3A00-aa-test-1

The only failure was a TruffleRuby job that passed, but just missed the 8 minute timeout...

**Comment by dentarg** [comment]
> This is the systemd notify socket, so it probably isn't the same issue as libev failures.
> 
> The teardown code might be amiss, as the server might still be shutting down when the socket is removed.

and the systemd integration is trying to send stuff on the socket when the server is shutting down?

**Comment by MSP-Greg** [comment]
>  the systemd integration is trying to send stuff on the socket when the server is shutting down

Not totally sure, but the test seems stable after I removed the test file's teardown.  The intermittent failures are messy.  Parallel tests run in threads, and blocking can be an issue, along with multi VM CI runners (noisy neighbors).

**Comment by dentarg** [comment]
Happened for the `ubuntu-22.04 3.2 rack2` job for https://github.com/puma/puma/pull/3589, log at https://github.com/puma/puma/actions/runs/12580493902/job/35062661418#step:10:444

```
(libev) epoll_wait: Invalid argument
/home/runner/work/_temp/6b5de6c8-8475-45ca-9362-076205407f49.sh: line 1:  2686 Aborted                 (core dumped) test/runner --verbose
```

**Comment by nateberkopec** [comment]
Man, I am so thankful we have the two of you constantly working on our CI because you couldn't pay me to get near this stuff.

@MSP-Greg would it be helpful if we had our own runners? @speedshop can sponsor. I'm going to set some up soon anyway for our own purposes.
