### ISSUE TITLE
Puma version 2.4.1 and SSL

### ISSUE THREAD

**Issue by thukim** [puma/puma#350]
The latest version of Puma (`2.4.1`) seems not to support SSL well. When I run 

`puma -b 'ssl://127.0.0.1:9292?key=path_to_key&cert=path_to_cert'`

and went to `https://localhost:9292` : at first, the server did not respond (it took very long time, more than half an hour to load but no data received). Then when I reloaded the page, I got this problem:

```
Puma starting in single mode...
* Version 2.4.1, codename: Crunchy Munchy Lunchy
* Min threads: 0, max threads: 16
* Environment: development
* Listening on ssl://127.0.0.1:9292?key=path_to_key&cert=path_to_cert
Use Ctrl-C to stop
127.0.0.1 - - [08/Aug/2013 14:58:05] "GET / HTTP/1.1" 200 - 2.8474
2013-08-08 14:58:05 +0700: Read error: #<Errno::EPIPE: Broken pipe>
/var/lib/gems/1.9.1/gems/puma-2.4.1/lib/puma/minissl.rb:56:in `write'
/var/lib/gems/1.9.1/gems/puma-2.4.1/lib/puma/minissl.rb:56:in `write'
/var/lib/gems/1.9.1/gems/puma-2.4.1/lib/puma/server.rb:758:in `fast_write'
/var/lib/gems/1.9.1/gems/puma-2.4.1/lib/puma/server.rb:585:in `handle_request'
/var/lib/gems/1.9.1/gems/puma-2.4.1/lib/puma/server.rb:343:in `process_client'
/var/lib/gems/1.9.1/gems/puma-2.4.1/lib/puma/server.rb:242:in `block in run'
/var/lib/gems/1.9.1/gems/puma-2.4.1/lib/puma/thread_pool.rb:92:in `call'
/var/lib/gems/1.9.1/gems/puma-2.4.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread
```

I reverted Puma gem to various versions from `2.0.0` to `2.4.0` but that did not solve the problem. However, reverting to v1.6.3 fixes it.

**Comment by Sultan91** [comment]
Same problem

**Comment by dentarg** [comment]
@Sultan91 please open new issue where you describe how to reproduce the problem
