### ISSUE TITLE
"Too many open files" when running tests locally

### ISSUE THREAD

**Issue by jjb** [puma/puma#3516]
this is solved with `ulimit -n 4000` in the shell - maybe could go into the test runner

----

<img width="958" alt="iTerm2 2024-10-11 17 51 09" src="https://github.com/user-attachments/assets/dee1652b-2132-45a6-8809-1635746db4d2">

```
  1) Error:
TestIntegrationCluster#test_puma_debug_loaded_exts:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:533:in `test_puma_debug_loaded_exts'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

  2) Error:
TestIntegrationCluster#test_fork_worker_spawn:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:326:in `test_fork_worker_spawn'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

  3) Error:
TestIntegrationCluster#test_usr1_all_respond_unix:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:629:in `usr1_all_respond'
    test/test_integration_cluster.rb:117:in `test_usr1_all_respond_unix'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

  4) Error:
TestIntegrationCluster#test_json_gem_not_required_in_master_process:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:387:in `test_json_gem_not_required_in_master_process'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

  5) Error:
TestIntegrationCluster#test_fork_worker_phased_restart_with_high_worker_count:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:342:in `test_fork_worker_phased_restart_with_high_worker_count'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

  6) Error:
TestIntegrationCluster#test_usr1_fork_worker:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:629:in `usr1_all_respond'
    test/test_integration_cluster.rb:112:in `test_usr1_fork_worker'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

  7) Error:
TestIntegrationCluster#test_worker_boot_timeout:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:543:in `worker_timeout'
    test/test_integration_cluster.rb:237:in `test_worker_boot_timeout'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

  8) Error:
TestIntegrationCluster#test_pre_existing_unix_stop_after_restart:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:53:in `test_pre_existing_unix_stop_after_restart'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

  9) Error:
TestIntegrationCluster#test_pre_existing_unix:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:36:in `test_pre_existing_unix'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 10) Error:
TestIntegrationCluster#test_culling_strategy_youngest:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:449:in `test_culling_strategy_youngest'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 11) Error:
TestIntegrationCluster#test_warning_message_not_outputted_when_single_worker_silenced:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:424:in `test_warning_message_not_outputted_when_single_worker_silenced'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 12) Error:
TestIntegrationCluster#test_load_path_includes_extra_deps:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:371:in `test_load_path_includes_extra_deps'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 13) Error:
TestIntegrationCluster#test_worker_index_is_with_in_options_limit:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:276:in `test_worker_index_is_with_in_options_limit'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 14) Error:
TestIntegrationCluster#test_term_exit_code:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:123:in `test_term_exit_code'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 15) Error:
TestIntegrationCluster#test_stuck_phased_restart:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:680:in `worker_respawn'
    test/test_integration_cluster.rb:212:in `test_stuck_phased_restart'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 16) Error:
TestIntegrationCluster#test_siginfo_thread_print:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:71:in `test_siginfo_thread_print'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 17) Error:
TestIntegrationCluster#test_nio4r_gem_not_required_in_master_process:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:393:in `test_nio4r_gem_not_required_in_master_process'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 18) Error:
TestIntegrationCluster#test_on_booted_and_on_stopped:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:141:in `test_on_booted_and_on_stopped'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 19) Error:
TestIntegrationCluster#test_load_path_does_not_include_nio4r:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:377:in `test_load_path_does_not_include_nio4r'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 20) Error:
TestIntegrationCluster#test_worker_hook_warning_web_concurrency:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:519:in `test_worker_hook_warning_web_concurrency'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 21) Error:
TestIntegrationCluster#test_nio4r_gem_not_required_in_master_process_when_using_control_server:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:401:in `test_nio4r_gem_not_required_in_master_process_when_using_control_server'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 22) Error:
TestIntegrationCluster#test_culling_strategy_oldest_fork_worker:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:475:in `test_culling_strategy_oldest_fork_worker'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 23) Error:
TestIntegrationCluster#test_application_is_loaded_exactly_once_if_using_preload_app:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:409:in `test_application_is_loaded_exactly_once_if_using_preload_app'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 24) Error:
TestIntegrationCluster#test_idle_timeout:
Errno::EMFILE: Too many open files - /Users/john-healthie/.rbenv/versions/3.3.5/bin/ruby
    test/helpers/integration.rb:115:in `popen'
    test/helpers/integration.rb:115:in `cli_server'
    test/test_integration_cluster.rb:257:in `test_idle_timeout'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

 25) Error:
TestIntegrationCluster#test_fork_worker_on_refork:
Errno::EMFILE: Too many open files - socket(2) for "127.0.0.1" port 61823
    test/helpers/integration.rb:235:in `initialize'
    test/helpers/integration.rb:235:in `new'
    test/helpers/integration.rb:235:in `fast_connect'
    test/test_integration_cluster.rb:311:in `test_fork_worker_on_refork'
    test/helper.rb:125:in `block (3 levels) in run'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
    /Users/john-healthie/.rbenv/versions/3.3.5/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
    test/helper.rb:123:in `block (2 levels) in run'

677 runs, 1850 assertions, 0 failures, 25 errors, 15 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1)
/Users/john-healthie/.rbenv/versions/3.3.5/bin/bundle:25:in `load'
/Users/john-healthie/.rbenv/versions/3.3.5/bin/bundle:25:in `<main>'
Tasks: TOP => default => test:all => test
(See full trace by running task with --trace)
```

**Comment by dentarg** [comment]
It is documented at https://github.com/puma/puma/blob/a59afabe782ec8869bb709ca991b32c0b2cc95fd/CONTRIBUTING.md#file-limits

Not sure about raising the limit automatically, I think there's a limit in operating systems for a reason?

**Comment by jjb** [comment]
> I think there's a limit in operating systems for a reason?

sure but i believe 100% of devs on macos will encounter this and then need to manually change it. maybe most people do in one project or another and then sets it in their shell config? seems to be common to set it in one's shell config, i think i have done it in the past.

so i think if the solution is that everyone is setting it in their shell config, and all macos devs _have to_ do that or set it manually per session, maybe setting it in the test runner is warranted.

**Comment by dentarg** [comment]
Yeah, might be warranted to do that... but I'm not sure it would work? I think it is too late when `test/runner` has started, that is the Ruby process. Maybe a comment in the runner is the best we can do.
