### ISSUE TITLE
No need for `Puma::NullIO` if Rack 3.1 is used?

### ISSUE THREAD

**Issue by dentarg** [puma/puma#3523]
I just merged https://github.com/puma/puma/pull/3214 that links to https://github.com/rack/rack/pull/2115

At https://github.com/rack/rack/pull/2115#issuecomment-1694807254 @ioquatix mentions

> In Rack 3.1+ you should stop using `Puma::NullIO`

How should we go about this?

**Comment by ioquatix** [comment]
Just don't set it at all if there is no input body.

**Comment by MSP-Greg** [comment]
@ioquatix

Dumb question, I don't want to switch gears to...

Off the top of your head, will that work with older versions of Rack?  I haven't run our test suite with the change, not sure if our coverage of Rack versions is deep enough.

**Comment by ioquatix** [comment]
No it is only valid for Rack 3.1+ applications. As a server, you can either be aggressive or conservative with what you give to applications. However, the Rack spec < 3.1 would fail such a request.

Therefore, I suppose you should sniff the Rack version in order to determine the best course of action - i.e. the application has loaded Rack 3.1 and thus works within that version of the spec.

**Comment by dentarg** [comment]
Sounds like a breaking change for Puma? Should we do this in Puma v7?

**Comment by ioquatix** [comment]
I think that would be reasonable, i.e. `(PUMA_VERSION >= 7 && RACK_VERSION >= 3.1)`.

**Comment by ioquatix** [comment]
https://github.com/socketry/protocol-rack/commit/33e53751e6fedf7106dfefe074101657ad9645da#diff-69a86ecb7fecec382d7f5e1d1993891087e1cae64486233660e1a59646e77a68R55-R61

**Comment by dentarg** [comment]
Hmm, what is the reason for not setting `rack.input` to `Puma::NullIO` when there's no body in the request? Reading https://github.com/rack/rack/pull/2115 it seem like the issue was `Puma::NullIO` not responding to `#set_encoding`.

I think Puma using `Puma::NullIO` is a good thing? I think changing this would cause more problems than it would solve, even if done in a major version.

Here's my app, using rack 3.1.8.

```ruby
$ cat config.ru
# frozen_string_literal: true

$stdout.sync = true
$stderr.sync = true

require "rack"

def try
  yield
rescue StandardError => e
  puts e.full_message
end


app = lambda do |env|
  request = Rack::Request.new(env)

  puts "request.body=#{request.body.inspect}"
  puts "rack.input=#{env['rack.input'].inspect}"

  try { puts "request.body=#{request.body.read.inspect}" }
  try { puts "rack.input=#{env['rack.input'].read.inspect}" }

  [200, {}, ["OK"]]
end

run app
```

I'm making this request: `curl localhost:8000`

Here is Puma 6.4.3 running it:

```shell
$ bundle e puma -p 8000
Puma starting in single mode...
* Puma version: 6.4.3 (ruby 3.3.5-p100) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 33072
* Listening on http://0.0.0.0:8000
Use Ctrl-C to stop

request.body=#<Puma::NullIO:0x0000000104d31850>
rack.input=#<Puma::NullIO:0x0000000104d31850>
request.body=""
rack.input=""
```

Here's Falcon 0.48.3 running it:

```shell
$ bundle e falcon -p 8000 --bind http://
  0.0s     info: Falcon::Command::Serve [oid=0x7d0] [ec=0x7e4] [pid=33591] [2024-11-21 17:19:12 +0100]
               | Falcon v0.48.3 taking flight! Using Async::Container::Forked {:count=>12, :restart=>true}.
               | - Binding to: #<Falcon::Endpoint http://:8000/ {:port=>8000}>
               | - To terminate: Ctrl-C or kill 33591
               | - To reload configuration: kill -HUP 33591
 0.01s     info: Falcon::Service::Server [oid=0x80c] [ec=0x7e4] [pid=33591] [2024-11-21 17:19:12 +0100]
               | Starting server on #<Falcon::Endpoint http://:8000/ {:port=>8000}>
request.body=nil
rack.input=nil
config.ru:21:in `block (4 levels) in <top (required)>': undefined method `read' for nil (NoMethodError)
	from config.ru:9:in `try'
	from config.ru:21:in `block (3 levels) in <top (required)>'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/protocol-rack-0.11.0/lib/protocol/rack/adapter/generic.rb:110:in `call'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/protocol-http-0.44.0/lib/protocol/http/middleware.rb:43:in `call'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/protocol-http-0.44.0/lib/protocol/http/content_encoding.rb:29:in `call'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/protocol-http-0.44.0/lib/protocol/http/middleware.rb:43:in `call'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/async-http-0.83.1/lib/async/http/server.rb:58:in `block in accept'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/async-http-0.83.1/lib/async/http/protocol/http1/server.rb:71:in `each'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/async-http-0.83.1/lib/async/http/server.rb:50:in `accept'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/io-endpoint-0.14.0/lib/io/endpoint/wrapper.rb:182:in `block (2 levels) in accept'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/async-2.21.0/lib/async/task.rb:197:in `block in run'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/async-2.21.0/lib/async/task.rb:435:in `block in schedule'
config.ru:22:in `block (4 levels) in <top (required)>': undefined method `read' for nil (NoMethodError)
	from config.ru:9:in `try'
	from config.ru:22:in `block (3 levels) in <top (required)>'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/protocol-rack-0.11.0/lib/protocol/rack/adapter/generic.rb:110:in `call'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/protocol-http-0.44.0/lib/protocol/http/middleware.rb:43:in `call'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/protocol-http-0.44.0/lib/protocol/http/content_encoding.rb:29:in `call'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/protocol-http-0.44.0/lib/protocol/http/middleware.rb:43:in `call'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/async-http-0.83.1/lib/async/http/server.rb:58:in `block in accept'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/async-http-0.83.1/lib/async/http/protocol/http1/server.rb:71:in `each'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/async-http-0.83.1/lib/async/http/server.rb:50:in `accept'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/io-endpoint-0.14.0/lib/io/endpoint/wrapper.rb:182:in `block (2 levels) in accept'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/async-2.21.0/lib/async/task.rb:197:in `block in run'
	from /Users/dentarg/.arm64_rubies/3.3.5/lib/ruby/gems/3.3.0/gems/async-2.21.0/lib/async/task.rb:435:in `block in schedule'
```

**Comment by ioquatix** [comment]
The reason is to make it easier for code which deals with input to know it can bail earlier, e.g. the multi-part parser: https://github.com/rack/rack/commit/54368a0981c46c2c62137e47795b38de50dabefb#diff-7404531728e9194974263579fc1b939066d457000ec901206b49ced795df9babL18

It's also unclear in the puma case whether the input was empty, or not provided at all.

The spec doesn't force you to not use `Puma::NullIO`, but it allows for it, which I think is fine. You can decide what makes sense for your server (or make it configurable).

**Comment by schneems** [comment]
I had no opinions on `Puma::NullIO` before, and I'm not sure I have strong opinions now. I can see an argument to be made for not having to play method whack-a-mole to add things like `set_encoding`. It also might be difficult to correctly predict what the behavior of a "null" object like NullIO should be on all of future method additions. I can see a value to always having a "readable" `rack.input`. So downstream doesn't have to special case the difference betwen empty and `nil`. 

Is there any way to gauge or quantify who all is relying on that behavior? What if we make `NullIO#read` print a warning saying it's going away, requesting people provide feedback to a discussion URL for them to describe how/why they're using it. If we get a lot of hits, then maybe we keep it but make it configurable. Depending on the feedback we could default to it on or off. Or we could still decide to remove it altogether. WDYT?

Anyone interested in (at minimum) driving a PR to add a warning?

**Comment by ioquatix** [comment]
Using `NullIO` is objectively worse when you want to bail on parsing input. The difference is between "There was no input body" vs "There was an empty input body". The latter is not possible to detect until you try to read. My advice is the same as what I said earlier.

> I think Puma using `Puma::NullIO` is a good thing

No it's not.

**Comment by dentarg** [comment]
Why was `NullIO` introduced in the first place? Anyone know the history behind it?

**Comment by dentarg** [comment]
If we remove `NullIO`, all apps wanting to read the body needs to check for `nil` before doing so?

**Comment by ioquatix** [comment]
> Why was NullIO introduced in the first place? Anyone know the history behind it?

Rack did not allow `rack.input` to be `nil` and instead required `read` to be empty/nil on the first operation. But it makes it impossible to distinguish between no input and empty input (which **is** distinct in HTTP). In Rack 3.1, it is acceptable not to specify `rack.input` if there is no input.

- https://github.com/rack/rack/pull/2018
- https://github.com/rack/rack/pull/2259

**Comment by dentarg** [comment]
I think we should make the behavior configurable. I think lots of apps would start to see nil errors on read if we just changed it. Please correct me if this sounds wrong.

**Comment by schneems** [comment]
> Why was NullIO introduced in the first place? Anyone know the history behind it?

I'm sitting on a chesterton's fence on this one. I was curious so I git-blamed

- NullIO class added in https://github.com/puma/puma/commit/bcdd5357fb8796aad1f0ac9d7a80b03f175e0411 (changed 2011). Prior to that it was `EmptyBinary`
- Prior to that constant it was an empty string https://github.com/puma/puma/commit/5f392b3e1386d9a4ee33951f3c9ab734285bacd6 (changed to constant in 2011).
- Behavior added in 2011 in https://github.com/puma/puma/commit/220c4aae1c2dacdd324cc5a9548410bc791cdb6f. Prior to that looks like it would bail instead of setting `rack.input` to nil. That commit isn't very helpful it says "Handle not exposing the next request to the last one." Though "Rack did not allow rack.input to be nil and instead required read to be empty/nil on the first operation." holds up. 

So sounds like Pre 3.1 spec it was required. After 3.1 it sounds like it's actively discouraged. We still support Rack 2.2 so it cannot be removed wholesale. It would need to be a gated change.

> I think we should make the behavior configurable.

Eventually instead of making it configurable in Puma, we could say "if you want this, add this middleware that checks for nil `rack.input` and sets it to a StringIO". But in the short term, I think this would need a deprecation cycle:

- Make a `Puma::NullIO` object called `Puma::DeprecatedNullIO` that prints a deprecation warning on every method call.

> Warning: `rack.input` came from an empty body. A temporary "null" object has been placed there instead. In the future you must explicitly check if this value is `nil` before using it. If you're already checking for that condition, set `nil_rack_input_on_empty_body = true` in your Puma config.

- Release a version with that
- In a major bump, remove the behavior and default to using `nil` instead of the NullIO object. Add an error to anyone setting `nil_rack_input_on_empty_body = false` telling them to inject a custom middleware instead.

We don't need to gate adding a deprecation warning on a major version (IMHO), so that sketch can be decoupled from `v7`.
