### ISSUE TITLE
Invalid request is swallowed and times out

### ISSUE THREAD

**Issue by utay** [puma/puma#3552]
**Describe the bug**

It seems like there's a bug in this optimization where after handling a request it tries to read the next request from the socket:
https://github.com/puma/puma/blob/v6.4.3/lib/puma/server.rb#L475-L486.

In this [code](https://github.com/puma/puma/blob/v6.4.3/lib/puma/client.rb#L186-L192) specifically:
```ruby
        begin
          if fast_check && @to_io.wait_readable(FAST_TRACK_KA_TIMEOUT)
            return try_to_finish
          end
        rescue IOError
          # swallow it
        end
```

If the request parsing fails, `try_to_finish` raises a `Puma::HttpParserError` which inherits `IOError` and it causes the invalid request to be swallowed and to time out after 20 seconds.

**To Reproduce**

Copy this into a file called `hello.ru`:
```
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

Run it with:
```
bundle exec puma hello.ru
```

Run this curl command:
```
curl -v --keepalive-time 30 "http://localhost:9292" --next "http://localhost:9292/$(printf 'a%.0s' {1..9000})"
```

This will send 2 requests sequentially in the same TCP connection:
- The first request succeeds with status code 200
- The second request is invalid - its path is longer than the allowed length (8192) - it hangs for 20 seconds and then the connection dies :boom: 

**Expected behavior**

The second request should return 400 immediately with the following error:
```
HTTP parse error, malformed request ("GET " - (-)): #<Puma::HttpParserError: HTTP element REQUEST_PATH is longer than the (8192) allowed length (was 9001)>
```

**Desktop (please complete the following information):**
 
 - Puma Version 6.4.3

**Comment by joshuay03** [comment]
@MSP-Greg Can this be closed seeing as https://github.com/puma/puma/pull/3553 has been released?

**Comment by dentarg** [comment]
@joshuay03 that PR only changed tests

but now we have https://github.com/puma/puma/pull/3590 that addresses this

**Comment by dentarg** [comment]
@utay are you able to share any context how you encountered this bug? 

I'm curious, seeing Puma has had this behavior for a long time according to the PR that addressed this. :-)

**Comment by MSP-Greg** [comment]
As to how to repro the issue...

If one sets a local repo/fork to master, and open or save `test_request_invalid.rb`, then checkout 59dd65e50e7c, compile, then save  `test_request_invalid.rb` back into the repo, then runs the test file, two tests timeout as below:
```text
  1) Error:
TestRequestInvalid#test_content_length_bad_characters_1_keep_alive:
Timeout::Error: Client Read Timeout
    test/helpers/test_puma/puma_socket.rb:279:in 'block (2 levels) in <module:PumaSocket>'
    <internal:kernel>:168:in 'Kernel#loop'
    test/helpers/test_puma/puma_socket.rb:225:in 'block in <module:PumaSocket>'
    test/test_request_invalid.rb:83:in 'TestRequestInvalid#assert_status'
    test/test_request_invalid.rb:157:in 'TestRequestInvalid#test_content_length_bad_characters_1_keep_alive'
    test/helper.rb:131:in 'block (3 levels) in TimeoutEveryTestCase#run'
    /usr/local/lib/ruby/3.5.0+0/timeout.rb:185:in 'block in Timeout.timeout'
    /usr/local/lib/ruby/3.5.0+0/timeout.rb:192:in 'Timeout.timeout'
    test/helper.rb:129:in 'block (2 levels) in TimeoutEveryTestCase#run'

  2) Error:
TestRequestInvalid#test_oversize_path_keep_alive:
Timeout::Error: Client Read Timeout
    test/helpers/test_puma/puma_socket.rb:279:in 'block (2 levels) in <module:PumaSocket>'
    <internal:kernel>:168:in 'Kernel#loop'
    test/helpers/test_puma/puma_socket.rb:225:in 'block in <module:PumaSocket>'
    test/test_request_invalid.rb:83:in 'TestRequestInvalid#assert_status'
    test/test_request_invalid.rb:118:in 'TestRequestInvalid#test_oversize_path_keep_alive'
    test/helper.rb:131:in 'block (3 levels) in TimeoutEveryTestCase#run'
    /usr/local/lib/ruby/3.5.0+0/timeout.rb:185:in 'block in Timeout.timeout'
    /usr/local/lib/ruby/3.5.0+0/timeout.rb:192:in 'Timeout.timeout'
    test/helper.rb:129:in 'block (2 levels) in TimeoutEveryTestCase#run'
```

You need to compile after the checkout, as the most recent commit in master changes the extension code.

**Comment by utay** [comment]
> @utay are you able to share any context how you encountered this bug?

> I'm curious, seeing Puma has had this behavior for a long time according to the PR that addressed this. :-)

@dentarg Some bots were hitting our API endpoint with very long paths or unconventional characters like `"` in path, which triggered our load balancer 5XX monitoring. It took us some time to identify the issue as we couldn't consistently reproduce since the requests needed to be sent over the same connection; we could reproduce only in staging/production (where we have a load balancer), not locally, so this led us to the same connection hypothesis and then we added logs down the stack until we found the bug!

@MSP-Greg Thank you for the fix :pray:

**Comment by MSP-Greg** [comment]
@utay

First of all, sorry for the delay with this.  Above, I stated:
> I should have a PR finished today or tomorrow

That was my original intent, but the rabbit hole kept getting deeper and deeper. Issues with HttpParser error handling also led to #3582 and #3586.

> has had this behavior for a long time

I didn't really want to imply any blame for this.

What happened a long time ago was giving special treatment to requests on a keep-alive connection that follow after the first.  

Those requests had a different code path.  That causes the 'long-tail' response problem, and also has slightly different error handling, which causes the issue here.

Also, regarding keep-alive connections (along with pipelined requests), once a request is considered invalid, it may be impossible to determine the 'end' of the invalid request.  This may cause the parser to throw subsequent errors when it tries to parse an additional request.  Because of these issues, the above PR's close the connection when an invalid request is received.

Lastly, this gets messy in the real world, especially when grey areas of RFC's are taken into account (e.g. https://github.com/rack/rack/pull/2273).

**Comment by ronkorving** [comment]
Was this bug introduced in 6.4.3? Or was that just the version tested?

**Comment by dentarg** [comment]
Tested. See https://github.com/puma/puma/pull/3590
