### ISSUE TITLE
Rails emits a "FATAL" level log when Puma opens a thread (Rails 5 / JRuby)

### ISSUE THREAD

**Issue by Fosfen** [puma/puma#3574]
Hello !
I'm sorry if the issue I'm encountering isn't related to Puma, I struggle to find the its source.

Since Rails 5.2, in deployed apps, when a user accesses one of the Rails routes, an emergency log is emitted.
It doesn't break anything and the app works as intended. However, since a lot of logs are emitted, it rises the cost of the logger solution and flood / block the monitors that are set up.

Versions of used gems:

Rails 5.2.8.1
JRuby 9.3.15.0 (Ruby 2.6.8)
Puma 6.5.0

These logs weren't emitted with Rails 4.

```
actionpack (5.2.8.1) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.8.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
lograge (0.11.0) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (5.2.8.1) lib/rails/rack/logger.rb:28:in `call'
actionpack (5.2.8.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.8.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.9) lib/rack/method_override.rb:24:in `call'
rack (2.2.9) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.8.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.8.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.8.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.9) lib/rack/sendfile.rb:110:in `call'
rack-cors (1.0.3) lib/rack/cors.rb:95:in `call'
ddtrace (1.14.0) lib/datadog/appsec/contrib/rack/request_middleware.rb:60:in `block in call'
ddtrace (1.14.0) lib/datadog/appsec/instrumentation/gateway.rb:37:in `block in push'
ddtrace (1.14.0) lib/datadog/appsec/contrib/rack/gateway/watcher.rb:56:in `block in watch_request'
ddtrace (1.14.0) lib/datadog/appsec/instrumentation/gateway.rb:19:in `call'
ddtrace (1.14.0) lib/datadog/appsec/instrumentation/gateway.rb:43:in `block in push'
ddtrace (1.14.0) lib/datadog/appsec/instrumentation/gateway.rb:47:in `push'
ddtrace (1.14.0) lib/datadog/appsec/contrib/rack/request_middleware.rb:59:in `block in call'
org/jruby/RubyKernel.java:1238:in `catch'
ddtrace (1.14.0) lib/datadog/appsec/contrib/rack/request_middleware.rb:58:in `call'
sentry-raven (3.1.0) lib/raven/integrations/rack.rb:51:in `call'
ddtrace (1.14.0) lib/datadog/tracing/contrib/rack/middlewares.rb:102:in `call'
railties (5.2.8.1) lib/rails/engine.rb:524:in `call'
org/jruby/RubyKernel.java:2009:in `public_send'
railties (5.2.8.1) lib/rails/railtie.rb:190:in `method_missing'
puma-6.5.0 (java) lib/puma/configuration.rb:279:in `call'
puma-6.5.0 (java) lib/puma/request.rb:99:in `block in handle_request'
puma-6.5.0 (java) lib/puma/thread_pool.rb:389:in `with_force_shutdown'
puma-6.5.0 (java) lib/puma/request.rb:98:in `handle_request'
puma-6.5.0 (java) lib/puma/server.rb:468:in `process_client'
puma-6.5.0 (java) lib/puma/server.rb:249:in `block in run'
puma-6.5.0 (java) lib/puma/thread_pool.rb:166:in `block in spawn_thread'
logging (2.2.2) lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

My question so far is: is there a chance that the problem is related to Puma ? It seems that the stack trace goes back to the Puma `spawn_thread` method, up until JRuby.

**Comment by dentarg** [comment]
The stack trace always starts with Puma. If it doesn't end with Puma, it is not related to Puma.

You should look into what changed between Rails 4 and 5 and how it relates to your application.

**Comment by Fosfen** [comment]
> The stack trace always starts with Puma. If it doesn't end with Puma, it is not related to Puma.
> 
> You should look into what changed between Rails 4 and 5 and how it relates to your application.

Got it, thank you I'll close the issue then and I'll start seeking into Rails change. Thanks !
