### ISSUE TITLE
Puma not restarting (or at least not loading new current) when notified with SIGUSR2

### ISSUE THREAD

**Issue by gamafranco** [puma/puma#416]
When my  cap deploys,  it sends a SIGUSR2 to Puma - tried manually with kill and with pumactl.

pumactl says the server will restart, but puma doesn't run the new code (the message is ' Command restart sent success').

To get the new code served, puma needs an hard restart (i.e. need to send it a SIGINT and then start).

I can't confirm if with SIGUSR2 puma doesn't restart or simply doesn't change working directory - as there is a new deploy. What is clear is that it keeps running the old code.

Setup is ubuntu 12.04, rails 4 and Ruby 1.9.3. Puma is 2.6.0.

Thanks.

**Comment by mcfadden** [comment]
I'm seeing this same issue as well (phased restart doesn't load new code)

Running Puma 2.11.2  on Ruby 2.2.2

We're deploying with Capistrano.

Here's my puma.rb:

    workers 2
    threads 5, 5

    prune_bundler

    rackup      DefaultRackup
    environment production

    directory '/www/my-app/current'
    bind "unix:///var/run/puma.sock"
    state_path "/var/run/puma.state"
    pidfile "/var/run/puma.pid"

We're issuing this command to start the phased restart:

    sudo pumactl --config-file /www/my-app/current/config/puma.rb phased-restart

When we issue the phased-restart the worker processes do restart (new PIDs), but they don't get the new code.

Where should I look for more information to figure out what's happening?

**Comment by mcfadden** [comment]
After coming back to this on a fresh day, I'm really not sure what I was experiencing. At one point in time my restarts definitely weren't working properly (as in, the new code definitely wasn't being loaded). This could have easily been a misconfiguration on my part.

After I noticed the problem I started testing by looking at the output from `ps aux` which included the directory it had loaded in the tag. Ex:

    puma: cluster worker 1: 918 [20150429172950]

When I was deploying new code I could see that worker restart, but the content loaded (`20150429172950`) wasn't changing, so I assumed it still wasn't loading the new code. I have no idea what I did to fix it, but it's loading the new code properly (with the configuration in my previous comment).

Perhaps I should open a new issue about updating the Process tag on the workers to match the new directory.

At the moment I'm not even sure where it's pulling the current release from since i'm running this out of the `/www/my-app/current` directory.

**Comment by Epigene** [comment]
To my surprise, I got this to work.

Using puma v2.15.3

```ruby
# in /config/puma.rb
app = "my_app"
root = "/home/deployer/apps/#{app}"

workers  4
threads  1, 2

rackup      DefaultRackup
environment ENV['RAILS_ENV']
daemonize   true

directory "#{root}/current"
pidfile "#{root}/shared/tmp/pids/puma.pid"
stdout_redirect "#{root}/shared/log/#{Time.now.to_i}_production.log", "#{root}/shared/log/#{Time.now.to_i}_production_errors.log"
bind "unix:/tmp/puma.socket"

prune_bundler
```

It is crucial to stop and start puma with these settings to have the master process pick up :directory and, possibly, :prune_bundler directives.

Then you can `bundle exec pumactl -p {pid_path} phased-restart`

__NB__, that it may take a few moments for workers to pick up the new code, and also `ps aux` will incorrectly output workers' directory as the master processes' original directory, when the new code will actually be taken from the new symlinked current folder.

**Comment by treenewbee** [comment]
This issue seems to recur in 3.9.0 and 3.9.1. 

3.8.2 works totally fine.

**Comment by pavelvasev** [comment]
In our case [ruby 2.3.3p222]
```
puma (3.10.0)
puma_worker_killer (0.1.0)
```
Puma reloads ok on SIGUSR2 and doesn't reload on SIGUSR1.

It feels like preload_app gets automatically turned on somehow.

**Comment by bf4** [comment]
This may be related, using `prune_bundler` and SIGUSR2 via foreman

Just observed something interesting using puma's phased restarts, old code was running against new code in the same process.... I think it has to do with how long it takes for our app code to load, about 3-4 seconds, then boot, about  6-7 seconds

```
03/27/2017 11:17:19.000 -0500	 
  [32187] - Starting phased worker restart, phase: 4
  [32187] + Changing to /srv/rails_server
03/27/2017 11:17:20.000 -0500
  [32187] - Stopping 22094 for phased upgrade...
  [32187] - TERM sent to 22094...
  [1292] + Gemfile in context: /srv/rails_server/Gemfile

timestamp=2017-03-27T16:17:23Z env=production frontend=www level=error thread_id=9400300 
  got a  NoMethodError on a model that a had that method added in the new code

timestamp=2017-03-27T16:17:23Z env=production frontend=www level=info thread_id=9400300 
  next request is the same controller and method, but works

03/27/2017 11:17:33.000 -0500	
[32187] - Worker 0 (pid: 1292) booted, phase: 4
			   
timestamp=2017-03-27T16:17:33Z env=production frontend=www level=info thread_id=7420240  tag=rails message={"app_info":{"pid":1292,"load_time":"4.446515 seconds","boot_time":"7.682576 seconds","config":{"mysql":{"pool":64},"pg":{"pool":64},"dm":{"pool":64},"puma":{"workers":"2","threads":{"min":"64","max":"64"}},"haproxy":{"max_puma_connections":128},"sidekiq":{"concurrency":25,"timeout":8},"machine":{"processor_count":2,"physical_processor_count":1}}

			   
[32187] - Worker 0 (pid: 1292) booted, phase: 4
[32187] - Stopping 22148 for phased upgrade...
[32187] - TERM sent to 22148...
			   

03/27/2017 11:17:43.000 -0500	
[32187] - Worker 1 (pid: 1397) booted, phase: 4

timestamp=2017-03-27T16:17:43Z env=production frontend=www level=info thread_id=7420240  tag=rails message={"app_info":{"pid":1397,"load_time":"3.273302 seconds","boot_time":"6.384623 seconds","config":{"mysql":{"pool":64},"pg":{"pool":64},"dm":{"pool":64},"puma":{"workers":"2","threads":{"min":"64","max":"64"}},"haproxy":{"max_puma_connections":128},"sidekiq":{"concurrency":25,"timeout":8},"machine":{"processor_count":2,"physical_processor_count":1}},

[32187] - Worker 1 (pid: 1397) booted, phase: 4
```

IN our `config/environment.rb` tl;dr we

```ruby
require 'benchmark'
require 'logger'

app_stats = {pid: Process.pid}

time = Benchmark.realtime {
  # Load the Rails application.
  require File.expand_path('../application', __FILE__)
}
app_stats[:load_time] = "#{format('%f', time)} seconds"

time = Benchmark.realtime {
  # Initialize the Rails application.
  Rails.application.initialize!
}
app_stats[:boot_time] = "#{format('%f', time)} seconds"

require File.expand_path('../../lib/app_formatter', __FILE__)
logger = Logger.new(STDOUT)
logger.formatter = AppFormatter.new
logger.info({app_info: app_stats}.to_json)
```

In our config/puma.rb, we have, in part:

```ruby
workers 2
threads 32, 32
# AWS ELB "Idle timeout" is set to 30s. In order to prevent ELB 500s from unexpected connection closes, ensure that the backend persistent connection timeout is greater than this idle timeout. https://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/config-idle-timeout.html
worker_shutdown_timeout 32
prune_bundler
```

If I flatten out the timeline:

```
03/27/2017 11:17:19.000 -0500 Starting phased worker restart
~~ 11:17:22 app code is being loaded
03/27/2017 11:17:23.000 -0500 got exception
~~ 11:17:26 app starts booting
03/27/2017 11:17:33.000 -0500  app booted, new worker booted, old worker sent TERM
```

https://github.com/puma/puma/blob/master/DEPLOYMENT.md#restarting

```
Use phased-restart (SIGUSR1 or pumactl phased-restart). 
This tells the master to kill off one worker at a time and restart them in your new code. 
This minimizes downtime and staggers the restart nicely. 

WARNING This means that both your old code and your new code will be running concurrently. 
Most deployment solutions already cause that, but it's worth warning you about it again. 
Be careful with your migrations, etc!
```

**Comment by x-yuri** [comment]
I wonder how many issues is in the issue...

I experienced a similar issue with `puma-3.8.2`. `puma` fails to restart after adding more gems.

`puma-restart-issue.sh`:

```sh
#!/usr/bin/env bash
set -eu

puma_pids() {
    local ruby_pids=$(pgrep -u `whoami` ruby | paste -sd,)
    if [ "$ruby_pids" ]; then
        ps -p "$ruby_pids" -o pid,args \
            | grep puma \
            | awk '{print $1}' \
            | paste -sd,
    fi
}

# install rails
rm -rf puma-restart-issue
mkdir $_
cd $_
bundle init &> /dev/null
echo 'gem "rails", "5.2.0"' >> Gemfile
bundle &> /dev/null

# create site
bundle exec rails new ra1 &> /dev/null
mkdir -p log bundle tmp/sockets
cd ra1
sed -Ei 's/gem.*puma.*/gem "puma", "3.8.2"/' Gemfile
rm -r log
ln -sf ../log log
ln -s ../../bundle vendor/bundle
ln -s ../../tmp/sockets tmp/sockets
bundle install --path vendor/bundle &> /dev/null
echo 'ROOT = File.join __dir__, ".."
daemonize
stdout_path = File.join ROOT, "log/stdout"
stderr_path = File.join ROOT, "log/stderr"
stdout_redirect stdout_path, stderr_path, true
pumactl_sock_path = File.join ROOT, "tmp/sockets/pumactl.sock"
activate_control_app "unix://" + pumactl_sock_path
state_path File.join ROOT, "tmp/sockets/puma.state"' > config/puma.rb
DISABLE_SPRING=1 bin/rails g scaffold Post title:string content:text &> /dev/null
cd ..

# create release 1
cp -r ra1 release1

# symlink current to release 1
ln -s release1 current

# start puma
cd current
bundle exec puma

sleep 5
bundle exec pumactl status
cd ..

# create release 2
cp -r release{1,2}
cd release2
echo 'gem "streamio-ffmpeg"' >> Gemfile
bundle &> /dev/null
echo 'require "streamio-ffmpeg"
puts "-- test"' >> app/models/post.rb
cd ..

# symlink current to release 2
ln -sfn release2 current

# restart puma
cd current
bundle exec pumactl restart

sleep 5
bundle exec pumactl status &> /dev/null || {
    echo not running
    more log/std* | cat
}

# stop puma
[ "`puma_pids`" ] && bundle exec pumactl stop

# start puma
bundle exec puma

sleep 5
bundle exec pumactl status
```

output:

```
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 0, max threads: 16
* Environment: production
* Daemonizing...
Puma is started
Command restart sent success
not running
::::::::::::::
log/stderr
::::::::::::::
=== puma startup: 2018-05-05 00:19:26 +0300 ===
=== puma startup: 2018-05-05 00:19:35 +0300 ===
/home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': No such file to load -- streamio-ffmpeg.rb (LoadError)
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
        from /home/u1/puma-restart-issue/release2/app/models/post.rb:3:in `<main>'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:370:in `block in require_or_load'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:13:in `loading'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `load_interlock'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:348:in `require_or_load'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:326:in `depend_on'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in depend_on'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `rescue in depend_on'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `depend_on'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:242:in `require_dependency'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:477:in `each'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:477:in `block in eager_load!'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:475:in `each'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:475:in `eager_load!'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:356:in `eager_load!'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/application/finisher.rb:69:in `each'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /home/u1/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /home/u1/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/u1/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/u1/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/u1/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /home/u1/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /home/u1/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/u1/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /home/u1/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/u1/puma-restart-issue/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
        from /home/u1/puma-restart-issue/release2/config/environment.rb:5:in `<top (required)>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/configuration.rb:313:in `load_rackup'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/configuration.rb:242:in `app'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/runner.rb:138:in `load_and_bind'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/single.rb:87:in `run'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/bin/puma:23:in `load'
        from /home/u1/puma-restart-issue/release1/vendor/bundle/ruby/2.4.0/bin/puma:23:in `<main>'
::::::::::::::
log/stdout
::::::::::::::
=== puma startup: 2018-05-05 00:19:26 +0300 ===
* Listening on tcp://0.0.0.0:9292
* Starting control server on unix://config/../tmp/sockets/pumactl.sock
* Restarting...
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 0, max threads: 16
* Environment: production
* Daemonizing...
=== puma startup: 2018-05-05 00:19:35 +0300 ===
! Unable to load application: LoadError: No such file to load -- streamio-ffmpeg.rb
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 0, max threads: 16
* Environment: production
* Daemonizing...
Puma is started
```

I can't reproduce it with `puma 3.11.4`.

P.S. Well, not really simple script, but what would you expect?...

**Comment by gamafranco** [comment]
Yeah. I'm closing this one and let people create separate ones. This is so old it probably has a 1m long beard...

**Comment by bubba** [comment]
> To my surprise, I got this to work.
> 
> Using puma v2.15.3
> 
> ```ruby
> # in /config/puma.rb
> app = "my_app"
> root = "/home/deployer/apps/#{app}"
> 
> workers  4
> threads  1, 2
> 
> rackup      DefaultRackup
> environment ENV['RAILS_ENV']
> daemonize   true
> 
> directory "#{root}/current"
> pidfile "#{root}/shared/tmp/pids/puma.pid"
> stdout_redirect "#{root}/shared/log/#{Time.now.to_i}_production.log", "#{root}/shared/log/#{Time.now.to_i}_production_errors.log"
> bind "unix:/tmp/puma.socket"
> 
> prune_bundler
> ```
> 
> It is crucial to stop and start puma with these settings to have the master process pick up :directory and, possibly, :prune_bundler directives.
> 
> Then you can `bundle exec pumactl -p {pid_path} phased-restart`
> 
> **NB**, that it may take a few moments for workers to pick up the new code, and also `ps aux` will incorrectly output workers' directory as the master processes' original directory, when the new code will actually be taken from the new symlinked current folder.

That was the trick for me too: We were using capistrano and so had symlinked deploys. Needed to specify `directory '/var/www/app/current'` for puma to actually `exec` our rails app from the new directory.
