### ISSUE TITLE
NoMethodError: undefined method `bytesize' for ["id", 86261648108]:Array

### ISSUE THREAD

**Issue by indirect** [puma/puma#536]
How does this happen, exactly? I'm just running my app in Puma on Heroku. :\

Here's the backtrace:

```
2014-05-20 00:46:01 +0000: Read error: #<NoMethodError: undefined method `bytesize' for ["id", 86261648108]:Array>
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:617:in `block in handle_request'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:615:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:615:in `handle_request'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:361:in `process_client'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:254:in `block in run'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/thread_pool.rb:92:in `call'
/app/vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

**Comment by MilesChatterji** [comment]
How did you solve this? I realize what is happening, I have tried a few .to_s possibilities but with on luck. I thought about writing some extra code to parse, but I thought maybe there is a simpler way, and im just thinking about it to hard. 

Thanks,
-Miles
