### ISSUE TITLE
USR2 restart kills master / worker processes with prune_bundler option

### ISSUE THREAD

**Issue by ghost** [puma/puma#550]
Going to see if I can maybe track the issue down myself, but figure I'd open this issue up in the meantime.

In the first example, with the prune_bundler option in the config, the process dies after the USR2 signal, giving the error that's listed below.  Once this option is removed from config, it restarts properly with this signal (see the second example).

``` bash
$ cat config/puma.rb
threads 0, 4
workers 2
prune_bundler

$ #  bundle exec puma -C config/puma.rb
$ ps -eo pid,cmd | grep '[p]uma 2.8.2'
19478 puma 2.8.2 (tcp://0.0.0.0:9292)

$ kill -USR2 19478

[19478] - Gracefully shutting down workers...
[19478] * Restarting...
/home/foo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find '-C' (>= 0) among 492 total gem(s) (Gem::LoadError)

#---------------------------------
$ cat config/puma.rb
threads 0, 4
workers 2

$ #  bundle exec puma -C config/puma.rb
$ ps -eo pid,cmd | grep '[p]uma 2.8.2'
19594 puma 2.8.2 (tcp://0.0.0.0:9292)

$ kill -USR2 19594  # successful

[19594] Puma starting in cluster mode...
[19594] * Version 2.8.2 (ruby 2.1.2-p95), codename: Sir Edmund Percival Hillary
[19594] * Min threads: 0, max threads: 4
```

**Comment by xiaoronglv** [comment]
We're seeing the same exact thing on 2.9.2 still. If we remove prune_bundler, things work fine. 

```bash
cd /home/webapp/www/searchapp/current && ( RACK_ENV=production ~/.rvm/bin/rvm 2.2.0 do bundle exec puma -C /home/webapp/www/searchapp/shared/puma.rb --daemon )
* Pruning Bundler environment
/home/webapp/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'rack' (= 1.6.4) among 15 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/webapp/.rvm/gems/ruby-2.2.0:/home/webapp/.rvm/gems/ruby-2.2.0@global', execute `gem env` for more information
	from /home/webapp/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /home/webapp/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /home/webapp/www/searchapp/shared/bundle/ruby/2.2.0/gems/puma-2.9.2/bin/puma-wild:20:in `block in <main>'
	from /home/webapp/www/searchapp/shared/bundle/ruby/2.2.0/gems/puma-2.9.2/bin/puma-wild:18:in `each'
	from /home/webapp/www/searchapp/shared/bundle/ruby/2.2.0/gems/puma-2.9.2/bin/puma-wild:18:in `<main>'
```

**Comment by richardrails** [comment]
update it to latest 2.12.3 and it works
