### ISSUE TITLE
Puma 2.9.0 crashing on restart when using prune_bundler setting

### ISSUE THREAD

**Issue by tbuehlmann** [puma/puma#555]
So, this is my `puma.rb` config file:

```ruby
environment env
daemonize
pidfile "/home/user/applications/project/alpha/shared/puma.pid"
state_path "/home/user/applications/project/alpha/shared/puma.state"
workers 4
threads 2,4
bind "unix:///home/user/applications/project/alpha/shared/puma.sock"
prune_bundler
stdout_redirect "/home/user/applications/project/alpha/shared/log/puma_stdout.log", "/home/user/applications/project/alpha/shared/log/puma_stderr.log", true
```

When I issue a restart command using `pumactl` the process dies because of this:

```
/opt/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find '-C' (>= 0) among 98 total gem(s) (Gem::LoadError)
  from /opt/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
  from /opt/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
  from /home/user/applications/project/alpha/shared/bundle/ruby/2.1.0/gems/puma-2.9.0/bin/puma-wild:10:in `block in <main>'
  from /home/user/applications/project/alpha/shared/bundle/ruby/2.1.0/gems/puma-2.9.0/bin/puma-wild:8:in `each'
  from /home/user/applications/project/alpha/shared/bundle/ruby/2.1.0/gems/puma-2.9.0/bin/puma-wild:8:in `<main>'
```

Restarting works without the prune_bundler setting.

**Comment by tbuehlmann** [comment]
Thanks, I think this is solved by now. :)
