### ISSUE TITLE
Cluster phased restart sometimes fails to load gems

### ISSUE THREAD

**Issue by ehlertij** [puma/puma#564]
Worker startup seems to be failing when the `boot.rb` file calls `require 'bundler/setup'`. As a result, the old code will continue running on the old workers which are never cycled out because the first worker continually fails to start up.

This has been an intermittent issue that I've seen on multiple apps over the last few weeks. They're all currently running 2.8.2, but I saw the same issue with 2.8.0.

Here are the versions of things we're running:
* puma 2.8.2
* ruby 2.1.1p76
* rubygems 2.2.2
* bundler 1.6.5

It seems to be related to adding/updating/removing gems, but have not been able to reproduce it consistently.

Here are two distinct stack traces that I've seen with this issue so far.

This is the original stack trace I saw on 2.8.2 in the `puma.error.log`:

```
/usr/local/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions': undefined method `build_extensions' for nil:NilClass (NoMethodError)
  from /usr/local/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
  from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
  from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:924:in `each'
  from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find'
  from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
  from /usr/local/lib/ruby/2.1.0/rubygems.rb:185:in `try_activate'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
  from /srv/www/app_name/releases/20140623144443/config/boot.rb:4:in `<top (required)>'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /srv/www/app_name/releases/20140623144443/config/application.rb:1:in `<top (required)>'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /srv/www/app_name/releases/20140623144443/config/environment.rb:2:in `<top (required)>'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from config.ru:3:in `block in <main>'
  from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  from config.ru:in `new'
  from config.ru:in `<main>'
  from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
  from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
  from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/configuration.rb:96:in `app'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/runner.rb:123:in `app'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/runner.rb:130:in `start_server'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:195:in `worker'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:95:in `block (2 levels) in spawn_workers'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:95:in `fork'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:95:in `block in spawn_workers'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:92:in `times'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:92:in `spawn_workers'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:143:in `check_workers'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:373:in `run'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cli.rb:499:in `run'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/bin/puma-wild:17:in `<main>'
```

This is a more recent one I've seen on 2.8.2 in the `puma.error.log`:

```
/usr/local/lib/ruby/2.1.0/rubygems/specification.rb:748:in `block in _resort!': undefined method `name' for nil:NilClass (NoMethodError)
  from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:747:in `sort!'
  from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:747:in `_resort!'
  from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:699:in `_all'
  from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:882:in `each'
  from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:914:in `find'
  from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:914:in `find_by_path'
  from /usr/local/lib/ruby/2.1.0/rubygems.rb:188:in `try_activate'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
  from /srv/www/app_name/releases/20140721193902/config/boot.rb:4:in `<top (required)>'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /srv/www/app_name/releases/20140721193902/config/application.rb:1:in `<top (required)>'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /srv/www/app_name/releases/20140721193902/config/environment.rb:2:in `<top (required)>'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from config.ru:3:in `block in <main>'
  from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  from config.ru:in `new'
  from config.ru:in `<main>'
  from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
  from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
  from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/configuration.rb:96:in `app'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/runner.rb:123:in `app'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/runner.rb:130:in `start_server'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:195:in `worker'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:95:in `block (2 levels) in spawn_workers'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:95:in `fork'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:95:in `block in spawn_workers'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:92:in `times'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:92:in `spawn_workers'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:143:in `check_workers'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cluster.rb:373:in `run'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/cli.rb:499:in `run'
  from /srv/www/app_name/shared/bundle/ruby/2.1.0/gems/puma-2.8.2/bin/puma-wild:17:in `<main>'
```

This is what I see in the `puma.log` file:

```
[15489] - Starting phased worker restart, phase: 11
[15489] + Changing to /srv/www/app_name/current
[15489] - Stopping 17885 for phased upgrade...
[15489] - TERM sent to 17885...
[1851] + Gemfile in context: /srv/www/app_name/releases/20140724133638/Gemfile
[1858] + Gemfile in context: /srv/www/app_name/releases/20140724133638/Gemfile
[1862] + Gemfile in context: /srv/www/app_name/releases/20140724133638/Gemfile
[1873] + Gemfile in context: /srv/www/app_name/releases/20140724133638/Gemfile
[2036] + Gemfile in context: /srv/www/app_name/releases/20140724133638/Gemfile
[2042] + Gemfile in context: /srv/www/app_name/releases/20140724133638/Gemfile
[2047] + Gemfile in context: /srv/www/app_name/releases/20140724133638/Gemfile
[2052] + Gemfile in context: /srv/www/app_name/releases/20140724133638/Gemfile
.... continues until hard-restart
```

Any thoughts on what's going wrong here? Is it a puma cluster specific issue, or is there something I can do differently with the apps I'm running?

Let me know if you need any more information to help track this down and I'll continue digging myself.

**Comment by evanphx** [comment]
This should be fixed now, lots has been adjusted in the code loading.
