### ISSUE TITLE
Can't bind socket uri containing a space char

### ISSUE THREAD

**Issue by sabamotto** [puma/puma#622]
puma 2.10.2, Ruby 2.1.3p242

config/puma.rb :
```ruby
app_root = "#{File.expand_path('../..', __FILE__)}"
# app_root is "/Users/saba/rails projects/test"

bind "unix://#{app_root}/tmp/sockets/puma.sock"
threads 1, 16
```
run `puma -C config/puma.rb`, then it occurred URI::InvalidURIError.
output :
```
Puma starting in single mode...
* Version 2.10.2 (ruby 2.1.3-p242), codename: Robots on Comets
* Min threads: 1, max threads: 16
* Environment: development
/Users/saba/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:176:in `split': bad URI(is not URI?): unix:///Users/saba/rails projects/test/tmp/sockets/puma.sock (URI::InvalidURIError)
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/binder.rb:83:in `block in parse'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/binder.rb:82:in `each'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/binder.rb:82:in `parse'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/runner.rb:119:in `load_and_bind'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/single.rb:78:in `run'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cli.rb:507:in `run'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/bin/puma:10:in `<top (required)>'
  from /Users/saba/.rbenv/versions/2.1.3/bin/puma:23:in `load'
  from /Users/saba/.rbenv/versions/2.1.3/bin/puma:23:in `<main>'
```

escaped uri :
```ruby
bind URI.escape("unix://#{app_root}/tmp/sockets/puma.sock")
```
retry... Errno::ENOENT.
output :
```
Puma starting in single mode...
* Version 2.10.2 (ruby 2.1.3-p242), codename: Robots on Comets
* Min threads: 1, max threads: 16
* Environment: development
* Listening on unix:///Users/saba/rails%20projects/test/tmp/sockets/puma.sock
/Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/binder.rb:276:in `initialize': No such file or directory - connect(2) for "/Users/saba/rails%20projects/test/tmp/sockets/puma.sock" (Errno::ENOENT)
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/binder.rb:276:in `new'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/binder.rb:276:in `add_unix_listener'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/binder.rb:119:in `block in parse'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/binder.rb:82:in `each'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/binder.rb:82:in `parse'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/runner.rb:119:in `load_and_bind'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/single.rb:78:in `run'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cli.rb:507:in `run'
  from /Users/saba/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/puma-2.10.2/bin/puma:10:in `<top (required)>'
  from /Users/saba/.rbenv/versions/2.1.3/bin/puma:23:in `load'
  from /Users/saba/.rbenv/versions/2.1.3/bin/puma:23:in `<main>'
```

**Comment by sabamotto** [comment]
Thanks momer. I didn't know `Shellwords#shellescape`.
But it occurred an `URI::InvalidURIError` like first code result.

`URI#parse` seems it cannot parse a shell-escaped uri.
```
[1] pry(main)> URI.parse Shellwords.shellescape('unix://space chars/test.sock')
URI::InvalidURIError: bad URI(is not URI?): unix://space\ chars/test.sock
from /Users/sabamotto/.rbenv/versions/2.1.3/lib/ruby/2.1.0/uri/common.rb:176:in `split'
```
