### ISSUE TITLE
Installing on a Raspberry Pi

### ISSUE THREAD

**Issue by ryanmjacobs** [puma/puma#631]
I'm attempting to install puma on a Raspberry Pi. Any help would be appreciated.
```
$ gem install puma
Building native extensions.  This could take a while...
ERROR:  Error installing puma:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20141227-28657-75el68.rb extconf.rb
checking for SSL_CTX_new() in -lssl... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/ruby
        --with-puma_http11-dir
        --without-puma_http11-dir
        --with-puma_http11-include
        --without-puma_http11-include=${puma_http11-dir}/include
        --with-puma_http11-lib
        --without-puma_http11-lib=${puma_http11-dir}/lib
        --with-ssllib
        --without-ssllib
/usr/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
        from /usr/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
        from /usr/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
        from /usr/lib/ruby/2.1.0/mkmf.rb:973:in `block in have_library'
        from /usr/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
        from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
        from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /usr/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
        from /usr/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
        from /usr/lib/ruby/2.1.0/mkmf.rb:968:in `have_library'
        from extconf.rb:5:in `block in <main>'
        from extconf.rb:5:in `each'
        from extconf.rb:5:in `find'
        from extconf.rb:5:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/lib/ruby/gems/2.1.0/gems/puma-2.10.2 for inspection.
Results logged to /usr/lib/ruby/gems/2.1.0/extensions/armv6l-linux/2.1.0/puma-2.10.2/gem_make.out
```

**Comment by ryanmjacobs** [comment]
Solved it. :smile:

On Arch Linux make sure that you have `libffi` installed.
```
$ pacman -S libffi
$ gem install puma
Building native extensions.  This could take a while...
Successfully installed puma-2.10.2
1 gem installed
```
