### ISSUE TITLE
stuck in deadlock

### ISSUE THREAD

**Issue by nateless** [puma/puma#654]
Randomly freezes after some usage, I can't isolate the code. It's a websocket app (tubesock) which synchronize some controller calls with global mutex.

After some time maybe 5 mins maybe 10 hours app is completely frozen. Process strace gives:
```
futex(0x7fc845d826a4, FUTEX_WAIT_PRIVATE, 1, NULL
```

```
(gdb) call rb_backtrace()
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:284:in `block in run'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:301:in `handle_servers'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:301:in `each'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:308:in `block in handle_servers'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:122:in `<<'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:122:in `synchronize'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:130:in `block in <<'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:60:in `spawn_thread'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:60:in `new'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:60:in `initialize'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:262:in `block in run'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:375:in `process_client'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:507:in `handle_request'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/puma-2.11.0/lib/puma/configuration.rb:82:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:31:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
	from /home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
	from /home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:453:in `checkout_and_verify'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_checkout_callbacks'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:454:in `block in checkout_and_verify'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:328:in `verify!'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:91:in `active?'
	from /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:91:in `ping'
```

Rails 4.2
Tubesock 0.2.5
Puma 2.11.0
Ruby 2.2.0

Any ideas how to isolate it and get more information?

**Comment by evanphx** [comment]
The backtrace is inside ActiveRecord's mysql adapter making me think that perhaps the connection pool isn't big enough and thus the app is getting starved? Are you accidentally sharing db connections across threads maybe too?

**Comment by nateless** [comment]
@evanphx well, found that error. The problem was in tubesock gem with redis. Seems like they don't play well. Sorry about it.
