### ISSUE TITLE
server.rb:589:in 'append' TypeError: no implicit conversion of Symbol into String

### ISSUE THREAD

**Issue by imton** [puma/puma#682]
Any idea guys?

````
appserving_1      | I, [2015-04-11T05:32:49.031613 #25]  INFO -- : Completed 400 Bad Request in 14ms (ActiveRecord: 3.0ms)
appserving_1      | 2015-04-11 05:32:49 +0000: Read error: #<TypeError: no implicit conversion of Symbol into String>
appserving_1      | /usr/local/bundle/gems/puma-2.11.1/lib/puma/server.rb:589:in `append'
appserving_1      | /usr/local/bundle/gems/puma-2.11.1/lib/puma/server.rb:589:in `block (2 levels) in handle_request'
appserving_1      | /usr/local/bundle/gems/puma-2.11.1/lib/puma/server.rb:588:in `each'
appserving_1      | /usr/local/bundle/gems/puma-2.11.1/lib/puma/server.rb:588:in `block in handle_request'
appserving_1      | /usr/local/bundle/gems/rack-1.5.2/lib/rack/utils.rb:451:in `block in each'
appserving_1      | /usr/local/bundle/gems/rack-1.5.2/lib/rack/utils.rb:450:in `each'
appserving_1      | /usr/local/bundle/gems/rack-1.5.2/lib/rack/utils.rb:450:in `each'
appserving_1      | /usr/local/bundle/gems/puma-2.11.1/lib/puma/server.rb:574:in `handle_request'
appserving_1      | /usr/local/bundle/gems/puma-2.11.1/lib/puma/server.rb:375:in `process_client'
appserving_1      | /usr/local/bundle/gems/puma-2.11.1/lib/puma/server.rb:262:in `block in run'
appserving_1      | /usr/local/bundle/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `call'
appserving_1      | /usr/local/bundle/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
````

**Comment by evanphx** [comment]
You have a header that is a Symbol rather than a String.

**Comment by imton** [comment]
Thank you
