### ISSUE TITLE
Puma will not start, `environment': wrong number of arguments (0 for 1)

### ISSUE THREAD

**Issue by Epigene** [puma/puma#706]
running `bundle exec puma -C ./config/puma.rb` or `bundle exec pumactl -F config/puma.rb start` returns
`wrong number of arguments (0 for 1)`.

The `bundle exec puma` variant is more verbose, saying

```
/home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/dsl.rb:83:in `environment': wrong number of arguments (0 for 1) (ArgumentError)
	from ./config/puma.rb:12:in `_load_from'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/dsl.rb:20:in `instance_eval'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/dsl.rb:20:in `_load_from'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/dsl.rb:9:in `block in load'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/dsl.rb:8:in `tap'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/dsl.rb:8:in `load'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/configuration.rb:35:in `load'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cli.rb:545:in `parse_options'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cli.rb:190:in `run'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/bin/puma:10:in `<top (required)>'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/bin/puma:23:in `load'
	from /home/deployer/apps/SwissLanguages/releases/6/vendor/bundle/ruby/2.1.0/bin/puma:23:in `<main>'
```

Contents of config/puma.rb are:

```ruby
app = "SwissLanguages"
root = "/home/deployer/apps/#{app}"

workers 5
threads  1, 1

rackup      DefaultRackup
environment (ENV['RACK_ENV'] || 'production')
daemonize   true

pidfile "#{root}/shared/tmp/pids/puma.pid"
stdout_redirect "#{root}/shared/log/#{environment}.log", "#{root}/shared/log/#{environment}_errors.log"
bind "unix:/tmp/puma.socket"
```

**Comment by Epigene** [comment]
The issue was with `#{environment}` parts. Switched to static strings everywhere and got it to work.
