### ISSUE TITLE
How to log request info in puma error log?

### ISSUE THREAD

**Issue by larryzhao** [puma/puma#720]
I just moved from `unicorn` to `puma` and I just found a lot of following exceptions in my puma error log. 

I know mostly they are caused by passing a header key with symbol rather than string. But is there a way to print the request path and other informations along with the exception for debugging?

```
2015-06-25 16:07:28 +0800: Read error: #<TypeError: no implicit conversion of Symbol into String>
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:591:in `append'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:591:in `block (2 levels) in handle_request'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:590:in `each'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:590:in `block in handle_request'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/rack-1.6.1/lib/rack/utils.rb:483:in `block in each'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/rack-1.6.1/lib/rack/utils.rb:482:in `each'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/rack-1.6.1/lib/rack/utils.rb:482:in `each'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:576:in `handle_request'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:375:in `process_client'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:262:in `block in run'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `call'
/home/deployer/deploy/maleskine/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

Best Regards.
Larry

**Comment by evanphx** [comment]
The Rack spec indicates that the return headers must be Strings. You can add a simple rack middleware to iterate through the env and print out any keys that are symbols.
