### ISSUE TITLE
 ! Unable to load application: NoMethodError: undefined method `threads' for main:Object

### ISSUE THREAD

**Issue by zhangsm** [puma/puma#738]
Hi, I hava a problem when using `puma 2.11.2 + rack1.6.4`

```ruby
#!/usr/bin/env puma

threads 6,24
workers 2

rackup      DefaultRackup
environment 'production'

pidfile './tmp/bxr_card_api.pid'
state_path './tmp/bxr_card_api.state'
daemonize true
bind 'unix://./tmp/bxr_card_api.sock'
stdout_redirect "./log/puma.site_a.access.log", "./log/puma.site_a.error.log", true

preload_app!

on_worker_boot do
  puts "hello...........boot........"
end
```

```shell
[ferrari@web-79 bxr_card_api]$ bundle exec puma -C config/puma.rb 
[26466] Puma starting in cluster mode...
[26466] * Version 2.11.2 (ruby 2.0.0-p481), codename: Intrepid Squirrel
[26466] * Min threads: 6, max threads: 24
[26466] * Environment: production
[26466] * Process workers: 2
[26466] * Preloading application
[26466] ! Unable to load application: NoMethodError: undefined method `threads' for main:Object
/opt/rails_apps/bxr_card_api/config/puma.rb:3:in `<top (required)>': undefined method `threads' for main:Object (NoMethodError)
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `require'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `each'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `block in require'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `each'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `require'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481@global/gems/bundler-1.7.11/lib/bundler.rb:134:in `require'
	from /opt/rails_apps/bxr_card_api/config/application.rb:10:in `<top (required)>'
	from /opt/rails_apps/bxr_card_api/config/environment.rb:3:in `require'
	from /opt/rails_apps/bxr_card_api/config/environment.rb:3:in `<top (required)>'
	from config.ru:1:in `require'
	from config.ru:1:in `block in <main>'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/puma-2.11.2/lib/puma/configuration.rb:102:in `load_rackup'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/puma-2.11.2/lib/puma/configuration.rb:69:in `app'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/puma-2.11.2/lib/puma/runner.rb:113:in `load_and_bind'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/puma-2.11.2/lib/puma/cluster.rb:302:in `run'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/puma-2.11.2/lib/puma/cli.rb:216:in `run'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/gems/puma-2.11.2/bin/puma:10:in `<top (required)>'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/bin/puma:23:in `load'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/bin/puma:23:in `<main>'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
	from /home/ferrari/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
```

what should i solve it?

**Comment by zhangsm** [comment]
add `require 'puma'` in `config/puma.rb`

**Comment by delwaterman** [comment]
I still get this issue with the require statement:

```
#!/usr/bin/env puma
require 'puma'

puts 'Reading puma configuration'
threads ENV.fetch("PUMA_THREADS_MIN", 4), ENV.fetch("PUMA_THREADS_MAX", 16)
```

```
15:50 $ ./config/puma.rb
Reading puma configuration
Puma starting in single mode...
* Version 2.16.0 (ruby 2.3.0-p0), codename: Midwinter Nights Trance
* Min threads: 4, max threads: 16
* Environment: development
Reading puma configuration
! Unable to load application: NoMethodError: undefined method `threads' for main:Object
/Users/orion.delwaterman/code/greenhouse/mobile_notification_server/config/puma.rb:3:in `<top (required)>': undefined method `threads' for main:Object (NoMethodError)
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:42:in `require'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:42:in `parse_file'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/configuration.rb:155:in `load_rackup'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/configuration.rb:99:in `app'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/runner.rb:114:in `load_and_bind'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/single.rb:79:in `run'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/cli.rb:214:in `run'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/bin/puma:10:in `<top (required)>'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.3.0/bin/puma:23:in `load'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.3.0/bin/puma:23:in `<main>'
```

**Comment by evanphx** [comment]
@delwaterman You're not loading a config file at all, you're just running a random ruby file while requiring puma.

**Comment by kwngo** [comment]
@evanphx How exactly would you load a config file?

**Comment by leoi11** [comment]
@kwngo What @delwaterman was doing was `./config/puma.rb` instead of `bundle exec puma -C config/puma.rb`.

**Comment by NoSkillGuy** [comment]
` bundle exec puma -C /data/app_name/shared/config/puma.rb` and i am still getting the same issue.

**Comment by marcello-telles** [comment]
i'm having the same issue, even adding `require 'puma'`. @NoSkillGuy did you came up with any solutions for this?

**Comment by ashishcompwiz** [comment]
some kind of similar issue here
`ashish@AshishPC:/mnt/d/Websites/Developing/BudgetSchoolErp3_Fedena_SchoolMaster/BudgetSchoolErp3$ bundle exec puma -C config/puma.rb
Puma starting in single mode...
* Version 2.16.0 (ruby 1.8.7-p376), codename: Midwinter Nights Trance
* Min threads: 5, max threads: 5
* Environment: development
! Unable to load application: NoMethodError: undefined method `parse_file' for Rack::Builder:Class
bundler: failed to load command: puma (/home/ashish/.rvm/gems/ruby-1.8.7-head/bin/puma)
NoMethodError: undefined method `parse_file' for Rack::Builder:Class
  /home/ashish/.rvm/gems/ruby-1.8.7-head/gems/puma-2.16.0/lib/puma/configuration.rb:155:in `load_rackup'
  /home/ashish/.rvm/gems/ruby-1.8.7-head/gems/puma-2.16.0/lib/puma/configuration.rb:99:in `app'
  /home/ashish/.rvm/gems/ruby-1.8.7-head/gems/puma-2.16.0/lib/puma/runner.rb:114:in `load_and_bind'
  /home/ashish/.rvm/gems/ruby-1.8.7-head/gems/puma-2.16.0/lib/puma/single.rb:79:in `run'
  /home/ashish/.rvm/gems/ruby-1.8.7-head/gems/puma-2.16.0/lib/puma/cli.rb:214:in `run'
  /home/ashish/.rvm/gems/ruby-1.8.7-head/gems/puma-2.16.0/bin/puma:10
  /home/ashish/.rvm/gems/ruby-1.8.7-head/bin/puma:19:in `load'
  /home/ashish/.rvm/gems/ruby-1.8.7-head/bin/puma:19`

**Comment by W-Mills** [comment]
Is puma in your gemfiles?:
```
group :production do
  gem "puma"
end
```

**Comment by will3216** [comment]
I ran into this issue earlier today. Turns out I had mistakenly put my config in /config/initializers/puma.rb instead of /config/puma.rb
