### ISSUE TITLE
NoMethodError during startup

### ISSUE THREAD

**Issue by kapso** [puma/puma#767]
This is on Heroku. Ruby 2.2.2. Puma `2.13.1`

```
2015-08-15T18:54:59.616692+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/puma-2.13.1/lib/puma/cli.rb:353:in `block (2 levels) in setup_options': undefined method `<<' for nil:NilClass (NoMethodError)
2015-08-15T18:54:59.616722+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1427:in `call'
2015-08-15T18:54:59.616724+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1427:in `block in parse_in_order'
2015-08-15T18:54:59.616726+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
2015-08-15T18:54:59.616727+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
2015-08-15T18:54:59.616728+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
2015-08-15T18:54:59.616730+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
2015-08-15T18:54:59.616731+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
2015-08-15T18:54:59.616732+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/puma-2.13.1/lib/puma/cli.rb:518:in `parse_options'
2015-08-15T18:54:59.616734+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/puma-2.13.1/lib/puma/cli.rb:189:in `run'
2015-08-15T18:54:59.616735+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/puma-2.13.1/bin/puma:10:in `<top (required)>'
2015-08-15T18:54:59.616737+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/bin/puma:23:in `load'
2015-08-15T18:54:59.616740+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/bin/puma:23:in `<main>'
20
```

**Comment by rosswilson** [comment]
I'm getting the exact same error, with Ruby 2.2.2. I've got

```
workers 2
```

defined in my config file. Removing this gets rid of the error. I'm looking into the root cause now.
