### ISSUE TITLE
Error in reactor loop escaped: undefined method `closed?' for #<Puma::Client

### ISSUE THREAD

**Issue by mwpastore** [puma/puma#835]
I'm seeing the following error message under extremely high concurrency (-w 8 -t 8:32):

```
Error in reactor loop escaped: undefined method `closed?' for #<Puma::Client:0x3f7e046103d4 @ready=false> (NoMethodError)
/FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/reactor.rb:31:in `block in run_internal'
/FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/reactor.rb:31:in `any?'
/FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/reactor.rb:31:in `rescue in run_internal'
/FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/reactor.rb:28:in `run_internal'
/FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/reactor.rb:138:in `block in run_in_thread'
```

Ruby 2.2.3, Puma 2.15.3, fairly simple Sinatra/Sequel application for FrameworkBenchmarks: https://github.com/mwpastore/FrameworkBenchmarks/tree/master/frameworks/Ruby/sinatra-sequel

**Comment by mwpastore** [comment]
Boom! Thanks @evanphx! Can't wait for 3.0.
