### ISSUE TITLE
undefined method `before_fork' for #<Puma::DSL:0x00000001133db8> (NoMethodError)

### ISSUE THREAD

**Issue by vincenzor** [puma/puma#886]
Hi,

I'm using capistrano/puma and I have a problem when trying to add a before_fork on my puma.rb config file. I'm using Ruby 2.3.0 with RVM.

I run:
`cap production puma:start `

this is the command that is executed:
`RACK_ENV=production /usr/local/rvm/bin/rvm default do bundle exec puma -C /PATH_TO_MY_APP/shared/puma.rb --daemon`

Here is the log:
```
DEBUG [6ef5b3ad] 	: undefined method `before_fork' for #<Puma::DSL:0x00000001133db8> (NoMethodError)
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/gems/puma-2.11.3/lib/puma/dsl.rb:20:in `instance_eval'
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/gems/puma-2.11.3/lib/puma/dsl.rb:20:in `_load_from'
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/gems/puma-2.11.3/lib/puma/dsl.rb:9:in `block in load'
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/gems/puma-2.11.3/lib/puma/dsl.rb:8:in `tap'
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/gems/puma-2.11.3/lib/puma/dsl.rb:8:in `load'
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/gems/puma-2.11.3/lib/puma/configuration.rb:35:in `load'
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/gems/puma-2.11.3/lib/puma/cli.rb:545:in `parse_options'
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/gems/puma-2.11.3/lib/puma/cli.rb:190:in `run'
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/gems/puma-2.11.3/bin/puma:10:in `<top (required)>'
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/bin/puma:23:in `load'
DEBUG [6ef5b3ad] 		from /PATH_TO_MY_APP/shared/bundle/ruby/2.3.0/bin/puma:23:in `<main>'
```

In simply added this in `puma.rb`:
```
before_fork do
  # configuration here
end
```

Any idea??

**Comment by nathansamson** [comment]
This option was only added in v2.13, you are running 2.11. Upgrade to the
latest version of puma to resolve this issue.

Regards,
Nathan

**Comment by vincenzor** [comment]
Yes! That was my problem!

Sorry about that...
