### ISSUE TITLE
Puma throws "missing_extensions?" error when using phased restarts after multiple deploys.

### ISSUE THREAD

**Issue by zzsnzmn** [puma/puma#900]
I've tested this with puma 2.13.4, 2.15.3, 2.16.0 and ruby 2.2.2 and ruby 2.3.0.

Using a phased restart as the mechanism for reloading our app code, if the directory that puma was started in is deleted it starts throwing this exception:

```
/home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/stub_specification.rb:148:in `missing_extensions?': undefined method `missing_extensions?' for nil:NilClass (NoMethodError)
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/basic_specification.rb:71:in `contains_requirable_file?'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1037:in `block in find_by_path'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1036:in `each'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1036:in `find'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1036:in `find_by_path'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems.rb:189:in `try_activate'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/rack/builder.rb:180:in `initialize'
    from config.ru:in `new'
    from config.ru:in `<main>'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/rack/builder.rb:170:in `eval'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/rack/builder.rb:170:in `new_from_string'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/rack/builder.rb:161:in `parse_file'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/configuration.rb:129:in `load_rackup'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/configuration.rb:96:in `app'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/runner.rb:123:in `app'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/runner.rb:130:in `start_server'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/cluster.rb:215:in `worker'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/cluster.rb:109:in `block (2 levels) in spawn_workers'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/cluster.rb:109:in `fork'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/cluster.rb:109:in `block in spawn_workers'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/cluster.rb:105:in `times'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/cluster.rb:105:in `spawn_workers'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/cluster.rb:157:in `check_workers'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/cluster.rb:427:in `run'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/lib/puma/cli.rb:215:in `run'
    from /var/www/app/releases/20160208195047/vendor/bundle/ruby/2.3.0/gems/puma-2.13.4/bin/puma-wild:31:in `<main>'
```

This works fine with ruby `2.2.2` and puma version `2.13.4` and `2.15.3`. Puma version `2.16.0` doesn't work with either 2.2.2 or 2.3.0.

My puma config looks like this:
```
workers 3
threads_count = 6
threads(1, threads_count)

environment ENV.fetch('RACK_ENV', 'development')

stdout_redirect 'log/puma.log', 'log/puma.err.log', true

prune_bundler true

directory "/var/www/app/current"

bind 'unix:///var/www/app/shared/tmp/sockets/puma.sock'
```

It's puzzling that bumping to ruby 2.3.0 would make this issue occur. I have yet to test the 3.0.0rc, but if I have time tonight I'll update this post with the results of that. I don't think it's a configuration issue, but I haven't ruled that out.

It seems that this issue might be related to #776

**Comment by evanphx** [comment]
Are you changing ruby versions during the phased upgrade? That's not going to be supported because you're changing rubygems versions with code loaded, very likely causing this issue.

**Comment by zzsnzmn** [comment]
I stopped puma before switching ruby versions and puma version.

Another shot in the dark--- could it be the config.ru we have?
```
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment', __FILE__)
run Rails.application
```

**Comment by evanphx** [comment]
No, that `config.ru` is fine. You're accidentally loading rubygems twice from multiple paths is my guess, you might want to look at the environment to see what is on the load path.
