### ISSUE TITLE
Incompatible library version

### ISSUE THREAD

**Issue by bgvo** [puma/puma#917]
```
$ puma
[68441] Puma starting in cluster mode...
[68441] * Version 3.0.2 (ruby 2.2.3-p173), codename: Plethora of Penguin Pinatas
[68441] * Min threads: 5, max threads: 5
[68441] * Environment: development
[68441] * Process workers: 2
[68441] * Preloading application
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.0 because its extensions are not built.  Try: gem pristine byebug --version 8.2.0
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Ignoring iconv-1.0.4 because its extensions are not built.  Try: gem pristine iconv --version 1.0.4
Ignoring pg-0.18.3 because its extensions are not built.  Try: gem pristine pg --version 0.18.3
[68441] ! Unable to load application: Gem::LoadError: You have already activated puma 3.0.2, but your Gemfile requires puma 2.16.0. Prepending `bundle exec` to your command may solve this.
/Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:34:in `block in setup': You have already activated puma 3.0.2, but your Gemfile requires puma 2.16.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:19:in `setup'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/setup.rb:8:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/borjagvo/MyStuff/webdev/Work/Gemfeed/dev/repos/educartis/config/boot.rb:3:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/borjagvo/MyStuff/webdev/Work/Gemfeed/dev/repos/educartis/config/application.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/borjagvo/MyStuff/webdev/Work/Gemfeed/dev/repos/educartis/config/environment.rb:2:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from config.ru:3:in `block in <main>'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-3.0.2/lib/puma/configuration.rb:310:in `load_rackup'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-3.0.2/lib/puma/configuration.rb:239:in `app'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-3.0.2/lib/puma/runner.rb:119:in `load_and_bind'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-3.0.2/lib/puma/cluster.rb:361:in `run'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-3.0.2/lib/puma/launcher.rb:173:in `run'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-3.0.2/lib/puma/cli.rb:74:in `run'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-3.0.2/bin/puma:10:in `<top (required)>'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/bin/puma:23:in `load'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/bin/puma:23:in `<main>'
```

Using `bundle exec`:

```
$ bundle exec puma
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.0 because its extensions are not built.  Try: gem pristine byebug --version 8.2.0
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Ignoring iconv-1.0.4 because its extensions are not built.  Try: gem pristine iconv --version 1.0.4
Ignoring pg-0.18.3 because its extensions are not built.  Try: gem pristine pg --version 0.18.3
[68473] Puma starting in cluster mode...
[68473] * Version 2.16.0 (ruby 2.2.3-p173), codename: Midwinter Nights Trance
[68473] * Min threads: 5, max threads: 5
[68473] * Environment: development
[68473] * Process workers: 2
[68473] * Preloading application
/Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/pg-0.18.3/lib/pg.rb:4:in `require': incompatible library version - /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/pg-0.18.3/lib/pg_ext.bundle (fatal)
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/pg-0.18.3/lib/pg.rb:4:in `<top (required)>'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/borjagvo/MyStuff/webdev/Work/Gemfeed/dev/repos/educartis/config/application.rb:7:in `<top (required)>'
	from /Users/borjagvo/MyStuff/webdev/Work/Gemfeed/dev/repos/educartis/config/environment.rb:2:in `require'
	from /Users/borjagvo/MyStuff/webdev/Work/Gemfeed/dev/repos/educartis/config/environment.rb:2:in `<top (required)>'
	from config.ru:3:in `require'
	from config.ru:3:in `block in <main>'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/configuration.rb:155:in `load_rackup'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/configuration.rb:99:in `app'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/runner.rb:114:in `load_and_bind'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/cluster.rb:318:in `run'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/cli.rb:214:in `run'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/bin/puma:10:in `<top (required)>'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/bin/puma:23:in `load'
	from /Users/borjagvo/.rvm/gems/ruby-2.3.0/bin/puma:23:in `<main>'
```

**Comment by bgvo** [comment]
I solved this by installing OS updates and running `gem pristine <gem>' as indicated by stdout.
