### ISSUE TITLE
`write': U+00F1 from UTF-8 to US-ASCII (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by rubenmoya** [puma/puma#930]
So, I'm getting this error, I have no idea how to fix it. Any ideas?

Using: puma-3.1.0, rails-4.2.6, ruby 2.1.6p336

```
bundle stdout: Puma starting in single mode...
bundle stderr: /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/gems/puma-3.1.0/lib/puma/events.rb:68:in `write': U+00F1 from UTF-8 to US-ASCII (Encoding::UndefinedConversionError)
	from /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/gems/puma-3.1.0/lib/puma/events.rb:68:in `puts'
	from /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/gems/puma-3.1.0/lib/puma/events.rb:68:in `log'
	from /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/gems/puma-3.1.0/lib/puma/runner.rb:20:in `log'
	from /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/gems/puma-3.1.0/lib/puma/runner.rb:84:in `output_header'
	from /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/gems/puma-3.1.0/lib/puma/single.rb:52:in `run'
	from /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/gems/puma-3.1.0/lib/puma/launcher.rb:173:in `run'
	from /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/gems/puma-3.1.0/lib/puma/cli.rb:74:in `run'
	from /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/gems/puma-3.1.0/bin/puma:10:in `<top (required)>'
	from /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/bin/puma:23:in `load'
	from /home/ubuntu/xxxxxx/shared/bundle/ruby/2.1.0/bin/puma:23:in `<main>'
```

EDIT: I found the problem here:

`CODE_NAME = "El Niño Winter Wonderland".freeze`

Removing the `ñ` solves the problem

**Comment by dapicester** [comment]
The same for puma-3.1.0-java and jruby-1.7.19.

I can confirm that removing the `ñ` solves the problem.

**Comment by tbrisker** [comment]
Please try https://github.com/puma/puma/pull/924, I believe it should fix this error.

**Comment by dapicester** [comment]
@tbrisker Yes, that fixes the error. Thanks!

I believe we should wait for the next Puma release to get the fix, right?

**Comment by evanphx** [comment]
3.1.1 out now with this fix.
