### ISSUE TITLE
NameError: uninitialized constant when trying to start puma

### ISSUE THREAD

**Issue by evenluo** [puma/puma#972]
Recently I was trying to deploy my app to server , It work just fine on my Mac in same puma setting. But when I run 

``` shell
puma -C /path/to/puma.rb
```

got this error:

```
[467] ! Unable to load application: NameError: uninitialized constant Api::V1::BaseController::Authenticatable
/var/www/apollo/releases/1/app/controllers/api/v1/base_controller.rb:2:in `<class:BaseController>': uninitialized constant Api::V1::BaseController::Authenticatable (NameError)
	from /var/www/apollo/releases/1/app/controllers/api/v1/base_controller.rb:1:in `<top (required)>'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:471:in `each'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:471:in `block in eager_load!'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:469:in `each'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:469:in `eager_load!'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:346:in `eager_load!'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:56:in `each'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /var/www/apollo/releases/1/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
	from /var/www/apollo/releases/1/config/environment.rb:5:in `<top (required)>'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from config.ru:3:in `block in <main>'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:313:in `load_rackup'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:242:in `app'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/puma-3.4.0/lib/puma/runner.rb:123:in `load_and_bind'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/puma-3.4.0/lib/puma/cluster.rb:370:in `run'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/puma-3.4.0/lib/puma/launcher.rb:172:in `run'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/puma-3.4.0/lib/puma/cli.rb:74:in `run'
	from /home/deploy/.rvm/gems/ruby-2.3.0/gems/puma-3.4.0/bin/puma:10:in `<top (required)>'
	from /home/deploy/.rvm/gems/ruby-2.3.0/bin/puma:23:in `load'
	from /home/deploy/.rvm/gems/ruby-2.3.0/bin/puma:23:in `<main>'
	from /home/deploy/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/deploy/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

and That's it! I don't know where to find other information. Because the puma error log file haven't been created yet. But If I use the same setting on my Mac, puma did started and worked just fine. Even run rails s in the production environment. 

Anyone have a clue? thx.

Here is my puma setting file:

```
#!/usr/bin/env puma

#rails environment
environment 'production'
threads 2, 8
workers 1

#project
app_name = "apollo"
#project path
application_path = "/var/www/#{app_name}"
#set to current in project path
directory "#{application_path}/current"

#setting puma
pidfile "#{application_path}/shared/tmp/pids/puma.pid"
state_path "#{application_path}/shared/tmp/sockets/puma.state"
stdout_redirect "#{application_path}/shared/log/puma.stdout.log", "#{application_path}/shared/log/puma.stderr.log"
bind "unix://#{application_path}/shared/tmp/sockets/#{app_name}.sock"
activate_control_app "unix://#{application_path}/shared/tmp/sockets/pumactl.sock"

#backgournd running
daemonize true
on_restart do
  puts 'On restart...'
end

#for cluster mode
preload_app!
```

**Comment by evanphx** [comment]
This is entirely within your app, it's not puma related. You're referencing a constant that isn't available.

**Comment by evenluo** [comment]
@evanphx  yes, you are right. It's a load issue caused by a capital letter 😂 .

**Comment by sseguku** [comment]
I have the same issue with uploading my rails app to Heroku application

**Comment by LeandroBever** [comment]
I have the same...just look the env.local. Maybe changing the env. it works.
